table Bridge_UserTerritory
	lineageTag: 4f4a8b23-7a8c-4b7d-9c51-4a6e8b9a1f2c

	column UserID
		dataType: int64
		formatString: 0
		lineageTag: 2d0d7b16-8a4c-4e39-a1c5-3a2c928b5c10
		summarizeBy: none
		sourceColumn: UserID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column territory_id
		dataType: int64
		formatString: 0
		lineageTag: 7f4c1d7a-0b4e-4a71-8f8d-3d3c0b2a81a5
		summarizeBy: none
		sourceColumn: territory_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Bridge_UserTerritory = m
		mode: import
		source = ```
						// ============================================================
						// Bridge_UserTerritory
						// Purpose: map users to *multiple* territories (ORG track)
						// Source: public users_territory
						// Output: distinct (UserID, territory_id)
						// ============================================================
						let
						    UsersTerritory = #"public users_territory",
						    Selected = Table.SelectColumns(
						        UsersTerritory,
						        {"users_id", "territory_id"},
						        MissingField.UseNull
						    ),
						    Filtered = Table.SelectRows(
						        Selected,
						        each [users_id] <> null and [territory_id] <> null
						    ),
						    Renamed = Table.RenameColumns(
						        Filtered,
						        {{"users_id", "UserID"}},
						        MissingField.Ignore
						    ),
						    Typed = Table.TransformColumnTypes(
						        Renamed,
						        {
						            {"UserID", Int64.Type},
						            {"territory_id", Int64.Type}
						        }
						    ),
						    DistinctRows = Table.Distinct(Typed, {"UserID", "territory_id"})
						in
						    DistinctRows
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

