/// DateFilterParam - Disconnected Parameter Table for Date Filter Radio Buttons
/// This table is intentionally NOT connected to any other table (no relationships)
/// Used for FR-7-10: Date filter with radio buttons (Daily, WTD, MTD, YTD)
/// Reference: FRD_IMPLEMENTATION_GUIDE.md - Phase 5.5 Relationship Schema Verification

table DateFilterParam
	lineageTag: 7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d

	column FilterOption
		dataType: string
		lineageTag: 8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e
		summarizeBy: none
		sourceColumn: FilterOption

		annotation SummarizationSetBy = Automatic

	column FilterOrder
		dataType: int64
		lineageTag: 9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f
		formatString: 0
		summarizeBy: none
		sourceColumn: FilterOrder

		annotation SummarizationSetBy = Automatic

	partition DateFilterParam = m
		mode: import
		source =
			let
			    Source = #table(
			        {"FilterOption", "FilterOrder"},
			        {
			            {"Daily", 1},
			            {"WTD", 2},
			            {"MTD", 3},
			            {"YTD", 4}
			        }
			    ),
			    TypedTable = Table.TransformColumnTypes(Source, {
			        {"FilterOption", type text},
			        {"FilterOrder", Int64.Type}
			    })
			in
			    TypedTable

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation IsDisconnectedParameterTable = true

