table Dim_Retailer2
	lineageTag: e3de5c87-8561-43d3-acfe-6afb779253e5

	measure Total_Retailer_Count =
			
			CALCULATE (
			    COUNTROWS ( Dim_Retailer2 ),
			    REMOVEFILTERS ()
			)
		formatString: 0
		lineageTag: 494c4da3-8064-4783-9073-4043a84f1a6a

	measure Active_Retailers = ```
			
			CALCULATE (
			    DISTINCTCOUNT ( Fact_RetailOrder[retailer_id])
			)
			
			```
		formatString: 0
		lineageTag: 0b8cf235-897f-4bcf-a1bc-69c2735cb7e0

	measure Potential_Retailers = ```
			
			[Total_Retailer_Count] - [Active_Retailers]
			
			```
		formatString: 0
		lineageTag: 0bc4536e-31c9-4ef1-87d4-39dc9094990c

	measure Retailer_Visit_Count =
			
			CALCULATE (
			    [Total_Visits2],
			    Fact_Visit2[ClientType] = "Retailer",
			    TREATAS (
			        VALUES ( Dim_Retailer2[id] ),
			        Fact_Visit[ClientID]
			    )
			)
		formatString: 0
		lineageTag: e2e4e721-55b7-4358-8202-18fe43e3e839

	measure Total_Retailer_UncoverRetailer_Count = [Total_Retailer_Count]+[Total_Uncover_Retailer]
		formatString: 0
		lineageTag: fea9aa75-015b-4932-8485-eef26b568a99

	measure Total_Retailers_No_Duplicate_Logic =
			
			VAR Retailers_Not_From_Uncovered =
			    CALCULATE (
			        COUNTROWS ( Dim_Retailer2 ),
			        ISBLANK ( Dim_Retailer2[uncovered_retailer_id] )
			    )
			VAR Total_Uncovered =
			    [Total_Uncover_Retailer]
			RETURN
			Retailers_Not_From_Uncovered + Total_Uncovered
		formatString: 0
		lineageTag: 7d3b9304-8de4-4b31-b536-343b13778788

	measure Total_Retailers_date =
			
			CALCULATE (
			    DISTINCTCOUNT ( Dim_Retailer[RetailerID] ),
			    TREATAS (
			        VALUES ( Dim_Date[Date] ),
			        Dim_Retailer2[created_at]
			    )
			)
		formatString: 0
		lineageTag: 2f0e6f03-2d04-4800-a897-b343dff7ec14

	measure Total_Retailer_Count_ACL = ```
			
			CALCULATE (
			    COUNTROWS ( Dim_Retailer2 ),
			    REMOVEFILTERS (),
			    Dim_Retailer2[organization_id] = 1
			)
			
			```
		formatString: 0
		lineageTag: 93b756e1-dd7f-4b68-ae7a-7a0e7185b798

	measure Total_Retailer_Count_AIL = ```
			
			CALCULATE (
			    COUNTROWS ( Dim_Retailer2 ),
			    REMOVEFILTERS (),
			    Dim_Retailer2[organization_id] = 2
			)
			
			```
		formatString: 0
		lineageTag: d8d36a27-8468-4a67-b1f9-9e61195da922

	measure Total_Retailer_Count_ACSL = ```
			
			CALCULATE (
			    COUNTROWS ( Dim_Retailer2 ),
			    REMOVEFILTERS (),
			    Dim_Retailer2[organization_id] = 3
			)
			
			```
		formatString: 0
		lineageTag: 219a4f6c-18f6-4f44-8632-5c0da32b90a4

	measure Retailers_Created =
			
			CALCULATE (
			    COUNTROWS ( Dim_Retailer2 ),
			    USERELATIONSHIP (
			        Dim_Retailer2[created_at],
			        Dim_Date[Date]
			    )
			)
		formatString: 0
		lineageTag: 34c8b27d-906c-49be-ba50-d575acc39441

	measure Avg_Active_Retailers_per_Territory =
			
			AVERAGEX (
			    VALUES ( Dim_Retailer2[territory_id] ),
			    CALCULATE (
			        DISTINCTCOUNT ( Fact_RetailOrder[retailer_id] )
			    )
			)
		lineageTag: b4068819-72d5-498e-8e94-154bf8c63b40

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Active_vs_Target_Retailer_ACL_Display =
			
			VAR Active = [Active_Retailers]
			VAR Total = [Total_Retailer_Count_ACL_Target]
			RETURN
			FORMAT ( Active, "0" ) & " / " & FORMAT ( Total, "0" )
		lineageTag: 1e5497f1-8dc0-4f63-ac56-0e9545d1c458

	measure Active_vs_Target_Retailer_ACL_Percentage =
			
			DIVIDE (
			    [Active_Retailers],
			    [Total_Retailer_Count_ACL_Target],
			    0
			)
		lineageTag: 4fca6624-fbb0-4d14-b3bb-359b8f90fef7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Avg_Volume_Per_Retailer_Target = 200
		formatString: 0
		lineageTag: ef33d3f3-07b8-4f6f-95a0-85c24ff3d83c

	measure Avg_Vol_Retailer_vs_Target_Retailer_Percentage =
			
			DIVIDE (
			    [Avg_Volume_Per_Retailer],
			    [Avg_Volume_Per_Retailer_Target],
			    0
			)
		lineageTag: b46478d2-5b32-44c1-8a23-3da7a3d68af9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Avg_Vol_Retailer_vs_Target_Retailer_Display =
			
			VAR Avg_Vol = [Avg_Volume_Per_Retailer]
			VAR Target = [Avg_Volume_Per_Retailer_Target]
			RETURN
			FORMAT ( Avg_Vol, "0" ) & " / " & FORMAT ( Target, "0" )
		lineageTag: ab08809c-100c-4e0f-a959-5059609f3cb1

	measure Total_Retailer_Count_ACL_Target = 500
		formatString: 0
		lineageTag: 5bd93c34-6dcc-4d46-b9b2-0c5bf87d06d0

	measure Active_Uncovered_Retailers = ```
			
			CALCULATE (
			    DISTINCTCOUNT ( Fact_RetailOrder[uncovered_retailer_id]),
			    YEAR ( Fact_RetailOrder[order_date] ) = YEAR ( TODAY() ),
			    MONTH ( Fact_RetailOrder[order_date] ) = MONTH ( TODAY() )
			)
			
			```
		formatString: 0
		lineageTag: 8bbbe1ec-7bb2-45cd-ad58-5cbce396fa7d

	measure Active_Retailer = [Active_Retailers] - [Active_Uncovered_Retailers]
		formatString: 0
		lineageTag: 5f625da2-7a8f-4d44-906f-11828df82e5c

	measure Active_Bazaars = DISTINCTCOUNT(Dim_Retailer2[bazaar_id])
		formatString: 0
		lineageTag: 2876c87a-e2fb-4064-a90d-fad60fc9f7fc

	measure Retailer_Count2 =
			
			DISTINCTCOUNT(Fact_RetailOrder[retailer_id])
		formatString: 0
		lineageTag: ba776f89-6c70-4d23-9b1e-2c3ae39e6386

	column id
		dataType: int64
		formatString: 0
		lineageTag: 735ed7bd-cb0c-437d-be94-978e04f55a82
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column bkash_no
		dataType: string
		lineageTag: 2c12a540-913b-4001-86ae-d6bf8c7526e4
		summarizeBy: none
		sourceColumn: bkash_no

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: Long Date
		lineageTag: cbff3a70-d858-454a-8926-f319d196a6da
		summarizeBy: none
		sourceColumn: created_at

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column mobile_no
		dataType: string
		lineageTag: c7933e8d-af67-4d6e-ad43-20c3a3c206f5
		summarizeBy: none
		sourceColumn: mobile_no

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 7768f55b-6e53-41a3-a5e0-bcbf5f5ac5c4
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 57d61cd3-14d2-46fc-a9f9-702470f0beb6
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column bazaar_id
		dataType: int64
		formatString: 0
		lineageTag: e4e6a537-061a-46b9-a23c-84d547ad23b2
		summarizeBy: sum
		sourceColumn: bazaar_id

		annotation SummarizationSetBy = Automatic

	column dealer_id
		dataType: int64
		formatString: 0
		lineageTag: d124380a-d7fa-4dc5-aaf4-7a5d92c484ad
		summarizeBy: sum
		sourceColumn: dealer_id

		annotation SummarizationSetBy = Automatic

	column organization_id
		dataType: int64
		formatString: 0
		lineageTag: afeb536e-7cca-4d59-abed-3e7ea0a328c5
		summarizeBy: sum
		sourceColumn: organization_id

		annotation SummarizationSetBy = Automatic

	column uncovered_retailer_id
		dataType: int64
		formatString: 0
		lineageTag: 6613916b-b17a-4339-9fc2-85ac0ac4663a
		summarizeBy: sum
		sourceColumn: uncovered_retailer_id

		annotation SummarizationSetBy = Automatic

	column lat
		dataType: string
		lineageTag: d35b1250-f4a4-4a23-97c7-b9c10a713b39
		summarizeBy: none
		sourceColumn: lat

		annotation SummarizationSetBy = Automatic

	column lng
		dataType: string
		lineageTag: 16da49f6-963e-46cd-b844-937da1ebe8ba
		summarizeBy: none
		sourceColumn: lng

		annotation SummarizationSetBy = Automatic

	column ClientKey
		dataType: string
		lineageTag: f441a436-a0c5-4474-b3b0-53b8bf3a98ac
		summarizeBy: none
		sourceColumn: ClientKey

		annotation SummarizationSetBy = Automatic

	column Territory_id =
			
			CALCULATE (
			    MAX ( Dim_Bazaar_Territory[territory_id] ),
			    FILTER (
			        Dim_Bazaar_Territory,
			        Dim_Bazaar_Territory[bazaar_list_id] = Dim_Retailer2[bazaar_id]
			            && Dim_Bazaar_Territory[organization_id] = Dim_Retailer2[organization_id]
			    )
			)
		formatString: 0
		lineageTag: c9916e54-5b94-436f-a425-0d108bbf1942
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column deleted_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 11de6519-c257-401b-93b8-1c28083081b1
		summarizeBy: none
		sourceColumn: deleted_at

		variation Variation
			isDefault
			relationship: 39072252-064b-4972-a5a5-45d7d05079d1
			defaultHierarchy: LocalDateTable_90e08de2-7a4a-4e7d-9b73-b56ea1e03101.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition Dim_Retailer2 = m
		mode: import
		source =
				let
				  Source = #"public retailers",
				  #"Removed columns" = Table.RemoveColumns(Source, {"address", "area_of_work", "assigned_agm", "assigned_asm", "assigned_gm", "assigned_sr", "assigned_sr_name", "assigned_zsm", "bank_name", "bazaar_name", "bazaar_name_text", "branch_name", "created_by", "dealer_name", "dob", "experience", "is_deleted", "message", "moduleid", "ac_name", "ac_no", "namespaceid", "nid_no", "nid_photo", "owned_by", "photo", "preferred_mfs", "present_address", "recordid", "revision", "routing_no", "shop_address", "shop_name", "updated_at", "updated_by", "created_by_user_id", "deleted_by", "updated_by_user", "business_type", "location_photo", "location_save_for_later", "mfs", "mfs_type", "code", "module_code_id"}),
				  #"Changed column type" = Table.TransformColumnTypes(#"Removed columns", {{"created_at", type date}}),
				  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Changed column type", "ClientKey", each "Retailer-" & Text.From([id])), {{"ClientKey", type text}})
				in
				  #"Added custom"

	annotation PBI_ResultType = Table

