table Dim_Client_Simple
	lineageTag: 2b116964-7d92-44bc-877a-08c63930e55d

	measure Visits_by_Type =
			CALCULATE(
			    [Total_Visits],
			    ALLEXCEPT('Fact_Visit', 'Fact_Visit'[visit_type])
			)
		formatString: 0
		lineageTag: d8252c2a-daea-40a9-8d01-a8dbc6364f9d

		changedProperty = IsHidden

	measure Total_Site_Visits =
			CALCULATE(
			    [Total_Visits],
			    'Fact_Visit'[ClientType] = "Site"
			)
		formatString: 0
		lineageTag: 1d887731-4d05-4abc-9a84-9ec92770e978

		changedProperty = IsHidden

	measure Total_Dealers =
			// Total distinct Dealers - respects filters from Fact_Visit (e.g., location filters)
			VAR ClientsWithVisits = DISTINCT('Fact_Visit'[ClientKey])
			VAR DealerClients = CALCULATETABLE(
				DISTINCT('Dim_Client_Simple'[ClientKey]),
				'Dim_Client_Simple'[ClientType] = "Dealer",
				REMOVEFILTERS('Fact_Visit')
			)
			RETURN
			COUNTROWS(
				INTERSECT(DealerClients, ClientsWithVisits)
			)
		formatString: #,##0
		displayFolder: Client Counts
		lineageTag: aa1b2c3d-4e5f-6789-0abc-def012345678

		changedProperty = IsHidden

	measure Total_Retailers =
			// Total distinct Retailers - respects filters from Fact_Visit (e.g., location filters)
			VAR ClientsWithVisits = DISTINCT('Fact_Visit'[ClientKey])
			VAR RetailerClients = CALCULATETABLE(
				DISTINCT('Dim_Client_Simple'[ClientKey]),
				'Dim_Client_Simple'[ClientType] = "Retailer",
				REMOVEFILTERS('Fact_Visit')
			)
			RETURN
			COUNTROWS(
				INTERSECT(RetailerClients, ClientsWithVisits)
			)
		formatString: #,##0
		displayFolder: Client Counts
		lineageTag: bb2c3d4e-5f6a-7890-1bcd-ef0123456789

		changedProperty = IsHidden

	measure Total_Sites =
			// Total distinct Sites - respects filters from Fact_Visit (e.g., location filters)
			VAR ClientsWithVisits = DISTINCT('Fact_Visit'[ClientKey])
			VAR SiteClients = CALCULATETABLE(
				DISTINCT('Dim_Client_Simple'[ClientKey]),
				'Dim_Client_Simple'[ClientType] = "Site",
				REMOVEFILTERS('Fact_Visit')
			)
			RETURN
			COUNTROWS(
				INTERSECT(SiteClients, ClientsWithVisits)
			)
		formatString: #,##0
		displayFolder: Client Counts
		lineageTag: cc3d4e5f-6a7b-8901-2cde-f01234567890

		changedProperty = IsHidden

	measure Total_Engineers =
			// Total distinct Engineers - respects filters from Fact_Visit (e.g., location filters)
			VAR ClientsWithVisits = DISTINCT('Fact_Visit'[ClientKey])
			VAR EngineerClients = CALCULATETABLE(
				DISTINCT('Dim_Client_Simple'[ClientKey]),
				'Dim_Client_Simple'[ClientType] = "Engineer",
				REMOVEFILTERS('Fact_Visit')
			)
			RETURN
			COUNTROWS(
				INTERSECT(EngineerClients, ClientsWithVisits)
			)
		formatString: #,##0
		displayFolder: Client Counts
		lineageTag: dd4e5f6a-7b8c-9012-3def-012345678901

		changedProperty = IsHidden

	measure Total_Contractors =
			// Total distinct Contractors - respects filters from Fact_Visit (e.g., location filters)
			VAR ClientsWithVisits = DISTINCT('Fact_Visit'[ClientKey])
			VAR ContractorClients = CALCULATETABLE(
				DISTINCT('Dim_Client_Simple'[ClientKey]),
				'Dim_Client_Simple'[ClientType] = "Contractor",
				REMOVEFILTERS('Fact_Visit')
			)
			RETURN
			COUNTROWS(
				INTERSECT(ContractorClients, ClientsWithVisits)
			)
		formatString: #,##0
		displayFolder: Client Counts
		lineageTag: ee5f6a7b-8c9d-0123-4ef0-123456789012

		changedProperty = IsHidden

	measure Total_IHBs =
			// Total distinct IHBs - respects filters from Fact_Visit (e.g., location filters)
			VAR ClientsWithVisits = DISTINCT('Fact_Visit'[ClientKey])
			VAR IHBClients = CALCULATETABLE(
				DISTINCT('Dim_Client_Simple'[ClientKey]),
				'Dim_Client_Simple'[ClientType] = "IHB",
				REMOVEFILTERS('Fact_Visit')
			)
			RETURN
			COUNTROWS(
				INTERSECT(IHBClients, ClientsWithVisits)
			)
		formatString: #,##0
		displayFolder: Client Counts
		lineageTag: ff6a7b8c-9d0e-1234-5f01-234567890123

		changedProperty = IsHidden

	measure Total_Influencers =
			// Total distinct Influencers (Engineers + Contractors) - respects filters from Fact_Visit
			VAR ClientsWithVisits = DISTINCT('Fact_Visit'[ClientKey])
			VAR InfluencerClients = CALCULATETABLE(
				DISTINCT('Dim_Client_Simple'[ClientKey]),
				'Dim_Client_Simple'[ClientType] IN {"Engineer", "Contractor"},
				REMOVEFILTERS('Fact_Visit')
			)
			RETURN
			COUNTROWS(
				INTERSECT(InfluencerClients, ClientsWithVisits)
			)
		formatString: #,##0
		displayFolder: Client Counts
		lineageTag: 0a7b8c9d-0e1f-2345-6012-345678901234

		changedProperty = IsHidden

	measure UniqueRoleCount =
			// FIXED: Now shows Total Visits (row count) to differentiate from Unique_Clients_Visited
			// Previously was DISTINCTCOUNT which was identical to Unique_Clients_Visited
			COUNTROWS('Fact_Visit')
		formatString: #,##0
		displayFolder: Client Counts
		lineageTag: 1b8c9d0e-1f2a-3456-7123-456789012345

		changedProperty = IsHidden

	measure Total_Clients_In_Filter =
			// Total clients in dimension that match current filter context
			// Ignores Fact_Visit filters - shows ALL clients in dimension for current ClientType/Location filters
			CALCULATE(
				DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
				REMOVEFILTERS('Fact_Visit'),
				REMOVEFILTERS('Fact_ProjectConversion')
			)
		formatString: #,##0
		displayFolder: Client Counts
		lineageTag: 2a9c0d1e-2f3a-4567-8234-567890123456

		changedProperty = IsHidden

	measure Dealer_Count =
			// Visits to Dealers - counts visits where client type is Dealer
			CALCULATE(
				COUNTROWS('Fact_Visit'),
				'Dim_Client_Simple'[ClientType] = "Dealer"
			)
		formatString: #,##0
		displayFolder: Visit Counts by Type
		lineageTag: 2c9d0e1f-2a3b-4567-8234-567890123456

		changedProperty = IsHidden

	measure Retailer_Count =
			// Visits to Retailers - counts visits where client type is Retailer
			CALCULATE(
				COUNTROWS('Fact_Visit'),
				'Dim_Client_Simple'[ClientType] = "Retailer"
			)
		formatString: #,##0
		displayFolder: Visit Counts by Type
		lineageTag: 3d0e1f2a-3b4c-5678-9345-678901234567

		changedProperty = IsHidden

	measure Site_Count =
			// Visits to Sites - counts visits where client type is Site
			CALCULATE(
				COUNTROWS('Fact_Visit'),
				'Dim_Client_Simple'[ClientType] = "Site"
			)
		formatString: #,##0
		displayFolder: Visit Counts by Type
		lineageTag: 4e1f2a3b-4c5d-6789-0456-789012345678

		changedProperty = IsHidden

	measure Engineer_Count =
			// Visits to Engineers - counts visits where client type is Engineer
			CALCULATE(
				COUNTROWS('Fact_Visit'),
				'Dim_Client_Simple'[ClientType] = "Engineer"
			)
		formatString: #,##0
		displayFolder: Visit Counts by Type
		lineageTag: 5f2a3b4c-5d6e-7890-1567-890123456789

		changedProperty = IsHidden

	measure Contractor_Count =
			// Visits to Contractors - counts visits where client type is Contractor
			CALCULATE(
				COUNTROWS('Fact_Visit'),
				'Dim_Client_Simple'[ClientType] = "Contractor"
			)
		formatString: #,##0
		displayFolder: Visit Counts by Type
		lineageTag: 6a3b4c5d-6e7f-8901-2678-901234567890

		changedProperty = IsHidden

	measure IHB_Count =
			// Visits to IHBs - counts visits where client type is IHB
			CALCULATE(
				COUNTROWS('Fact_Visit'),
				'Dim_Client_Simple'[ClientType] = "IHB"
			)
		formatString: #,##0
		displayFolder: Visit Counts by Type
		lineageTag: 7b4c5d6e-7f8a-9012-3789-012345678901

		changedProperty = IsHidden

	measure Clients_in_User_Bazaar =
			VAR UserBazaar = SELECTEDVALUE(Dim_User[BazaarID])
			VAR LocalClients =
				CALCULATE(
					DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
					USERELATIONSHIP(Dim_User[BazaarID], Dim_Bazaar[BazaarID]),
					USERELATIONSHIP('Dim_Client_Simple'[BazaarID], Dim_Bazaar[BazaarID]),
					'Dim_Client_Simple'[BazaarID] <> -1,
					REMOVEFILTERS('Fact_Visit'),
					REMOVEFILTERS('Fact_ProjectConversion')
				)
			VAR NationalClients =
				CALCULATE(
					DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
					'Dim_Client_Simple'[BazaarID] = -1,
					REMOVEFILTERS('Fact_Visit'),
					REMOVEFILTERS('Fact_ProjectConversion')
				)
			RETURN
				IF(ISBLANK(UserBazaar), BLANK(), LocalClients + NationalClients)
		formatString: #,##0
		displayFolder: User-Bazaar Analysis
		lineageTag: 8c5d6e7f-8a9b-0123-4890-123456789012

		changedProperty = IsHidden

	measure Retailers_in_User_Bazaar =
			CALCULATE(
				DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
				USERELATIONSHIP(Dim_User[BazaarID], Dim_Bazaar[BazaarID]),
				USERELATIONSHIP('Dim_Client_Simple'[BazaarID], Dim_Bazaar[BazaarID]),
				'Dim_Client_Simple'[ClientType] = "Retailer",
				REMOVEFILTERS('Fact_Visit'),
				REMOVEFILTERS('Fact_ProjectConversion')
			)
		formatString: #,##0
		displayFolder: User-Bazaar Analysis
		lineageTag: 9d6e7f8a-9b0c-1234-5901-234567890123

		changedProperty = IsHidden

	measure Sites_in_User_Bazaar =
			CALCULATE(
				DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
				USERELATIONSHIP(Dim_User[BazaarID], Dim_Bazaar[BazaarID]),
				USERELATIONSHIP('Dim_Client_Simple'[BazaarID], Dim_Bazaar[BazaarID]),
				'Dim_Client_Simple'[ClientType] = "Site",
				REMOVEFILTERS('Fact_Visit'),
				REMOVEFILTERS('Fact_ProjectConversion')
			)
		formatString: #,##0
		displayFolder: User-Bazaar Analysis
		lineageTag: 0e7f8a9b-0c1d-2345-6012-345678901234

		changedProperty = IsHidden

	measure IHBs_in_User_Bazaar =
			CALCULATE(
				DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
				USERELATIONSHIP(Dim_User[BazaarID], Dim_Bazaar[BazaarID]),
				USERELATIONSHIP('Dim_Client_Simple'[BazaarID], Dim_Bazaar[BazaarID]),
				'Dim_Client_Simple'[ClientType] = "IHB",
				REMOVEFILTERS('Fact_Visit'),
				REMOVEFILTERS('Fact_ProjectConversion')
			)
		formatString: #,##0
		displayFolder: User-Bazaar Analysis
		lineageTag: 1f8a9b0c-1d2e-3456-7123-456789012345

		changedProperty = IsHidden

	measure Dealers_National =
			CALCULATE(
				DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
				'Dim_Client_Simple'[ClientType] = "Dealer",
				'Dim_Client_Simple'[BazaarID] = -1,
				REMOVEFILTERS('Fact_Visit'),
				REMOVEFILTERS('Fact_ProjectConversion')
			)
		formatString: #,##0
		displayFolder: User-Bazaar Analysis
		lineageTag: 2a9b0c1d-2e3f-4567-8234-567890123456

		changedProperty = IsHidden

	measure Engineers_National =
			CALCULATE(
				DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
				'Dim_Client_Simple'[ClientType] = "Engineer",
				'Dim_Client_Simple'[BazaarID] = -1,
				REMOVEFILTERS('Fact_Visit'),
				REMOVEFILTERS('Fact_ProjectConversion')
			)
		formatString: #,##0
		displayFolder: User-Bazaar Analysis
		lineageTag: 3b0c1d2e-3f4a-5678-9345-678901234567

		changedProperty = IsHidden

	measure Contractors_National =
			CALCULATE(
				DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
				'Dim_Client_Simple'[ClientType] = "Contractor",
				'Dim_Client_Simple'[BazaarID] = -1,
				REMOVEFILTERS('Fact_Visit'),
				REMOVEFILTERS('Fact_ProjectConversion')
			)
		formatString: #,##0
		displayFolder: User-Bazaar Analysis
		lineageTag: 4c1d2e3f-4a5b-6789-0456-789012345678

		changedProperty = IsHidden

	measure User_Has_Bazaar = IF(NOT ISBLANK(SELECTEDVALUE(Dim_User[BazaarID])), 1, 0)
		formatString: 0
		displayFolder: User-Bazaar Analysis
		lineageTag: 5d2e3f4a-5b6c-7890-1567-890123456789

		changedProperty = IsHidden

	measure User_Bazaar_Coverage =
			VAR UserBazaar = SELECTEDVALUE(Dim_User[BazaarID])
			VAR LocalCount =
				CALCULATE(
					DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
					USERELATIONSHIP(Dim_User[BazaarID], Dim_Bazaar[BazaarID]),
					USERELATIONSHIP('Dim_Client_Simple'[BazaarID], Dim_Bazaar[BazaarID]),
					'Dim_Client_Simple'[BazaarID] <> -1,
					REMOVEFILTERS('Fact_Visit'),
					REMOVEFILTERS('Fact_ProjectConversion')
				)
			VAR NationalCount =
				CALCULATE(
					DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
					'Dim_Client_Simple'[BazaarID] = -1,
					REMOVEFILTERS('Fact_Visit'),
					REMOVEFILTERS('Fact_ProjectConversion')
				)
			RETURN
				IF(ISBLANK(UserBazaar),
					"No Bazaar Assigned",
					"Local: " & FORMAT(LocalCount, "#,##0") & " | National: " & FORMAT(NationalCount, "#,##0")
				)
		displayFolder: User-Bazaar Analysis
		lineageTag: 6e3f4a5b-6c7d-8901-2678-901234567890

		changedProperty = IsHidden

	measure 'Total Site + IHB' =
			// Total distinct Sites + IHBs - ignores fact table filter context
			CALCULATE(
				DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
				'Dim_Client_Simple'[ClientType] IN {"Site", "IHB"},
				REMOVEFILTERS('Fact_Visit'),
				REMOVEFILTERS('Fact_ProjectConversion')
			)
		formatString: #,##0
		displayFolder: Client Counts
		lineageTag: 3278bbb7-5350-46ee-b37b-8d99ebedb46f

		changedProperty = IsHidden

	measure Site_Status_Selected_Month =
			VAR _IsSite = SELECTEDVALUE('Dim_Client_Simple'[ClientType]) = "Site"
			VAR _ContextMaxDate = COALESCE(MAX('Dim_Date'[Date]), TODAY())
			VAR _MonthStart = DATE(YEAR(_ContextMaxDate), MONTH(_ContextMaxDate), 1)
			VAR _MonthEnd = EOMONTH(_MonthStart, 0)
			VAR _ActivityThisMonth =
				CALCULATE(
					COUNTROWS('Fact_ProjectConversion'),
					REMOVEFILTERS('Dim_Date'),
					'Dim_Date'[Date] >= _MonthStart,
					'Dim_Date'[Date] <= _MonthEnd
				)
			VAR _ActivityEver =
				CALCULATE(
					COUNTROWS('Fact_ProjectConversion'),
					REMOVEFILTERS('Dim_Date')
				)
			RETURN
				IF(
					NOT _IsSite,
					BLANK(),
					IF(
						_ActivityEver = 0,
						"Potential",
						IF(_ActivityThisMonth > 0, "Active", "Inactive")
					)
				)
		displayFolder: Site Analysis\Status
		lineageTag: 7c2b9f1d-4c8e-4c9a-9df6-02c5c3c6f7a1

	measure Total_Active_Sites =
			// Active Sites = Sites with at least one conversion ever
			COALESCE(
				CALCULATE(
					DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
					'Dim_Client_Simple'[ClientType] = "Site",
					'Dim_Client_Simple'[Active Sites] = TRUE(),
					REMOVEFILTERS('Fact_Visit'),
					REMOVEFILTERS('Fact_ProjectConversion')
				),
				0
			)
		formatString: #,##0
		displayFolder: Site Analysis\Counts
		lineageTag: 2c8a6c3f-1b2d-4b7a-9b8b-3d6a2d7c1e4f

	measure Total_Potential_Sites =
			// Potential Sites = Sites with no conversions ever
			COALESCE(
				CALCULATE(
					DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
					'Dim_Client_Simple'[ClientType] = "Site",
					'Dim_Client_Simple'[Potential Site] = TRUE(),
					REMOVEFILTERS('Fact_Visit'),
					REMOVEFILTERS('Fact_ProjectConversion')
				),
				0
			)
		formatString: #,##0
		displayFolder: Site Analysis\Counts
		lineageTag: 7a4e1c2d-9f3b-4d5a-8c1e-6b2d9a3f4c5e

	measure Total_Count =
			// Base measure: Total distinct clients (unaffected by fact table filters)
			CALCULATE(
				DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
				REMOVEFILTERS('Fact_Visit'),
				REMOVEFILTERS('Fact_ProjectConversion')
			)
		formatString: #,##0
		lineageTag: 043a2bb6-bf84-4bef-b672-bc13005a5654

	measure Total_Clients =
			// Total distinct clients - respects dimension filters but ignores fact table context
			CALCULATE(
				DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]),
				REMOVEFILTERS('Fact_Visit'),
				REMOVEFILTERS('Fact_ProjectConversion')
			)
		formatString: #,##0
		displayFolder: Client Counts
		lineageTag: 043a2bb6-bf84-4bef-b672-bc13005a5655

	measure Clients_With_Visits =
			// Clients that have at least one visit - respects current filter context
			DISTINCTCOUNT('Fact_Visit'[ClientKey])
		formatString: #,##0
		displayFolder: Client Activity
		lineageTag: 143b2cc7-cf85-4cef-c783-cc14006b6756

	measure Clients_With_Conversions =
			// Clients that have at least one conversion/order - respects current filter context
			DISTINCTCOUNT('Fact_ProjectConversion'[ClientKey])
		formatString: #,##0
		displayFolder: Client Activity
		lineageTag: 243c2dd8-df86-5def-d894-dd25007c7867

	measure Clients_With_Any_Activity =
			// Clients with either visits or conversions - union of both fact tables
			VAR _VisitClients = VALUES('Fact_Visit'[ClientKey])
			VAR _ConversionClients = VALUES('Fact_ProjectConversion'[ClientKey])
			VAR _AllActiveClients = DISTINCT(UNION(_VisitClients, _ConversionClients))
			RETURN COUNTROWS(_AllActiveClients)
		formatString: #,##0
		displayFolder: Client Activity
		lineageTag: 343d2ee9-ef97-6efa-e9a5-ee36008d8978

	measure Visit_Coverage_Rate =
			// % of total clients that have been visited
			VAR _TotalClients = [Total_Clients]
			VAR _VisitedClients = [Clients_With_Visits]
			RETURN DIVIDE(_VisitedClients, _TotalClients, 0)
		formatString: 0.0%
		displayFolder: Client Activity\Rates
		lineageTag: 443e2ffa-ff08-7f0b-f0b6-ff47009e9089

	measure Conversion_Coverage_Rate =
			// % of total clients that have conversions/orders
			VAR _TotalClients = [Total_Clients]
			VAR _ConvertedClients = [Clients_With_Conversions]
			RETURN DIVIDE(_ConvertedClients, _TotalClients, 0)
		formatString: 0.0%
		displayFolder: Client Activity\Rates
		lineageTag: 543f3aab-aa19-8a1c-a1c7-aa58010f0190

	column ClientKey
		dataType: string
		isKey
		lineageTag: 0a17d132-6804-48b8-8d27-c2cf96bc5a03
		summarizeBy: distinctCount
		sourceColumn: ClientKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column ClientID
		dataType: int64
		formatString: 0
		lineageTag: a2a76574-ee27-4b38-9474-5c2c04bddc8c
		summarizeBy: count
		sourceColumn: ClientID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientName
		dataType: string
		lineageTag: d591ffac-1fc0-4240-960a-d02e462b3285
		summarizeBy: none
		sourceColumn: ClientName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientType
		dataType: string
		lineageTag: 1f8bfd75-e214-4b94-8990-f4f09112fb38
		summarizeBy: none
		sourceColumn: ClientType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SubType
		dataType: string
		lineageTag: 4344f130-38b3-4120-9f5b-2b6175b7660b
		summarizeBy: none
		sourceColumn: SubType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientCategory
		dataType: string
		lineageTag: 044beb90-910b-4a15-a867-e14423fe0aca
		summarizeBy: none
		sourceColumn: ClientCategory

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ResponsibleRole
		dataType: string
		lineageTag: 46db7c9a-8622-4ff6-9702-f3cedb90efc2
		summarizeBy: none
		sourceColumn: ResponsibleRole

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ResponsibleRoleRLS
		dataType: string
		lineageTag: 0c2e4094-24ce-4b72-87d8-c0569f56acd3
		summarizeBy: none
		sourceColumn: ResponsibleRoleRLS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BazaarID
		dataType: int64
		formatString: 0
		lineageTag: 10924ccf-70ef-4bd0-b352-0269c55c4a88
		summarizeBy: none
		sourceColumn: BazaarID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EntityGroup =
			SWITCH(
			    [ClientType],
			    "Dealer", "Customers",
			    "Retailer", "Customers",
			    "Engineer", "Influencers",
			    "Contractor", "Influencers",
			    "Site", "Consumers",
			    "IHB", "Consumers",
			    "Influencers"
			)
		lineageTag: 8f901234-5678-9abc-def0-123456789abc
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column bd_territory_id
		dataType: int64
		formatString: 0
		lineageTag: f0560325-b75e-4917-9390-dc9dba0de7d6
		summarizeBy: sum
		sourceColumn: bd_territory_id

		annotation SummarizationSetBy = Automatic

	column territory_id
		dataType: int64
		formatString: 0
		lineageTag: 0292c323-2eec-4535-b109-b70f4a27a7e2
		summarizeBy: sum
		sourceColumn: territory_id

		annotation SummarizationSetBy = Automatic

	column TerritoryName
		dataType: string
		lineageTag: 283eb63f-c665-441a-8bf2-227fc71a5679
		summarizeBy: none
		sourceColumn: TerritoryName

		annotation SummarizationSetBy = Automatic

	column AreaName
		dataType: string
		lineageTag: 68787523-c45b-474f-8e02-b0e2b214652d
		summarizeBy: none
		sourceColumn: AreaName

		annotation SummarizationSetBy = Automatic

	column site_status =
			VAR _IsSite = [ClientType] = "Site"
			VAR _HasEver =
				COUNTROWS(RELATEDTABLE('Fact_ProjectConversion'))
			RETURN
				IF(
					NOT _IsSite,
					BLANK(),
					IF(_HasEver > 0, "Active", "Potential")
				)
		lineageTag: 1fd41b25-6b34-4ef6-a1d9-2a9c4b7f3d5e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Active Sites' =
			VAR _IsSite = [ClientType] = "Site"
			VAR _HasEver =
				COUNTROWS(RELATEDTABLE('Fact_ProjectConversion'))
			RETURN
				IF(_IsSite && _HasEver > 0, TRUE(), FALSE())
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8b23a8d3-2bb8-4c6f-8b7b-8c2d1e3b4a5f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Potential Site' =
			VAR _IsSite = [ClientType] = "Site"
			VAR _HasEver =
				COUNTROWS(RELATEDTABLE('Fact_ProjectConversion'))
			RETURN
				IF(_IsSite && _HasEver = 0, TRUE(), FALSE())
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4c6d2c5b-9b39-4e5c-93d3-5d0a1b2c3d4e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Dim_Client_Simple = m
		mode: import
		source = ```
				// ============================================================
				// Dim_Client_Simple - Unified Client Dimension (Simplified)
				// No complex joins - uses direct columns from source tables
				// 
				// Client Types (6 per PRD):
				// 1. Sites (potential_site) - BDO managed
				// 2. Retailers - SR managed
				// 3. IHB (ihb_registration) - CRO/BDO managed
				// 4. Dealers - CRO managed
				// 5. Engineers - BDO managed
				// 6. Contractors - CRO managed
				// 
				// SCHEMA NOTES (Nov 2025):
				// - Retailers: is_deleted = "NO" (text)
				// - Dealers: is_deleted = "NO" (text)
				// - IHB, Engineers, Contractors: no delete column
				// ============================================================
				
				let
				    // ============================================================
				    // 1. SITES (potential_site)
				    // ============================================================
				    SitesSource = #"public potential_site",
				    SitesFiltered = Table.SelectRows(SitesSource, each [delete_status] = "NO"),
				    SitesBase = Table.SelectColumns(SitesFiltered, {
				        "id", "project_name", "bazaar_id", "site_type", "territory_name", "area_name"
				    }),
				    SitesFinal = Table.AddColumn(SitesBase, "ClientType", each "Site", type text),
				    SitesFinal2 = Table.AddColumn(SitesFinal, "ResponsibleRole", each "BDO", type text),
				    SitesRenamed = Table.RenameColumns(SitesFinal2, {
				        {"id", "ClientID"}, 
				        {"project_name", "ClientName"}, 
				        {"site_type", "SubType"},
				        {"bazaar_id", "BazaarID"},
				        {"territory_name", "TerritoryName"},
				        {"area_name", "AreaName"}
				    }),
				    SitesClean = Table.SelectColumns(SitesRenamed, {
				        "ClientID", "ClientName", "ClientType", "SubType", "ResponsibleRole", "BazaarID", "TerritoryName", "AreaName"
				    }),
				
				    // ============================================================
				    // 2. RETAILERS
				    // ============================================================
				    RetailersSource = #"public retailers",
				    RetailersFiltered = Table.SelectRows(RetailersSource, each [is_deleted] = "NO"),
				    RetailersBase = Table.SelectColumns(RetailersFiltered, {"id", "name", "shop_name", "bazaar_id"}),
				    RetailersFinal = Table.AddColumn(RetailersBase, "ClientType", each "Retailer", type text),
				    RetailersFinal2 = Table.AddColumn(RetailersFinal, "SubType", each null, type text),
				    RetailersFinal3 = Table.AddColumn(RetailersFinal2, "ResponsibleRole", each "SR", type text),
				    RetailersFinal4 = Table.AddColumn(RetailersFinal3, "TerritoryName", each null, type text),
				    RetailersFinal5 = Table.AddColumn(RetailersFinal4, "AreaName", each null, type text),
				    RetailersRenamed = Table.RenameColumns(RetailersFinal5, {
				        {"id", "ClientID"}, {"name", "ClientName"}, {"bazaar_id", "BazaarID"}
				    }),
				    RetailersClean = Table.SelectColumns(RetailersRenamed, {
				        "ClientID", "ClientName", "ClientType", "SubType", "ResponsibleRole", "BazaarID", "TerritoryName", "AreaName"
				    }),
				
				    // ============================================================
				    // 3. IHB (ihb_registration) - No delete column
				    // ============================================================
				    IHBSource = #"public ihb_registration",
				    IHBBase = Table.SelectColumns(IHBSource, {"id", "bazaar_id", "end_user"}),
				    IHBFinal = Table.AddColumn(IHBBase, "ClientType", each "IHB", type text),
				    IHBFinal2 = Table.AddColumn(IHBFinal, "ClientName", each "IHB-" & Text.From([id]), type text),
				    IHBFinal3 = Table.AddColumn(IHBFinal2, "SubType", each [end_user], type text),
				    IHBFinal4 = Table.AddColumn(IHBFinal3, "ResponsibleRole", each "CRO,BDO", type text),
				    IHBFinal5 = Table.AddColumn(IHBFinal4, "TerritoryName", each null, type text),
				    IHBFinal6 = Table.AddColumn(IHBFinal5, "AreaName", each null, type text),
				    IHBRenamed = Table.RenameColumns(IHBFinal6, {{"id", "ClientID"}, {"bazaar_id", "BazaarID"}}),
				    IHBClean = Table.SelectColumns(IHBRenamed, {
				        "ClientID", "ClientName", "ClientType", "SubType", "ResponsibleRole", "BazaarID", "TerritoryName", "AreaName"
				    }),
				
				    // ============================================================
				    // 4. DEALERS
				    // ============================================================
				    DealersSource = #"public dealers",
				    DealersFiltered = Table.SelectRows(DealersSource, each [is_deleted] = "NO"),
				    DealersBase = Table.SelectColumns(DealersFiltered, {"id", "name", "shop_name", "district_name_text"}),
				    DealersFinal = Table.AddColumn(DealersBase, "ClientType", each "Dealer", type text),
				    DealersFinal2 = Table.AddColumn(DealersFinal, "SubType", each null, type text),
				    DealersFinal3 = Table.AddColumn(DealersFinal2, "ResponsibleRole", each "CRO", type text),
				    // BazaarID = -1 represents "National" for clients available nationally
				    DealersFinal4 = Table.AddColumn(DealersFinal3, "BazaarID", each -1, Int64.Type),
				    DealersFinal5 = Table.AddColumn(DealersFinal4, "TerritoryName", each null, type text),
				    DealersFinal6 = Table.AddColumn(DealersFinal5, "AreaName", each [district_name_text], type text),
				    DealersRenamed = Table.RenameColumns(DealersFinal6, {{"id", "ClientID"}, {"name", "ClientName"}}),
				    DealersClean = Table.SelectColumns(DealersRenamed, {
				        "ClientID", "ClientName", "ClientType", "SubType", "ResponsibleRole", "BazaarID", "TerritoryName", "AreaName"
				    }),
				
				    // ============================================================
				    // 5. ENGINEERS - No delete column
				    // ============================================================
				    EngineersSource = #"public engineers",
				    EngineersBase = Table.SelectColumns(EngineersSource, {"id", "engineer_type", "consultancy_firm"}),
				    EngineersFinal = Table.AddColumn(EngineersBase, "ClientType", each "Engineer", type text),
				    EngineersFinal2 = Table.AddColumn(EngineersFinal, "ClientName", each 
				        if [consultancy_firm] <> null and [consultancy_firm] <> "" then [consultancy_firm] 
				        else "Engineer-" & Text.From([id]), type text),
				    EngineersFinal3 = Table.AddColumn(EngineersFinal2, "SubType", each [engineer_type], type text),
				    EngineersFinal4 = Table.AddColumn(EngineersFinal3, "ResponsibleRole", each "BDO", type text),
				    // BazaarID = -1 represents "National" for clients available nationally
				    EngineersFinal5 = Table.AddColumn(EngineersFinal4, "BazaarID", each -1, Int64.Type),
				    EngineersFinal6 = Table.AddColumn(EngineersFinal5, "TerritoryName", each null, type text),
				    EngineersFinal7 = Table.AddColumn(EngineersFinal6, "AreaName", each null, type text),
				    EngineersRenamed = Table.RenameColumns(EngineersFinal7, {{"id", "ClientID"}}),
				    EngineersClean = Table.SelectColumns(EngineersRenamed, {
				        "ClientID", "ClientName", "ClientType", "SubType", "ResponsibleRole", "BazaarID", "TerritoryName", "AreaName"
				    }),
				
				    // ============================================================
				    // 6. CONTRACTORS - No delete column
				    // ============================================================
				    ContractorSource = #"public contractor",
				    ContractorBase = Table.SelectColumns(ContractorSource, {"id"}),
				    ContractorFinal = Table.AddColumn(ContractorBase, "ClientType", each "Contractor", type text),
				    ContractorFinal2 = Table.AddColumn(ContractorFinal, "ClientName", each "Partner-" & Text.From([id]), type text),
				    ContractorFinal3 = Table.AddColumn(ContractorFinal2, "SubType", each "Partner", type text),
				    ContractorFinal4 = Table.AddColumn(ContractorFinal3, "ResponsibleRole", each "CRO", type text),
				    // BazaarID = -1 represents "National" for clients available nationally
				    ContractorFinal5 = Table.AddColumn(ContractorFinal4, "BazaarID", each -1, Int64.Type),
				    ContractorFinal6 = Table.AddColumn(ContractorFinal5, "TerritoryName", each null, type text),
				    ContractorFinal7 = Table.AddColumn(ContractorFinal6, "AreaName", each null, type text),
				    ContractorRenamed = Table.RenameColumns(ContractorFinal7, {{"id", "ClientID"}}),
				    ContractorClean = Table.SelectColumns(ContractorRenamed, {
				        "ClientID", "ClientName", "ClientType", "SubType", "ResponsibleRole", "BazaarID", "TerritoryName", "AreaName"
				    }),

				    // ============================================================
				    // 7. HEAD MASONS (Dec 2025) - For project conversion client types
				    // ============================================================
				    HeadMasonsSource = #"public head_masons",
				    HeadMasonsBase = Table.SelectColumns(HeadMasonsSource, {"id"}, MissingField.UseNull),
				    HeadMasonsFinal = Table.AddColumn(HeadMasonsBase, "ClientType", each "HeadMason", type text),
				    HeadMasonsFinal2 = Table.AddColumn(HeadMasonsFinal, "ClientName", each "HeadMason-" & Text.From([id]), type text),
				    HeadMasonsFinal3 = Table.AddColumn(HeadMasonsFinal2, "SubType", each null, type text),
				    HeadMasonsFinal4 = Table.AddColumn(HeadMasonsFinal3, "ResponsibleRole", each "BDO", type text),
				    HeadMasonsFinal5 = Table.AddColumn(HeadMasonsFinal4, "BazaarID", each -1, Int64.Type),
				    HeadMasonsFinal6 = Table.AddColumn(HeadMasonsFinal5, "TerritoryName", each null, type text),
				    HeadMasonsFinal7 = Table.AddColumn(HeadMasonsFinal6, "AreaName", each null, type text),
				    HeadMasonsRenamed = Table.RenameColumns(HeadMasonsFinal7, {{"id", "ClientID"}}),
				    HeadMasonsClean = Table.SelectColumns(HeadMasonsRenamed, {
				        "ClientID", "ClientName", "ClientType", "SubType", "ResponsibleRole", "BazaarID", "TerritoryName", "AreaName"
				    }),

				    // ============================================================
				    // 8. SITE MANAGERS (Dec 2025) - For project conversion client types
				    // ============================================================
				    SiteManagersSource = #"public site_managers",
				    SiteManagersBase = Table.SelectColumns(SiteManagersSource, {"id"}, MissingField.UseNull),
				    SiteManagersFinal = Table.AddColumn(SiteManagersBase, "ClientType", each "SiteManager", type text),
				    SiteManagersFinal2 = Table.AddColumn(SiteManagersFinal, "ClientName", each "SiteManager-" & Text.From([id]), type text),
				    SiteManagersFinal3 = Table.AddColumn(SiteManagersFinal2, "SubType", each null, type text),
				    SiteManagersFinal4 = Table.AddColumn(SiteManagersFinal3, "ResponsibleRole", each "BDO", type text),
				    SiteManagersFinal5 = Table.AddColumn(SiteManagersFinal4, "BazaarID", each -1, Int64.Type),
				    SiteManagersFinal6 = Table.AddColumn(SiteManagersFinal5, "TerritoryName", each null, type text),
				    SiteManagersFinal7 = Table.AddColumn(SiteManagersFinal6, "AreaName", each null, type text),
				    SiteManagersRenamed = Table.RenameColumns(SiteManagersFinal7, {{"id", "ClientID"}}),
				    SiteManagersClean = Table.SelectColumns(SiteManagersRenamed, {
				        "ClientID", "ClientName", "ClientType", "SubType", "ResponsibleRole", "BazaarID", "TerritoryName", "AreaName"
				    }),

				    // ============================================================
				    // 9. UNCOVERED RETAILERS (Dec 2025) - For project conversion client types
				    // ============================================================
				    UncoveredRetailerSource = #"public uncovered_retailer",
				    UncoveredRetailerBase = Table.SelectColumns(UncoveredRetailerSource, {"id"}, MissingField.UseNull),
				    UncoveredRetailerFinal = Table.AddColumn(UncoveredRetailerBase, "ClientType", each "UncoveredRetailer", type text),
				    UncoveredRetailerFinal2 = Table.AddColumn(UncoveredRetailerFinal, "ClientName", each "UncoveredRetailer-" & Text.From([id]), type text),
				    UncoveredRetailerFinal3 = Table.AddColumn(UncoveredRetailerFinal2, "SubType", each null, type text),
				    UncoveredRetailerFinal4 = Table.AddColumn(UncoveredRetailerFinal3, "ResponsibleRole", each "SR", type text),
				    UncoveredRetailerFinal5 = Table.AddColumn(UncoveredRetailerFinal4, "BazaarID", each -1, Int64.Type),
				    UncoveredRetailerFinal6 = Table.AddColumn(UncoveredRetailerFinal5, "TerritoryName", each null, type text),
				    UncoveredRetailerFinal7 = Table.AddColumn(UncoveredRetailerFinal6, "AreaName", each null, type text),
				    UncoveredRetailerRenamed = Table.RenameColumns(UncoveredRetailerFinal7, {{"id", "ClientID"}}),
				    UncoveredRetailerClean = Table.SelectColumns(UncoveredRetailerRenamed, {
				        "ClientID", "ClientName", "ClientType", "SubType", "ResponsibleRole", "BazaarID", "TerritoryName", "AreaName"
				    }),

				    // ============================================================
				    // COMBINE ALL CLIENT TYPES (Dec 2025: Added HeadMason, SiteManager, UncoveredRetailer)
				    // ============================================================
				    AllClients = Table.Combine({
				        SitesClean, 
				        RetailersClean, 
				        IHBClean,
				        DealersClean, 
				        EngineersClean,
				        ContractorClean,
				        HeadMasonsClean,
				        SiteManagersClean,
				        UncoveredRetailerClean
				    }),
				
				    // ============================================================
				    // FINAL PROCESSING
				    // ============================================================
				    
				    // Create Composite Key (ClientType + ClientID) for uniqueness
				    WithCompositeKey = Table.AddColumn(AllClients, "ClientKey", 
				        each [ClientType] & "-" & Text.From([ClientID]), type text),
				    
				    // Add Client Category (Dec 2025: Added HeadMason, SiteManager, UncoveredRetailer)
				    WithCategory = Table.AddColumn(WithCompositeKey, "ClientCategory", each 
				        if [ClientType] = "Site" then "Prospect"
				        else if [ClientType] = "Dealer" or [ClientType] = "Retailer" or [ClientType] = "UncoveredRetailer" then "Channel Partner"
				        else if [ClientType] = "Engineer" then "Influencer-Technical"
				        else if [ClientType] = "Contractor" or [ClientType] = "HeadMason" then "Influencer-Partner"
				        else if [ClientType] = "IHB" then "End Customer"
				        else if [ClientType] = "SiteManager" then "Site Staff"
				        else "Other",
				        type text
				    ),
				    
				    // Add RLS Role (Dec 2025: Added HeadMason, SiteManager, UncoveredRetailer)
				    WithResponsibleRoleRLS = Table.AddColumn(WithCategory, "ResponsibleRoleRLS", each 
				        if [ClientType] = "Site" then "BDO"
				        else if [ClientType] = "Engineer" then "BDO"
				        else if [ClientType] = "Contractor" then "CRO"
				        else if [ClientType] = "Retailer" then "SR"
				        else if [ClientType] = "Dealer" then "CRO"
				        else if [ClientType] = "IHB" then "CRO,BDO"
				        else if [ClientType] = "HeadMason" then "BDO"
				        else if [ClientType] = "SiteManager" then "BDO"
				        else if [ClientType] = "UncoveredRetailer" then "SR"
				        else "All",
				        type text
				    ),
				    
				    // Reorder Columns
				    ReorderedColumns = Table.ReorderColumns(WithResponsibleRoleRLS, {
				        "ClientKey", "ClientID", "ClientName", "ClientType", "SubType", "ClientCategory",
				        "ResponsibleRole", "ResponsibleRoleRLS", "BazaarID", "TerritoryName", "AreaName"
				    }),
				    
				    // Set Data Types
				    TypedTable = Table.TransformColumnTypes(ReorderedColumns, {
				        {"ClientKey", type text},
				        {"ClientID", Int64.Type},
				        {"ClientName", type text},
				        {"ClientType", type text},
				        {"SubType", type text},
				        {"ClientCategory", type text},
				        {"ResponsibleRole", type text},
				        {"ResponsibleRoleRLS", type text},
				        {"BazaarID", Int64.Type},
				        {"TerritoryName", type text},
				        {"AreaName", type text}
				    }),
				  #"Merged queries" = Table.NestedJoin(TypedTable, {"BazaarID"}, Dim_Bazaar, {"BazaarID"}, "Dim_Bazaar", JoinKind.LeftOuter),
				  #"Expanded Dim_Bazaar" = Table.ExpandTableColumn(#"Merged queries", "Dim_Bazaar", {"bd_territory_id", "territory_id"}, {"bd_territory_id", "territory_id"})
				in
				    #"Expanded Dim_Bazaar"
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

