table Dim_Territory
	lineageTag: db5d884b-6597-4180-9777-910caa2361d1

	column zone_id
		dataType: int64
		formatString: 0
		lineageTag: 50f3f619-0a75-4644-a84d-4caf4af7af2a
		summarizeBy: count
		sourceColumn: zone_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column zone_name
		dataType: string
		lineageTag: d75f803f-af45-4365-b68d-b6d9291288f3
		summarizeBy: none
		sourceColumn: zone_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column region_id
		dataType: int64
		formatString: 0
		lineageTag: 9cfefd4e-e5fc-4e89-a996-b3dfd44af963
		summarizeBy: count
		sourceColumn: region_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column region_name
		dataType: string
		lineageTag: f4b7956a-9300-481c-aa24-88c84c0f914b
		summarizeBy: none
		sourceColumn: region_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column area_id
		dataType: int64
		formatString: 0
		lineageTag: 49bf659c-a5e3-49ee-82d8-32f8b3be567a
		summarizeBy: count
		sourceColumn: area_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column area_name
		dataType: string
		lineageTag: cb53eb18-73a4-4264-a85c-3e8250c0437f
		summarizeBy: none
		sourceColumn: area_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column nation_id
		dataType: int64
		formatString: 0
		lineageTag: beb0ebc3-f7b2-47f7-a820-fe4d8c9291b7
		summarizeBy: count
		sourceColumn: nation_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column nation_name
		dataType: string
		lineageTag: a3067a9a-3152-4971-b8bd-869a841f85e3
		summarizeBy: none
		sourceColumn: nation_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column organization_id
		dataType: int64
		formatString: 0
		lineageTag: ded7c21d-31fb-4fb4-80b2-4062e7944276
		summarizeBy: count
		sourceColumn: organization_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column assigned_zsm
		dataType: string
		lineageTag: 64b0d8c7-90d8-4d73-be35-cfd439f2aff2
		summarizeBy: none
		sourceColumn: assigned_zsm

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column assigned_gm
		dataType: string
		lineageTag: 6f2f0bee-e27d-4a82-9473-bc201c4c4f97
		summarizeBy: none
		sourceColumn: assigned_gm

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column assigned_agm
		dataType: string
		lineageTag: c0516678-66a3-48d1-8968-969608fbaae1
		summarizeBy: none
		sourceColumn: assigned_agm

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column assigned_asm
		dataType: string
		lineageTag: 0bbb4e7a-d829-4984-8b70-6d533602c226
		summarizeBy: none
		sourceColumn: assigned_asm

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id
		dataType: int64
		formatString: 0
		lineageTag: territory-id-001
		summarizeBy: count
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: territory-name-001
		summarizeBy: none
		sourceColumn: name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column assigned_sr
		dataType: string
		lineageTag: assigned-sr-001
		summarizeBy: none
		sourceColumn: assigned_sr

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column assigned_bdo
		dataType: string
		lineageTag: assigned-bdo-001
		summarizeBy: none
		sourceColumn: assigned_bdo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column assigned_cro
		dataType: string
		lineageTag: assigned-cro-001
		summarizeBy: none
		sourceColumn: assigned_cro

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column users_id
		dataType: int64
		formatString: 0
		lineageTag: 264dd87b-8e7e-4b31-a249-014aad855b81
		summarizeBy: none
		sourceColumn: users_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column delete_status
		dataType: string
		lineageTag: 6d3a0f5e-ff7e-486e-b200-0188d3ed3210
		summarizeBy: none
		sourceColumn: delete_status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Dim_Territory = m
		mode: import
		source = ```
				// ============================================================
				// Dim_Territory - Geographic Hierarchy Dimension
				// Source: public territory table
				// Full Hierarchy: Zone → Region → Area → Territory
				// ============================================================
				
				let
				    // Reference the existing 'public territory' table in Power BI
				    Source = #"public territory",
				    
				    // ---- Select Core Columns from territory table ----
				    SelectedColumns = Table.SelectColumns(Source, {"id", "area_name", "assigned_agm", "assigned_asm", "assigned_bdo", "assigned_cro", "assigned_gm", "assigned_sr", "assigned_zsm", "delete_status", "name", "nation_name", "region_name", "zone_name", "area_id", "nation_id", "organization_id", "region_id", "zone_id"}),
				    
				    // ---- Filter Active Territories ----
				    ActiveTerritories = Table.SelectRows(SelectedColumns, each [delete_status] = "NO"),
				  #"Merged queries" = Table.NestedJoin(ActiveTerritories, {"id"}, #"public users_territory", {"territory_id"}, "public users_territory", JoinKind.LeftOuter),
				  #"Expanded public users_territory" = Table.ExpandTableColumn(#"Merged queries", "public users_territory", {"users_id"}, {"users_id"})
				in
				    #"Expanded public users_territory"
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

