table Dim_Engineer
	lineageTag: e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b

	/// Total count of engineers in the dimension
	measure Total_Engineers_Count = COUNTROWS('Dim_Engineer')
		formatString: #,##0
		displayFolder: Counts
		lineageTag: f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c

	/// Total pending disbursement amount across all engineers
	measure Total_Engineer_Pending_Disbursement = SUM('Dim_Engineer'[Pending_Disbursement])
		formatString: #,##0.00
		displayFolder: Disbursement
		lineageTag: a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d

	/// Total ready for disbursement amount across all engineers
	measure Total_Engineer_Ready_For_Disbursement = SUM('Dim_Engineer'[Ready_For_Disbursement])
		formatString: #,##0.00
		displayFolder: Disbursement
		lineageTag: b4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e

	/// Pending disbursement MT across all engineers
	measure Total_Engineer_Pending_MT = SUM('Dim_Engineer'[Pending_Disbursement_MT])
		formatString: #,##0.00
		displayFolder: Disbursement
		lineageTag: c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f

	/// Ready for disbursement MT across all engineers
	measure Total_Engineer_Ready_MT = SUM('Dim_Engineer'[Ready_For_Disbursement_MT])
		formatString: #,##0.00
		displayFolder: Disbursement
		lineageTag: d6e7f8a9-b0c1-4d2e-3f4a-5b6c7d8e9f0a

	/// Engineers with pending orders
	measure Engineers_With_Pending = 
			CALCULATE(
				COUNTROWS('Dim_Engineer'),
				FILTER('Dim_Engineer', 'Dim_Engineer'[Pending_Order_Count] > 0)
			)
		formatString: #,##0
		displayFolder: Counts
		lineageTag: e7f8a9b0-c1d2-4e3f-4a5b-6c7d8e9f0a1b

	/// Engineers with ready orders
	measure Engineers_With_Ready = 
			CALCULATE(
				COUNTROWS('Dim_Engineer'),
				FILTER('Dim_Engineer', 'Dim_Engineer'[Ready_Order_Count] > 0)
			)
		formatString: #,##0
		displayFolder: Counts
		lineageTag: f8a9b0c1-d2e3-4f4a-5b6c-7d8e9f0a1b2c

	column EngineerID
		dataType: int64
		formatString: 0
		lineageTag: a9b0c1d2-e3f4-4a5b-6c7d-8e9f0a1b2c3d
		summarizeBy: none
		sourceColumn: EngineerID

		annotation SummarizationSetBy = Automatic

	column ClientID
		dataType: int64
		formatString: 0
		lineageTag: b0c1d2e3-f4a5-4b6c-7d8e-9f0a1b2c3d4e
		summarizeBy: none
		sourceColumn: ClientID

		annotation SummarizationSetBy = Automatic

	column EngineerName
		dataType: string
		lineageTag: c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f
		summarizeBy: none
		sourceColumn: EngineerName

		annotation SummarizationSetBy = Automatic

	column EngineerPhone
		dataType: string
		lineageTag: d2e3f4a5-b6c7-4d8e-9f0a-1b2c3d4e5f6a
		summarizeBy: none
		sourceColumn: EngineerPhone

		annotation SummarizationSetBy = Automatic

	column BkashNumber
		dataType: string
		lineageTag: e3f4a5b6-c7d8-4e9f-0a1b-2c3d4e5f6a7b
		summarizeBy: none
		sourceColumn: BkashNumber

		annotation SummarizationSetBy = Automatic

	column BankAccountID
		dataType: int64
		formatString: 0
		lineageTag: f4a5b6c7-d8e9-4f0a-1b2c-3d4e5f6a7b8c
		summarizeBy: none
		sourceColumn: BankAccountID

		annotation SummarizationSetBy = Automatic

	column BankName
		dataType: string
		lineageTag: a5b6c7d8-e9f0-4a1b-2c3d-4e5f6a7b8c9d
		summarizeBy: none
		sourceColumn: BankName

		annotation SummarizationSetBy = Automatic

	column RoutingNumber
		dataType: string
		lineageTag: b6c7d8e9-f0a1-4b2c-3d4e-5f6a7b8c9d0e
		summarizeBy: none
		sourceColumn: RoutingNumber

		annotation SummarizationSetBy = Automatic

	column ACNumber
		dataType: string
		lineageTag: c7d8e9f0-a1b2-4c3d-4e5f-6a7b8c9d0e1f
		summarizeBy: none
		sourceColumn: ACNumber

		annotation SummarizationSetBy = Automatic

	column Address
		dataType: string
		lineageTag: d8e9f0a1-b2c3-4d4e-5f6a-7b8c9d0e1f2a
		summarizeBy: none
		sourceColumn: Address

		annotation SummarizationSetBy = Automatic

	column SecondaryAddress
		dataType: string
		lineageTag: e9f0a1b2-c3d4-4e5f-6a7b-8c9d0e1f2a3b
		summarizeBy: none
		sourceColumn: SecondaryAddress

		annotation SummarizationSetBy = Automatic

	column UpazillaID
		dataType: int64
		formatString: 0
		lineageTag: f0a1b2c3-d4e5-4f6a-7b8c-9d0e1f2a3b4c
		summarizeBy: none
		sourceColumn: UpazillaID

		annotation SummarizationSetBy = Automatic

	column EngineerType
		dataType: string
		lineageTag: a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d
		summarizeBy: none
		sourceColumn: EngineerType

		annotation SummarizationSetBy = Automatic

	column ConsultancyFirm
		dataType: string
		lineageTag: b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e
		summarizeBy: none
		sourceColumn: ConsultancyFirm

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Notes
		dataType: string
		lineageTag: d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	column Photo
		dataType: string
		lineageTag: e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b
		summarizeBy: none
		sourceColumn: Photo

		annotation SummarizationSetBy = Automatic

	column CreatedAt
		dataType: dateTime
		formatString: General Date
		lineageTag: f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c
		summarizeBy: none
		sourceColumn: CreatedAt

		annotation SummarizationSetBy = Automatic

	column UpdatedAt
		dataType: dateTime
		formatString: General Date
		lineageTag: a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d
		summarizeBy: none
		sourceColumn: UpdatedAt

		annotation SummarizationSetBy = Automatic

	column CreatedByID
		dataType: int64
		formatString: 0
		lineageTag: b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e
		summarizeBy: none
		sourceColumn: CreatedByID

		annotation SummarizationSetBy = Automatic

	column Pending_Disbursement
		dataType: double
		lineageTag: c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f
		summarizeBy: sum
		sourceColumn: Pending_Disbursement

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ready_For_Disbursement
		dataType: double
		lineageTag: d0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a
		summarizeBy: sum
		sourceColumn: Ready_For_Disbursement

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Pending_Disbursement_MT
		dataType: double
		lineageTag: e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b
		summarizeBy: sum
		sourceColumn: Pending_Disbursement_MT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ready_For_Disbursement_MT
		dataType: double
		lineageTag: f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c
		summarizeBy: sum
		sourceColumn: Ready_For_Disbursement_MT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Pending_Order_Count
		dataType: int64
		formatString: 0
		lineageTag: a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d
		summarizeBy: sum
		sourceColumn: Pending_Order_Count

		annotation SummarizationSetBy = Automatic

	column Ready_Order_Count
		dataType: int64
		formatString: 0
		lineageTag: b4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e
		summarizeBy: sum
		sourceColumn: Ready_Order_Count

		annotation SummarizationSetBy = Automatic

	column EngineerKey
		dataType: string
		lineageTag: c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f
		summarizeBy: none
		sourceColumn: EngineerKey

		annotation SummarizationSetBy = Automatic

	partition Dim_Engineer = m
		mode: import
		source = ```
				// ============================================================
				// Dim_Engineer - Engineer Dimension Table
				// 
				// PURPOSE:
				// Provides engineer dimension with details from public.client
				// and aggregated order disbursement metrics from user_orders.
				// 
				// DATA SOURCES:
				// - public.engineers: Engineer IDs and type
				// - public.client: Client details (where client_type = 'ENGINEER')
				// - public.user_orders: Disbursement status (is_engineer_eligible, order_status)
				// - public.potential_site: Links site_id to engineer_id
				// 
				// KEY COLUMNS:
				// - EngineerID: ID from public.engineers table
				// - ClientID: ID from public.client table (for lookup)
				// - Pending_Disbursement: Amount for PENDING/PENDING_SR_VERIFICATION orders
				// - Ready_For_Disbursement: Amount for APPROVED orders
				// 
				// DISBURSEMENT LOGIC (from user_orders):
				// - is_engineer_eligible = TRUE → Engineer is eligible for disbursement
				// - order_status = PENDING/PENDING_SR_VERIFICATION → Pending Disbursement
				// - order_status = APPROVED → Ready for Disbursement
				// ============================================================
				
				let
				    // ============================================================
				    // STEP 1: Load engineer IDs and details from public.engineers
				    // ============================================================
				    EngineerSource = #"public engineers",
				    EngineerSelected = Table.SelectColumns(EngineerSource, {
				        "id", "engineer_type", "consultancy_firm"
				    }, MissingField.UseNull),
				    EngineerRenamed = Table.RenameColumns(EngineerSelected, {
				        {"id", "EngineerID"},
				        {"engineer_type", "EngineerType"},
				        {"consultancy_firm", "ConsultancyFirm"}
				    }),
				    
				    // ============================================================
				    // STEP 2: Load client details from public.client
				    // Filter to only ENGINEER type clients
				    // ============================================================
				    ClientSource = #"public client",
				    
				    // Select relevant columns from public.client
				    ClientSelected = Table.SelectColumns(ClientSource, {
				        "id", "client_type", "name", "phone", "bkash_number", 
				        "bank_account_id", "bank_name", "routing_number", "ac_number",
				        "address", "secondary_address", "upazilla_id",
				        "status", "notes", "photo",
				        "created_at", "updated_at", "created_by_id", "is_deleted"
				    }, MissingField.UseNull),
				    
				    // Filter to ENGINEER type only
				    ClientEngineers = Table.SelectRows(ClientSelected, each 
				        Text.Upper(Text.From([client_type])) = "ENGINEER"
				    ),
				    
				    // Filter out deleted records
				    ClientActive = Table.SelectRows(ClientEngineers, each
				        let
				            del = if [is_deleted] = null then "NO" else try Text.Upper(Text.From([is_deleted])) otherwise "NO"
				        in
				            del = "NO" or del = "N" or del = "0" or del = "FALSE"
				    ),
				    
				    // Rename client columns
				    ClientRenamed = Table.RenameColumns(ClientActive, {
				        {"id", "ClientID"},
				        {"name", "EngineerName"},
				        {"phone", "EngineerPhone"},
				        {"bkash_number", "BkashNumber"},
				        {"bank_account_id", "BankAccountID"},
				        {"bank_name", "BankName"},
				        {"routing_number", "RoutingNumber"},
				        {"ac_number", "ACNumber"},
				        {"address", "Address"},
				        {"secondary_address", "SecondaryAddress"},
				        {"upazilla_id", "UpazillaID"},
				        {"status", "Status"},
				        {"notes", "Notes"},
				        {"photo", "Photo"},
				        {"created_at", "CreatedAt"},
				        {"updated_at", "UpdatedAt"},
				        {"created_by_id", "CreatedByID"}
				    }, MissingField.Ignore),
				    
				    // Remove temporary columns
				    ClientClean = Table.RemoveColumns(ClientRenamed, {"client_type", "is_deleted"}, MissingField.Ignore),
				    
				    // ============================================================
				    // STEP 3: Join engineer IDs with client details
				    // ============================================================
				    JoinedEngineers = Table.NestedJoin(
				        EngineerRenamed,
				        {"EngineerID"},
				        ClientClean,
				        {"ClientID"},
				        "ClientDetails",
				        JoinKind.LeftOuter
				    ),
				    
				    ExpandedEngineers = Table.ExpandTableColumn(
				        JoinedEngineers,
				        "ClientDetails",
				        {"ClientID", "EngineerName", "EngineerPhone", "BkashNumber", 
				         "BankAccountID", "BankName", "RoutingNumber", "ACNumber",
				         "Address", "SecondaryAddress", "UpazillaID",
				         "Status", "Notes", "Photo", "CreatedAt", "UpdatedAt", "CreatedByID"},
				        {"ClientID", "EngineerName", "EngineerPhone", "BkashNumber", 
				         "BankAccountID", "BankName", "RoutingNumber", "ACNumber",
				         "Address", "SecondaryAddress", "UpazillaID",
				         "Status", "Notes", "Photo", "CreatedAt", "UpdatedAt", "CreatedByID"}
				    ),
				    
				    // ============================================================
				    // STEP 4: Load user_orders for disbursement calculations
				    // This is the source of truth for disbursement status
				    // ============================================================
				    UserOrdersSource = #"public user_orders",
				    
				    // Get potential_site to find engineer_id linkage via site_id
				    PotentialSiteSource = #"public potential_site",
				    PotentialSiteCols = Table.ColumnNames(PotentialSiteSource),
				    
				    // Select site_id and engineer_id from potential_site
				    PotentialSiteSelected = if List.Contains(PotentialSiteCols, "engineer_id") then
				        Table.SelectColumns(PotentialSiteSource, {"id", "engineer_id"}, MissingField.UseNull)
				    else
				        Table.AddColumn(Table.SelectColumns(PotentialSiteSource, {"id"}), "engineer_id", each null, Int64.Type),
				    
				    PotentialSiteRenamed = Table.RenameColumns(PotentialSiteSelected, {
				        {"id", "site_id"},
				        {"engineer_id", "ps_engineer_id"}
				    }),
				    
				    // Select relevant columns from user_orders
				    UserOrdersSelected = Table.SelectColumns(UserOrdersSource, {
				        "id", "order_status", "site_id", "total_amount", "is_engineer_eligible"
				    }, MissingField.UseNull),
				    
				    // Filter to engineer-eligible orders only (is_engineer_eligible = TRUE)
				    UserOrdersEngineerEligible = Table.SelectRows(UserOrdersSelected, each
				        [is_engineer_eligible] = true or [is_engineer_eligible] = 1
				    ),
				    
				    // Join with potential_site to get engineer_id
				    UserOrdersWithEngineer = Table.NestedJoin(
				        UserOrdersEngineerEligible,
				        {"site_id"},
				        PotentialSiteRenamed,
				        {"site_id"},
				        "PotentialSite",
				        JoinKind.LeftOuter
				    ),
				    
				    UserOrdersExpanded = Table.ExpandTableColumn(
				        UserOrdersWithEngineer,
				        "PotentialSite",
				        {"ps_engineer_id"},
				        {"engineer_id"}
				    ),
				    
				    // Filter to orders with an engineer linked via site
				    UserOrdersWithEngineerOnly = Table.SelectRows(UserOrdersExpanded, each [engineer_id] <> null),
				    
				    // Add disbursement status classification based on user_orders.order_status
				    // PENDING, PENDING_SR_VERIFICATION = "Pending"
				    // APPROVED = "Ready"
				    UserOrdersWithStatus = Table.AddColumn(UserOrdersWithEngineerOnly, "DisbursementGroup", each
				        let
				            status = if [order_status] = null then "" else Text.Upper(Text.From([order_status]))
				        in
				            if status = "PENDING" or status = "PENDING_SR_VERIFICATION" then "Pending"
				            else if status = "APPROVED" then "Ready"
				            else "Other",
				        type text
				    ),
				    
				    // Convert total_amount to number
				    UserOrdersWithAmount = Table.AddColumn(UserOrdersWithStatus, "amount", each
				        try Number.From([total_amount]) otherwise 0,
				        type number
				    ),
				    
				    // ============================================================
				    // STEP 5: Get order_items for MT calculation
				    // ============================================================
				    OrderItemsSource = #"public order_items",
				    SKUSource = #"public sku_data",
				    
				    // Get org_id from SKU for MT conversion
				    SKUWithOrg = Table.SelectColumns(SKUSource, {"id", "org_id"}, MissingField.UseNull),
				    
				    OrderItemsSelected = Table.SelectColumns(OrderItemsSource, {
				        "user_order_history_id", "qty", "sku_info_id"
				    }, MissingField.UseNull),
				    
				    // Join with SKU to get org_id
				    OrderItemsWithSKU = Table.NestedJoin(
				        OrderItemsSelected,
				        {"sku_info_id"},
				        SKUWithOrg,
				        {"id"},
				        "SKU",
				        JoinKind.LeftOuter
				    ),
				    
				    OrderItemsExpanded = Table.ExpandTableColumn(OrderItemsWithSKU, "SKU", {"org_id"}, {"org_id"}),
				    
				    // Calculate MT (ACL = qty/20, others = qty as-is)
				    OrderItemsWithMT = Table.AddColumn(OrderItemsExpanded, "qty_in_mt", each
				        let
				            q = if [qty] = null then 0 else try Number.From([qty]) otherwise 0
				        in
				            if [org_id] = 1 then q / 20 else q,
				        type number
				    ),
				    
				    // Aggregate by user_order_history_id
				    OrderItemsAgg = Table.Group(
				        OrderItemsWithMT,
				        {"user_order_history_id"},
				        {
				            {"total_qty_mt", each List.Sum([qty_in_mt]), type number}
				        }
				    ),
				    
				    // Join MT with user_orders
				    UserOrdersWithMT = Table.NestedJoin(
				        UserOrdersWithAmount,
				        {"id"},
				        OrderItemsAgg,
				        {"user_order_history_id"},
				        "ItemsAgg",
				        JoinKind.LeftOuter
				    ),
				    
				    UserOrdersExpandedMT = Table.ExpandTableColumn(UserOrdersWithMT, "ItemsAgg", {"total_qty_mt"}, {"qty_in_mt"}),
				    
				    // Fill nulls
				    UserOrdersFilled = Table.ReplaceValue(UserOrdersExpandedMT, null, 0, Replacer.ReplaceValue, {"qty_in_mt", "amount"}),
				    
				    // ============================================================
				    // STEP 6: Aggregate disbursement by engineer
				    // ============================================================
				    
				    // Pending disbursement (PENDING or PENDING_SR_VERIFICATION)
				    PendingOrders = Table.SelectRows(UserOrdersFilled, each [DisbursementGroup] = "Pending"),
				    PendingAgg = Table.Group(
				        PendingOrders,
				        {"engineer_id"},
				        {
				            {"Pending_Disbursement", each List.Sum([amount]), type number},
				            {"Pending_Disbursement_MT", each List.Sum([qty_in_mt]), type number},
				            {"Pending_Order_Count", each Table.RowCount(_), Int64.Type}
				        }
				    ),
				    PendingRenamed = Table.RenameColumns(PendingAgg, {{"engineer_id", "EngineerID_Pending"}}),
				    
				    // Ready for disbursement (APPROVED)
				    ReadyOrders = Table.SelectRows(UserOrdersFilled, each [DisbursementGroup] = "Ready"),
				    ReadyAgg = Table.Group(
				        ReadyOrders,
				        {"engineer_id"},
				        {
				            {"Ready_For_Disbursement", each List.Sum([amount]), type number},
				            {"Ready_For_Disbursement_MT", each List.Sum([qty_in_mt]), type number},
				            {"Ready_Order_Count", each Table.RowCount(_), Int64.Type}
				        }
				    ),
				    ReadyRenamed = Table.RenameColumns(ReadyAgg, {{"engineer_id", "EngineerID_Ready"}}),
				    
				    // ============================================================
				    // STEP 7: Join disbursement aggregates with engineer dimension
				    // ============================================================
				    
				    // Join pending disbursement
				    WithPending = Table.NestedJoin(
				        ExpandedEngineers,
				        {"EngineerID"},
				        PendingRenamed,
				        {"EngineerID_Pending"},
				        "PendingData",
				        JoinKind.LeftOuter
				    ),
				    
				    ExpandedPending = Table.ExpandTableColumn(
				        WithPending,
				        "PendingData",
				        {"Pending_Disbursement", "Pending_Disbursement_MT", "Pending_Order_Count"},
				        {"Pending_Disbursement", "Pending_Disbursement_MT", "Pending_Order_Count"}
				    ),
				    
				    // Join ready for disbursement
				    WithReady = Table.NestedJoin(
				        ExpandedPending,
				        {"EngineerID"},
				        ReadyRenamed,
				        {"EngineerID_Ready"},
				        "ReadyData",
				        JoinKind.LeftOuter
				    ),
				    
				    ExpandedReady = Table.ExpandTableColumn(
				        WithReady,
				        "ReadyData",
				        {"Ready_For_Disbursement", "Ready_For_Disbursement_MT", "Ready_Order_Count"},
				        {"Ready_For_Disbursement", "Ready_For_Disbursement_MT", "Ready_Order_Count"}
				    ),
				    
				    // ============================================================
				    // STEP 8: Fill nulls and add EngineerKey
				    // ============================================================
				    FilledNulls = Table.ReplaceValue(
				        ExpandedReady, 
				        null, 
				        0, 
				        Replacer.ReplaceValue, 
				        {"Pending_Disbursement", "Pending_Disbursement_MT", "Pending_Order_Count",
				         "Ready_For_Disbursement", "Ready_For_Disbursement_MT", "Ready_Order_Count"}
				    ),
				    
				    // Add EngineerKey for joining with Fact tables
				    WithEngineerKey = Table.AddColumn(FilledNulls, "EngineerKey", each 
				        "Engineer-" & Text.From([EngineerID]),
				        type text
				    ),
				    
				    // ============================================================
				    // STEP 9: Set data types
				    // ============================================================
				    TypedTable = Table.TransformColumnTypes(WithEngineerKey, {
				        {"EngineerID", Int64.Type},
				        {"ClientID", Int64.Type},
				        {"EngineerName", type text},
				        {"EngineerPhone", type text},
				        {"BkashNumber", type text},
				        {"BankAccountID", Int64.Type},
				        {"BankName", type text},
				        {"RoutingNumber", type text},
				        {"ACNumber", type text},
				        {"Address", type text},
				        {"SecondaryAddress", type text},
				        {"UpazillaID", Int64.Type},
				        {"EngineerType", type text},
				        {"ConsultancyFirm", type text},
				        {"Status", type text},
				        {"Notes", type text},
				        {"Photo", type text},
				        {"CreatedAt", type datetime},
				        {"UpdatedAt", type datetime},
				        {"CreatedByID", Int64.Type},
				        {"Pending_Disbursement", type number},
				        {"Ready_For_Disbursement", type number},
				        {"Pending_Disbursement_MT", type number},
				        {"Ready_For_Disbursement_MT", type number},
				        {"Pending_Order_Count", Int64.Type},
				        {"Ready_Order_Count", Int64.Type},
				        {"EngineerKey", type text}
			    })
			in
			    TypedTable
				```

	annotation PBI_ResultType = Table