table Dim_BDTerritory
	lineageTag: 8a9b0c1d-2e3f-4567-89ab-cdef01234567

	column BDTerritoryID
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 9b0c1d2e-3f4a-5678-9abc-def012345678
		summarizeBy: none
		sourceColumn: BDTerritoryID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BDTerritoryName
		dataType: string
		lineageTag: 0c1d2e3f-4a5b-6789-abcd-ef0123456789
		summarizeBy: none
		sourceColumn: BDTerritoryName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DistrictID
		dataType: int64
		formatString: 0
		lineageTag: 1d2e3f4a-5b6c-789a-bcde-f01234567890
		summarizeBy: count
		sourceColumn: DistrictID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UpazillaID
		dataType: int64
		formatString: 0
		lineageTag: 3f4a5b6c-7d8e-9abc-def0-123456789012
		summarizeBy: count
		sourceColumn: UpazillaID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column delete_status
		dataType: string
		lineageTag: 5b6c7d8e-9f0a-bcde-f012-345678901234
		summarizeBy: none
		sourceColumn: delete_status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 6c7d8e9f-0a1b-cdef-0123-456789012345
		summarizeBy: none
		sourceColumn: created_at

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 7d8e9f0a-1b2c-def0-1234-567890123456
		summarizeBy: none
		sourceColumn: updated_at

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column users_id
		dataType: int64
		formatString: 0
		lineageTag: 798ffaa5-4cf3-4c73-b3b6-9c3b4f02523b
		summarizeBy: none
		sourceColumn: users_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Dim_BDTerritory = m
		mode: import
		source = ```
				// ============================================================
								// Dim_BDTerritory - Business Development Territory Dimension
								// Source: public bd_territory
								// 
								// PURPOSE:
								// Dimension for BMD track (BDO/CRO/BD Incharge) territory filtering
								// BD Territory links to Bazaars which bridges to ORG Territory
								// 
								// HIERARCHY:
								// District → Upazilla → BD Territory
								// ============================================================
								
								let
								    // Reference the existing tables
								    BDTerritorySource = #"public bd_territory",
								    
								    // ---- Select Core Columns from bd_territory ----
								    SelectedColumns = Table.SelectColumns(BDTerritorySource, {
								        "id", "bd_territory_name", "district_id", "upazilla_id",
								        "delete_status", "created_at", "updated_at"
								    }),
					  // Buffer to prevent gateway/PostgreSQL folding issues during join
					  UsersBDTerritoryBridgeBuffered = Table.Buffer(#"public users_bd_territory"),
					  #"Merged queries" = Table.NestedJoin(SelectedColumns, {"id"}, UsersBDTerritoryBridgeBuffered, {"bd_territory_id"}, "public users_bd_territory", JoinKind.LeftOuter),
				  #"Expanded public users_bd_territory" = Table.ExpandTableColumn(#"Merged queries", "public users_bd_territory", {"users_id"}, {"users_id"}),
								    
								    // ---- Filter Active BD Territories ----
								    ActiveTerritories = Table.SelectRows(#"Expanded public users_bd_territory", each [delete_status] = "NO"),				    // ---- Rename Columns ----
								    RenamedColumns = Table.RenameColumns(ActiveTerritories, {
								        {"id", "BDTerritoryID"},
								        {"bd_territory_name", "BDTerritoryName"},
								        {"district_id", "DistrictID"},
								        {"upazilla_id", "UpazillaID"}
								    }),
				  #"Removed duplicates" = Table.Distinct(RenamedColumns, {"BDTerritoryID"})
								in
								    #"Removed duplicates"
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

