table Dim_Territory
	lineageTag: db5d884b-6597-4180-9777-910caa2361d1

	column users_id
		dataType: int64
		formatString: 0
		lineageTag: 264dd87b-8e7e-4b31-a249-014aad855b81
		summarizeBy: none
		sourceColumn: users_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column territory_id
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 3b5a100f-e280-4775-b6a6-532e4c3efa48
		summarizeBy: none
		sourceColumn: territory_id

		annotation SummarizationSetBy = Automatic

	column mainOrganizationName
		dataType: string
		lineageTag: 7838605c-0969-4d3a-a212-509f26e98286
		summarizeBy: none
		sourceColumn: mainOrganizationName

		annotation SummarizationSetBy = Automatic

	column mainZoneName
		dataType: string
		lineageTag: 5c863bb5-004b-4c81-8ef6-5e5796669de5
		summarizeBy: none
		sourceColumn: mainZoneName

		annotation SummarizationSetBy = Automatic

	column mainRegionName
		dataType: string
		lineageTag: 256a9515-8ad9-44cf-9f65-be9af2ea6532
		summarizeBy: none
		sourceColumn: mainRegionName

		annotation SummarizationSetBy = Automatic

	column mainTerritoryName
		dataType: string
		lineageTag: 52fab69a-180f-475c-b8f7-3f29368410ef
		summarizeBy: none
		sourceColumn: mainTerritoryName

		annotation SummarizationSetBy = Automatic

	column AreaName
		dataType: string
		lineageTag: f883ff80-8aaa-4e87-a1ef-4fc841abfe73
		summarizeBy: none
		sourceColumn: AreaName

		annotation SummarizationSetBy = Automatic

	partition Dim_Territory = m
		mode: import
		source = ```
				// ============================================================
				// Dim_Territory - Geographic Hierarchy Dimension
				// Source: public territory table
				// Full Hierarchy: Zone → Region → Area → Territory
				// ============================================================
				
				let
				    // Reference the existing 'public territory' table in Power BI
				    Source = #"public territory",
				    
				    // ---- Select Core Columns from territory table ----
				    SelectedColumns = Table.SelectColumns(Source, {"id", "area_name", "assigned_agm", "assigned_asm", "assigned_bdo", "assigned_cro", "assigned_gm", "assigned_sr", "assigned_zsm", "delete_status", "name", "nation_name", "region_name", "zone_name", "area_id", "nation_id", "organization_id", "region_id", "zone_id"}),
				    
				    // ---- Filter Active Territories ----
				    ActiveTerritories = Table.SelectRows(SelectedColumns, each [delete_status] = "NO"),
				    // Buffer to prevent gateway/PostgreSQL folding issues during join
				    UsersTerritoryBridgeBuffered = Table.Buffer(#"public users_territory"),
				  #"Merged queries 1" = Table.NestedJoin(UsersTerritoryBridgeBuffered, {"users_id"}, Dim_User, {"UserID"}, "Dim_User", JoinKind.LeftOuter),
				  #"Expanded Dim_User 1" = Table.ExpandTableColumn(#"Merged queries 1", "Dim_User", {"OrganizationName", "ZoneName", "RegionName", "TerritoryName", "AreaName"}, {"OrganizationName", "ZoneName", "RegionName", "TerritoryName", "AreaName"}),
				  #"Renamed columns" = Table.RenameColumns(#"Expanded Dim_User 1", {{"OrganizationName", "mainOrganizationName"}, {"ZoneName", "mainZoneName"}, {"RegionName", "mainRegionName"}, {"TerritoryName", "mainTerritoryName"}})
				in
				    #"Renamed columns"
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

