table Dim_Bazaar
	lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567890

	column BazaarID
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 2b3c4d5e-6f7a-8901-bcde-f12345678901
		summarizeBy: none
		sourceColumn: BazaarID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BazaarName
		dataType: string
		lineageTag: 3c4d5e6f-7a8b-9012-cdef-012345678902
		summarizeBy: none
		sourceColumn: BazaarName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BazaarType
		dataType: string
		lineageTag: 4d5e6f7a-8b9c-0123-def0-123456789012
		summarizeBy: none
		sourceColumn: BazaarType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column bd_territory_id
		dataType: int64
		formatString: 0
		lineageTag: 5557fdcf-e63c-4aac-a60b-ef01c65f366b
		summarizeBy: none
		sourceColumn: bd_territory_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column territory_id
		dataType: int64
		formatString: 0
		lineageTag: 785bb0fc-70a2-4b5e-9569-81cc2d4ec977
		summarizeBy: none
		sourceColumn: territory_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column district_id
		dataType: int64
		formatString: 0
		lineageTag: 13c316b2-e10f-49b8-91bd-6480d365becc
		summarizeBy: sum
		sourceColumn: district_id

		annotation SummarizationSetBy = Automatic

	column upazilla_id
		dataType: int64
		formatString: 0
		lineageTag: da82ef6d-983c-4782-92e0-2661583cb1fb
		summarizeBy: sum
		sourceColumn: upazilla_id

		annotation SummarizationSetBy = Automatic

	partition Dim_Bazaar = m
		mode: import
		source = ```
				let
				    // Get unique bazaars from public bazaars table
				    BazaarsSource = #"public bazaars",
				    
				    // Select key columns
				    SelectedColumns = Table.SelectColumns(BazaarsSource, {"id", "bazaar_name", "district_id", "upazilla_id"}),
				    
				    // Rename columns
				    RenamedColumns = Table.RenameColumns(SelectedColumns, {
				        {"id", "BazaarID"},
				        {"bazaar_name", "BazaarName"}
				    }),
				    
				    // Add BazaarType column
				    WithBazaarType = Table.AddColumn(RenamedColumns, "BazaarType", each "Local", type text),
				    
				    // Create National row for Dealers/Engineers/Contractors (BazaarID = -1)
				    NationalRow = #table(
				        type table [BazaarID = Int64.Type, BazaarName = text, BazaarType = text],
				        {{-1, "National", "National"}}
				    ),
				    
				    // Combine with National row
				    CombinedTable = Table.Combine({WithBazaarType, NationalRow}),
				    
				    // Set data types
				    TypedTable = Table.TransformColumnTypes(CombinedTable, {
				        {"BazaarID", Int64.Type},
				        {"BazaarName", type text},
				        {"BazaarType", type text}
				    }),
				    // Buffer to prevent gateway/PostgreSQL folding issues during joins
				    BDTerritoryBazaarsBuffered = Table.Buffer(#"public bd_territory_bazaars"),
				    TerritoryBazaarListBuffered = Table.Buffer(#"public territory_bazaar_list"),
				  #"Merged queries" = Table.NestedJoin(TypedTable, {"BazaarID"}, BDTerritoryBazaarsBuffered, {"bazaar_id"}, "public bd_territory_bazaars", JoinKind.LeftOuter),
				  #"Expanded public bd_territory_bazaars" = Table.ExpandTableColumn(#"Merged queries", "public bd_territory_bazaars", {"bd_territory_id"}, {"bd_territory_id"}),
				  #"Merged queries 1" = Table.NestedJoin(#"Expanded public bd_territory_bazaars", {"BazaarID"}, TerritoryBazaarListBuffered, {"bazaar_list_id"}, "public territory_bazaar_list", JoinKind.LeftOuter),
				  #"Expanded public territory_bazaar_list" = Table.ExpandTableColumn(#"Merged queries 1", "public territory_bazaar_list", {"territory_id"}, {"territory_id"}),
				  #"Removed duplicates" = Table.Distinct(#"Expanded public territory_bazaar_list", {"BazaarID"})
				in
				    #"Removed duplicates"
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

