table Dim_VisitStage
	lineageTag: 305ad795-8085-498c-9bd3-cab16b6a808a

	column VisitStageID
		dataType: int64
		formatString: 0
		lineageTag: ff087162-638b-4f1d-8fdf-c03f459a0db2
		summarizeBy: count
		sourceColumn: VisitStageID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StageName
		dataType: string
		lineageTag: 8d8fda56-1ae0-457a-a0ab-8d6b7c6c6b03
		summarizeBy: none
		sourceColumn: StageName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StageDescription
		dataType: string
		lineageTag: 1d3d1370-0c84-48fb-a3a4-1ddfda38148d
		summarizeBy: none
		sourceColumn: StageDescription

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column VisitPhaseID
		dataType: int64
		formatString: 0
		lineageTag: ae43d420-8cfd-401b-a70b-c490e5e2de59
		summarizeBy: none
		sourceColumn: VisitPhaseID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ParentStageID
		dataType: int64
		formatString: 0
		lineageTag: 277d3d83-1ae0-4ab0-aee1-1dbd06f3370b
		summarizeBy: count
		sourceColumn: ParentStageID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StageSortOrder
		dataType: int64
		formatString: 0
		lineageTag: d57fd9a1-09b1-4c74-82b1-3e132fbb3168
		summarizeBy: sum
		sourceColumn: StageSortOrder

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StageCategory
		dataType: string
		lineageTag: ce348c7b-d974-4787-9b70-db772b971585
		summarizeBy: none
		sourceColumn: StageCategory

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsSubStage
		dataType: int64
		formatString: 0
		lineageTag: 98cd1407-24f6-4c40-8e31-1c0440f48996
		summarizeBy: sum
		sourceColumn: IsSubStage

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Dim_VisitStage = m
		mode: import
		source = ```
				// ============================================================
				// Dim_VisitStage - Visit Stage Dimension
				// Source: public visit_stages (78 records)
				// 
				// PURPOSE:
				// Detailed stages within each visit phase
				// Links to Dim_VisitPhase for hierarchical stage analysis
				// Supports visit workflow tracking and progression analysis
				//
				// ACTUAL COLUMNS: id, name, description, visit_phase_id, parent_id, 
				//                 delete_status, created_at, updated_at
				// ============================================================
				
				let
				    // Reference the existing 'public visit_stages' table in Power BI
				    Source = #"public visit_stages",
				    
				    // ---- Filter Active Stages ----
				    ActiveStages = Table.SelectRows(Source, each [delete_status] = "NO" or [delete_status] = null),
				    
				    // ---- Select Columns ----
				    SelectedColumns = Table.SelectColumns(ActiveStages, {"id", "name", "description", "visit_phase_id", "parent_id"}),
				    
				    // ---- Rename Columns ----
				    RenamedColumns = Table.RenameColumns(SelectedColumns, {
				        {"id", "VisitStageID"},
				        {"name", "StageName"},
				        {"description", "StageDescription"},
				        {"visit_phase_id", "VisitPhaseID"},
				        {"parent_id", "ParentStageID"}
				    }),
				    
				    // ---- Add Sort Order ----
				    WithSortOrder = Table.AddColumn(RenamedColumns, "StageSortOrder", each [VisitStageID], Int64.Type),
				    
				    // ---- Stage Category Grouping (based on construction stage patterns) ----
				    WithStageCategory = Table.AddColumn(WithSortOrder, "StageCategory", each 
				        let stageLower = Text.Lower([StageName])
				        in
				            if Text.Contains(stageLower, "formwork") then "Formwork"
				            else if Text.Contains(stageLower, "reinforcement") then "Reinforcement"
				            else if Text.Contains(stageLower, "concreting") or Text.Contains(stageLower, "casting") then "Concreting"
				            else if Text.Contains(stageLower, "curing") then "Curing"
				            else if Text.Contains(stageLower, "brick") or Text.Contains(stageLower, "masonry") then "Masonry"
				            else if Text.Contains(stageLower, "plaster") then "Plastering"
				            else if Text.Contains(stageLower, "finish") then "Finishing"
				            else "General",
				        type text
				    ),
				    
				    // ---- Is Sub-Stage Flag (has parent) ----
				    WithSubStageFlag = Table.AddColumn(WithStageCategory, "IsSubStage", each 
				        if [ParentStageID] <> null then 1 else 0,
				        Int64.Type
				    ),
				    
				    // ---- Set Data Types ----
				    TypedTable = Table.TransformColumnTypes(WithSubStageFlag, {
				        {"VisitStageID", Int64.Type},
				        {"StageName", type text},
				        {"StageDescription", type text},
				        {"VisitPhaseID", Int64.Type},
				        {"ParentStageID", Int64.Type},
				        {"StageSortOrder", Int64.Type},
				        {"StageCategory", type text},
				        {"IsSubStage", Int64.Type}
				    })
				in
				    TypedTable
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

