table Fact_Target
	lineageTag: fact-target-001

	partition Fact_Target = calculated
		mode: import
		source = ```
			VAR MinDate = MIN(Fact_Visit[DateKey])
			VAR MaxDate = MAX(Fact_Visit[DateKey])
			VAR DateRange = FILTER(
			    ALL(Dim_Date[DateKey]),
			    Dim_Date[DateKey] >= MinDate && Dim_Date[DateKey] <= MaxDate
			)
			VAR Users = DISTINCT(Dim_User[UserID])
			VAR EntityGroups = DATATABLE(
			    "EntityGroup", STRING,
			    {
			        {"Customers"},
			        {"Consumers"},
			        {"Influencers"}
			    }
			)
			VAR BaseTable = CROSSJOIN(DateRange, Users, EntityGroups)
			RETURN
			ADDCOLUMNS(
			    BaseTable,
			    "DailyTarget", 
			    SWITCH(
			        [EntityGroup],
			        "Customers", 10,
			        "Influencers", 10,
			        "Consumers", 5,
			        10
			    )
			)
			```

	column DateKey
		dataType: dateTime
		formatString: Short Date
		lineageTag: c1d2e3f4-5678-9abc-def0-123456789abc
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column UserID
		dataType: int64
		formatString: 0
		lineageTag: fact-target-userid-001
		summarizeBy: none
		sourceColumn: UserID
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column EntityGroup
		dataType: string
		lineageTag: fact-target-entitygroup-001
		summarizeBy: none
		sourceColumn: EntityGroup
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column DailyTarget
		dataType: int64
		formatString: 0
		lineageTag: fact-target-dailytarget-001
		summarizeBy: sum
		sourceColumn: DailyTarget
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	measure Target_Sum = SUM(Fact_Target[DailyTarget])
		formatString: #,##0
		displayFolder: FRD Dashboard\Targets
		lineageTag: fact-target-sum-001

	measure Target_Achievement_Pct = ```
		VAR TargetValue = [Target_Sum]
		VAR ActualValue = [FRD_Target]
		RETURN
		IF(TargetValue = 0, BLANK(), DIVIDE(ActualValue, TargetValue, 0))
		```
		formatString: 0%
		displayFolder: FRD Dashboard\Performance
		lineageTag: fact-target-achievement-001

	annotation PBI_ResultType = Table

