table Fact_ProjectConversion
	lineageTag: 9e65a144-53c6-4509-8230-315bc142daf6

	measure Total_Conversions = COUNTROWS('Fact_ProjectConversion')
		formatString: 0
		displayFolder: Conversion Counts
		lineageTag: 1a1b1c1d-1e1f-1a1b-1c1d-1e1f1a1b1c1d

		changedProperty = IsHidden

	measure Converted_Projects =
			CALCULATE(
			    COUNTROWS('Fact_ProjectConversion'),
			    'Fact_ProjectConversion'[IsConverted] = 1
			)
		formatString: 0
		displayFolder: Conversion Counts
		lineageTag: 2a2b2c2d-2e2f-2a2b-2c2d-2e2f2a2b2c2d

		changedProperty = IsHidden

	measure Project_Conversion_Rate = DIVIDE([Converted_Projects], [Total_Conversions], 0)
		formatString: 0.0%
		displayFolder: Rates
		lineageTag: 3a3b3c3d-3e3f-3a3b-3c3d-3e3f3a3b3c3d

		changedProperty = IsHidden

	measure Engineer_Reward_Eligible_Count =
			CALCULATE(
			    COUNTROWS('Fact_ProjectConversion'),
			    'Fact_ProjectConversion'[IsEngineerRewardEligible] = 1,
			    'Fact_ProjectConversion'[IsConverted] = 1
			)
		formatString: 0
		displayFolder: Rewards\Engineer
		lineageTag: 4a4b4c4d-4e4f-4a4b-4c4d-4e4f4a4b4c4d

		changedProperty = IsHidden

	measure Contractor_Reward_Eligible_Count =
			CALCULATE(
			    COUNTROWS('Fact_ProjectConversion'),
			    'Fact_ProjectConversion'[IsContractorRewardEligible] = 1,
			    'Fact_ProjectConversion'[IsConverted] = 1
			)
		formatString: 0
		displayFolder: Rewards\Contractor
		lineageTag: 5a5b5c5d-5e5f-5a5b-5c5d-5e5f5a5b5c5d

		changedProperty = IsHidden

	measure Conversion_Funnel_Stage_Distribution =
			VAR TotalByStage = COUNTROWS('Fact_ProjectConversion')
			VAR GrandTotal = CALCULATE(COUNTROWS('Fact_ProjectConversion'), ALL('Fact_ProjectConversion'[stage]))
			RETURN
			DIVIDE(TotalByStage, GrandTotal, 0)
		formatString: 0.0%
		displayFolder: Analytics\Funnel
		lineageTag: 6a6b6c6d-6e6f-6a6b-6c6d-6e6f6a6b6c6d

		changedProperty = IsHidden

	measure Conversion_Velocity_Days = ```
			VAR AvgDaysToConvert = 
			    AVERAGEX(
			        FILTER('Fact_ProjectConversion', 'Fact_ProjectConversion'[IsConverted] = 1),
			        DATEDIFF('Fact_ProjectConversion'[created_at], 'Fact_ProjectConversion'[updated_at], DAY)
			    )
			RETURN
			IF(ISBLANK(AvgDaysToConvert), 0, AvgDaysToConvert)
			```
		formatString: 0.0
		displayFolder: Analytics\Velocity
		lineageTag: 7a7b7c7d-7e7f-7a7b-7c7d-7e7f7a7b7c7d

		changedProperty = IsHidden

	measure Conversion_Trend_MoM =
			VAR CurrentMonthConversions = [Converted_Projects]
			VAR PreviousMonthConversions = CALCULATE([Converted_Projects], PREVIOUSMONTH('Dim_Date'[Date]))
			RETURN
			DIVIDE(CurrentMonthConversions - PreviousMonthConversions, PreviousMonthConversions, 0)
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence\Growth
		lineageTag: 8a8b8c8d-8e8f-8a8b-8c8d-8e8f8a8b8c8d

		changedProperty = IsHidden

	measure Retail_Delivery_Rate =
			VAR RetailDeliveries = CALCULATE(
			    COUNTROWS('Fact_ProjectConversion'),
			    'Fact_ProjectConversion'[DeliveryType] = "Factory DN"
			)
			RETURN
			DIVIDE(RetailDeliveries, [Total_Conversions], 0)
		formatString: 0.0%
		displayFolder: Rates\Delivery
		lineageTag: 9a9b9c9d-9e9f-9a9b-9c9d-9e9f9a9b9c9d

		changedProperty = IsHidden

	measure Pending_Conversions =
			CALCULATE(
			    COUNTROWS('Fact_ProjectConversion'),
			    'Fact_ProjectConversion'[StatusGroup] = "Pending"
			)
		formatString: 0
		displayFolder: Conversion Counts\By Status
		lineageTag: 0b0c0d0e-0f0a-0b0c-0d0e-0f0a0b0c0d0e

		changedProperty = IsHidden

	measure Conversion_Anomaly_Flag =
			VAR AvgConversions = AVERAGEX(ALL('Dim_Date'[Date]), [Converted_Projects])
			VAR StdDeviation = STDEVX.P(ALL('Dim_Date'[Date]), [Converted_Projects])
			VAR CurrentConversions = [Converted_Projects]
			VAR ZScore = DIVIDE(CurrentConversions - AvgConversions, StdDeviation, 0)
			RETURN
			IF(ABS(ZScore) > 2, 1, 0)
		formatString: 0
		displayFolder: Analytics\Anomaly Detection
		lineageTag: 1c1d1e1f-1a1b-1c1d-1e1f-1a1b1c1d1e1f

		changedProperty = IsHidden

	measure Site_Conversion_Pareto = ```
			VAR CurrentSiteConversions = [Converted_Projects]
			VAR AllSiteConversions = 
			    ADDCOLUMNS(
			        SUMMARIZE(ALL('Fact_ProjectConversion'), 'Fact_ProjectConversion'[SiteID]),
			        "@Conversions", CALCULATE([Converted_Projects])
			    )
			VAR RankedSites = 
			    FILTER(AllSiteConversions, [@Conversions] >= CurrentSiteConversions)
			VAR RunningTotal = SUMX(RankedSites, [@Conversions])
			VAR GrandTotal = CALCULATE([Converted_Projects], ALL('Fact_ProjectConversion'))
			RETURN
			DIVIDE(RunningTotal, GrandTotal, 0)
			```
		formatString: 0.0%
		displayFolder: Analytics\Pareto
		lineageTag: 2d2e2f2a-2b2c-2d2e-2f2a-2b2c2d2e2f2a

		changedProperty = IsHidden

	measure Total_conversions_MT = SUM(Fact_ProjectConversion[qty_in_mt])
		displayFolder: Analytics\Engagement
		lineageTag: 8147ebce-77aa-4288-99dd-0b068f9b1cea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Active_Contractors =
			COALESCE(
				CALCULATE(
					DISTINCTCOUNT('Fact_ProjectConversion'[contractor_id]),
					NOT ISBLANK('Fact_ProjectConversion'[contractor_id]),
					UPPER('Fact_ProjectConversion'[OrderStatus]) = "APPROVED"
				),
				0
			)
		formatString: 0
		displayFolder: Conversion Counts\By Status
		lineageTag: 7f05a2a2-0e1b-4d4f-a65e-1a8fbaea8799

	column ConversionID
		dataType: int64
		formatString: 0
		lineageTag: cce26385-305f-4699-ba2e-f8e40dea0371
		summarizeBy: count
		sourceColumn: ConversionID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderStatus
		dataType: string
		lineageTag: 15e6f5ec-a79d-4196-9367-381df639ae02
		summarizeBy: none
		sourceColumn: OrderStatus

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DeliveryMethod
		dataType: string
		lineageTag: 9faacf23-70e9-4f17-aeb4-d34a9f58d0d9
		summarizeBy: none
		sourceColumn: DeliveryMethod

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column delete_status
		dataType: string
		lineageTag: 3f0f1c5e-354a-405d-8728-36b3773c2eaf
		summarizeBy: none
		sourceColumn: delete_status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SiteID
		dataType: int64
		formatString: 0
		lineageTag: 3edbcb3f-0040-453e-83b4-3b9960b3d840
		summarizeBy: count
		sourceColumn: SiteID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EngineerID
		dataType: int64
		formatString: 0
		lineageTag: 564aa26d-0a27-42d2-9471-f2d14d5b0018
		summarizeBy: count
		sourceColumn: EngineerID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DealerID
		dataType: int64
		formatString: 0
		lineageTag: 14db75c1-a0c7-4e09-857c-9601c4f288b2
		summarizeBy: count
		sourceColumn: DealerID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RetailerID
		dataType: int64
		formatString: 0
		lineageTag: ad9ee0c9-b2b4-4b0f-afab-6523082493aa
		summarizeBy: count
		sourceColumn: RetailerID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BazaarID
		dataType: int64
		formatString: 0
		lineageTag: 52ff5d65-41d0-4719-949a-3fe0341ed946
		summarizeBy: count
		sourceColumn: BazaarID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 0a9b1300-e572-498d-9837-eb5d0383ad4c
		summarizeBy: none
		sourceColumn: created_at

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: a82998e0-4551-4273-a3d5-2205354e87b7
		summarizeBy: none
		sourceColumn: updated_at

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EngineerLoyalty
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cad10395-175a-4271-be08-d3d4545aedfc
		summarizeBy: none
		sourceColumn: EngineerLoyalty

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ContractorLoyalty
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: aa727c8e-5e02-42ba-96b9-5312ddf156c9
		summarizeBy: none
		sourceColumn: ContractorLoyalty

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column assigned_sr
		dataType: string
		lineageTag: 5d976dda-718a-4679-a906-1d2c21dfa5bb
		summarizeBy: none
		sourceColumn: assigned_sr

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column assigned_cro
		dataType: string
		lineageTag: b1412640-7414-4448-810a-d76706518550
		summarizeBy: none
		sourceColumn: assigned_cro

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column assigned_bdo
		dataType: string
		lineageTag: adf7107e-c69f-497c-9462-d6507b9b798d
		summarizeBy: none
		sourceColumn: assigned_bdo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column assigned_asm
		dataType: string
		lineageTag: b9e4a6b1-3edf-4cf7-98f1-4976574305ed
		summarizeBy: none
		sourceColumn: assigned_asm

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column total_amount
		dataType: double
		lineageTag: f1bdc296-ef57-4ea5-bbe3-7152f19cc968
		summarizeBy: sum
		sourceColumn: total_amount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column stage
		dataType: string
		lineageTag: f83a7ca6-863d-472e-ae5c-06092dea9354
		summarizeBy: none
		sourceColumn: stage

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ConversionDateKey
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2d508ee4-6c00-4041-ad9b-c92baa661900
		summarizeBy: none
		sourceColumn: ConversionDateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ClientKey
		dataType: string
		lineageTag: 46a44625-3ef9-4746-88f7-211cbfa3ad1a
		summarizeBy: none
		sourceColumn: ClientKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DeliveryType
		dataType: string
		lineageTag: d652d6b0-3b4c-4470-84bc-494657708fb3
		summarizeBy: none
		sourceColumn: DeliveryType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StatusGroup
		dataType: string
		lineageTag: f9242ed7-92ec-4977-9942-991ff2ae69d0
		summarizeBy: none
		sourceColumn: StatusGroup

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsConverted
		dataType: int64
		formatString: 0
		lineageTag: f5d9e5e4-f5f9-42af-9bee-cd7286861254
		summarizeBy: sum
		sourceColumn: IsConverted

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsEngineerRewardEligible
		dataType: int64
		formatString: 0
		lineageTag: 8f3d0008-df7c-43e9-b905-7ba6403f8883
		summarizeBy: sum
		sourceColumn: IsEngineerRewardEligible

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IsContractorRewardEligible
		dataType: int64
		formatString: 0
		lineageTag: 736df42f-0251-44b4-b011-32bd1b3554d6
		summarizeBy: sum
		sourceColumn: IsContractorRewardEligible

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrganizationID
		dataType: int64
		formatString: 0
		lineageTag: 4f6f53e8-0af7-4d23-8c32-0e55f9d4da3a
		summarizeBy: count
		sourceColumn: OrganizationID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CompanyCode
		dataType: string
		lineageTag: 6bfc4d83-6b3a-4dcb-b2c2-4f97a48fce5a
		summarizeBy: none
		sourceColumn: CompanyCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column total_quantity
		dataType: double
		lineageTag: 997b3f03-6a38-4237-bf0c-56203522f519
		summarizeBy: sum
		sourceColumn: total_quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column unit
		dataType: string
		lineageTag: fe3a178b-a30a-4e0b-abba-4e08ba84545d
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column contractor_id
		dataType: int64
		formatString: 0
		lineageTag: 583cbbe3-feb5-4988-9a19-d394d2255f1c
		summarizeBy: sum
		sourceColumn: contractor_id

		annotation SummarizationSetBy = Automatic

	column bkash_number
		dataType: string
		lineageTag: 27d88a7f-58a9-4817-9425-4571b6cb9d18
		summarizeBy: none
		sourceColumn: bkash_number

		annotation SummarizationSetBy = Automatic

	column contractor_name
		dataType: string
		lineageTag: 19f25acb-7780-41a2-a2a7-65df169f3069
		summarizeBy: none
		sourceColumn: contractor_name

		annotation SummarizationSetBy = Automatic

	column contractor_phone
		dataType: string
		lineageTag: f2bfd5ff-bb65-43ab-94c4-e81425a2ae89
		summarizeBy: none
		sourceColumn: contractor_phone

		annotation SummarizationSetBy = Automatic

	column bank_account_id
		dataType: int64
		formatString: 0
		lineageTag: a6f00428-a058-413a-bb22-bf83bde43ccd
		summarizeBy: sum
		sourceColumn: bank_account_id

		annotation SummarizationSetBy = Automatic

	column qty_in_mt
		dataType: double
		lineageTag: 6c4b1e2a-4b6a-4a7d-9b1b-3b0d0a6f1b3c
		summarizeBy: sum
		sourceColumn: qty_in_mt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_ProjectConversion = m
		mode: import
		source = ```
				// ============================================================
				// Fact_ProjectConversion - Project Conversion Fact Table
				// Source: public project_conversion (836 records)
				// 
				// PURPOSE:
				// Tracks the conversion journey from Site visit to Order
				// Links Engineers/Contractors to conversion rewards
				// 
				// KEY FIELDS (from ERD analysis):
				// - order_status, delivery_method
				// - loyalty_of_engineer, loyalty_of_contractor (reward eligibility)
				// - assigned_sr, assigned_cro, assigned_bdo, assigned_asm (role assignments)
				// - site_id, engineer_id, dealer_id, retailer_id, bazaar_id
				// ============================================================
				
				let
				    // Reference the existing 'public project_conversion' table in Power BI
				    Source = #"public project_conversion",
				    
				    // ---- Get Available Columns ----
				    AllColumns = Table.ColumnNames(Source),
				    
				    // ---- Define Expected Columns (based on ERD) ----
				    ExpectedCoreColumns = {
				        "id", "order_status", "delivery_method", "delete_status",
				        "organization_id",
				        "site_id", "engineer_id", "dealer_id", "retailer_id", "bazaar_id",
				        "created_at", "updated_at"
				    },
				    
				    // ---- Define Optional Columns ----
				    OptionalColumns = {
				        "loyalty_of_engineer", "loyalty_of_contractor",
				        "assigned_sr", "assigned_cro", "assigned_bdo", "assigned_asm",
				        "total_amount", "stage", "feedback"
				    },
				    
				    // ---- Select Available Columns ----
				    AvailableColumns = List.Select(
				        ExpectedCoreColumns & OptionalColumns, 
				        each List.Contains(AllColumns, _)
				    ),
				    
				    SelectedColumns = Table.SelectColumns(Source, AvailableColumns),
				    
				    // ---- Rename Core Columns ----
				    RenamedColumns = Table.RenameColumns(SelectedColumns, {
				        {"id", "ConversionID"},
				        {"order_status", "OrderStatus"},
				        {"delivery_method", "DeliveryMethod"},
				        {"organization_id", "OrganizationID"},
				        {"site_id", "SiteID"},
				        {"bazaar_id", "BazaarID"}
				    }, MissingField.Ignore),
				    
				    // Ensure OrganizationID exists even if the source column is missing
				    WithOrganizationID = if Table.HasColumns(RenamedColumns, "OrganizationID")
				        then RenamedColumns
				        else Table.AddColumn(RenamedColumns, "OrganizationID", each null, Int64.Type),
				    
				    // ---- Conditionally Rename Optional Columns ----
				    WithRenames1 = if Table.HasColumns(WithOrganizationID, "engineer_id") 
				        then Table.RenameColumns(WithOrganizationID, {{"engineer_id", "EngineerID"}})
				        else WithOrganizationID,
				    
				    WithRenames2 = if Table.HasColumns(WithRenames1, "dealer_id") 
				        then Table.RenameColumns(WithRenames1, {{"dealer_id", "DealerID"}})
				        else WithRenames1,
				    
				    WithRenames3 = if Table.HasColumns(WithRenames2, "retailer_id") 
				        then Table.RenameColumns(WithRenames2, {{"retailer_id", "RetailerID"}})
				        else WithRenames2,
				    
				    WithRenames4 = if Table.HasColumns(WithRenames3, "loyalty_of_engineer") 
				        then Table.RenameColumns(WithRenames3, {{"loyalty_of_engineer", "EngineerLoyalty"}})
				        else WithRenames3,
				    
				    WithRenames5 = if Table.HasColumns(WithRenames4, "loyalty_of_contractor") 
				        then Table.RenameColumns(WithRenames4, {{"loyalty_of_contractor", "ContractorLoyalty"}})
				        else WithRenames4,
				    
				    FinalRenames = WithRenames5,
				    
				    // ---- Check if loyalty columns exist (evaluate once) ----
				    HasEngineerLoyalty = Table.HasColumns(FinalRenames, "EngineerLoyalty"),
				    HasContractorLoyalty = Table.HasColumns(FinalRenames, "ContractorLoyalty"),
				
				    // ---- Helper: normalize flags to 0/1 safely (supports 0/1, true/false, and common text) ----
				    AsFlag01 = (v as any) as nullable number =>
				        let
				            n = try Number.From(v) otherwise null,
				            t =
				                if n <> null then n
				                else
				                    let
				                        s = try Text.Lower(Text.From(v)) otherwise null
				                    in
				                        if s = null then null
				                        else if s = "true" or s = "t" or s = "yes" or s = "y" then 1
				                        else if s = "false" or s = "f" or s = "no" or s = "n" then 0
				                        else try Number.FromText(s) otherwise null
				        in
				            if t = null then null else if t <> 0 then 1 else 0,
				    
				    // ---- Filter out deleted records ----
				    ActiveRecords =
				        if Table.HasColumns(FinalRenames, "delete_status") then
				            Table.SelectRows(
				                FinalRenames,
				                each
				                    let
				                        ds = try Text.Upper(Text.From([delete_status])) otherwise null
				                    in
				                        ds = null or ds = "NO"
				            )
				        else
				            FinalRenames,
				    
				    // ---- Company Code (ACL/AIL) ----
				    WithCompanyCode = Table.AddColumn(ActiveRecords, "CompanyCode", each
				        if [OrganizationID] = 1 then "ACL"
				        else if [OrganizationID] = 2 then "AIL"
				        else "Unknown",
				        type text
				    ),
				    
				    // ---- Extract Date Key ----
				    WithDateKey = Table.AddColumn(WithCompanyCode, "ConversionDateKey", each 
				        Date.From([created_at]),
				        type date
				    ),
				    
				    // ---- Create Client Key (Site is primary for conversions) ----
				    WithClientKey = Table.AddColumn(WithDateKey, "ClientKey", each 
				        "Site-" & Text.From([SiteID]),
				        type text
				    ),
				    
				    // ---- Delivery Type Classification ----
				    // Per PRD: "Factory DN" = Retail Delivery, "General Delivery" = CRO visit required
				    WithDeliveryType = Table.AddColumn(WithClientKey, "DeliveryType", each 
				        if [DeliveryMethod] = "Retail Delivery" then "Factory DN"
				        else if [DeliveryMethod] = "General Delivery" then "General Delivery"
				        else [DeliveryMethod],
				        type text
				    ),
				    
				    // ---- Conversion Status Group ----
				    WithStatusGroup = Table.AddColumn(WithDeliveryType, "StatusGroup", each 
				        if Text.Upper([OrderStatus]) = "PENDING" then "Pending"
				        else if Text.Upper([OrderStatus]) = "APPROVED" or Text.Upper([OrderStatus]) = "COMPLETED" then "Converted"
				        else if Text.Upper([OrderStatus]) = "CANCELLED" then "Cancelled"
				        else "Other",
				        type text
				    ),
				    
				    // ---- Is Converted Flag ----
				    WithConvertedFlag = Table.AddColumn(WithStatusGroup, "IsConverted", each 
				        if [StatusGroup] = "Converted" then 1 else 0,
				        Int64.Type
				    ),
				
				    // Buffer to avoid query-folding type mismatches (e.g., integer = boolean in PostgreSQL)
				    BufferedForEligibility = Table.Buffer(WithConvertedFlag),
				    
				    // ---- Engineer Eligible for Reward ----
				    WithEngineerReward = Table.AddColumn(BufferedForEligibility, "IsEngineerRewardEligible", each 
				        if HasEngineerLoyalty and [IsConverted] = 1 and AsFlag01([EngineerLoyalty]) = 1 then 1 else 0,
				        Int64.Type
				    ),
				    
				    // ---- Contractor Eligible for Reward ----
				    WithContractorReward = Table.AddColumn(WithEngineerReward, "IsContractorRewardEligible", each 
				        if HasContractorLoyalty and [IsConverted] = 1 and AsFlag01([ContractorLoyalty]) = 1 then 1 else 0,
				        Int64.Type
				    ),
				    
				    // ---- Set Data Types ----
				    TypedTable = Table.TransformColumnTypes(WithContractorReward, {
				        {"ConversionID", Int64.Type},
				        {"OrderStatus", type text},
				        {"DeliveryMethod", type text},
				        {"OrganizationID", Int64.Type},
				        {"CompanyCode", type text},
				        {"SiteID", Int64.Type},
				        {"BazaarID", Int64.Type},
				        {"ConversionDateKey", type date},
				        {"ClientKey", type text},
				        {"DeliveryType", type text},
				        {"StatusGroup", type text},
				        {"IsConverted", Int64.Type},
				        {"IsEngineerRewardEligible", Int64.Type},
				        {"IsContractorRewardEligible", Int64.Type},
				        {"total_amount", type number},
				        {"created_at", type datetime},
				        {"updated_at", type datetime}
				    }),
				  #"Merged queries" = Table.NestedJoin(TypedTable, {"ConversionID"}, #"public project_conversion", {"id"}, "public project_conversion", JoinKind.LeftOuter),
				  #"Expanded public project_conversion" = Table.ExpandTableColumn(#"Merged queries", "public project_conversion", {"total_quantity", "unit"}, {"total_quantity", "unit"}),
				  #"Changed column type" = Table.TransformColumnTypes(#"Expanded public project_conversion", {{"total_quantity", type number}, {"unit", type text}}),
				  #"Added qty_in_mt" = Table.AddColumn(
				    #"Changed column type",
				    "qty_in_mt",
				    each
				      let
				        q = try Number.From([total_quantity]) otherwise null,
				        u = try Text.Lower(Text.From([unit])) otherwise null,
				        isBag = if u = null then false else Text.Contains(u, "bag")
				      in
				        if q = null then null else if isBag then q / 20 else q,
				    type number
				  ),
				  #"Merged queries 1" = Table.NestedJoin(#"Added qty_in_mt", {"SiteID"}, #"public potential_site", {"id"}, "public potential_site", JoinKind.LeftOuter),
				  #"Expanded public potential_site" = Table.ExpandTableColumn(#"Merged queries 1", "public potential_site", {"contractor_id"}, {"contractor_id"}),
				  #"Merged queries 2" = Table.NestedJoin(#"Expanded public potential_site", {"contractor_id"}, #"public client", {"id"}, "public client", JoinKind.LeftOuter),
				  #"Expanded public client" = Table.ExpandTableColumn(#"Merged queries 2", "public client", {"bkash_number", "name", "phone", "bank_account_id"}, {"bkash_number", "name", "phone", "bank_account_id"}),
				  #"Renamed columns" = Table.RenameColumns(#"Expanded public client", {{"name", "contractor_name"}, {"phone", "contractor_phone"}})
				in
				    #"Renamed columns"
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

