table Fact_Target
	lineageTag: 36f33059-4adf-4405-890d-237f2c919742

	column DateKey
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2de34b1a-3f49-4fbf-aeae-11450a984bc9
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column UserID
		dataType: int64
		formatString: 0
		lineageTag: 675804bf-0add-4e5c-919c-a1f5ce82b2cd
		summarizeBy: none
		sourceColumn: UserID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EntityGroup
		dataType: string
		lineageTag: 4632518b-027e-44eb-ae73-596bef356c7f
		summarizeBy: none
		sourceColumn: EntityGroup

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DailyTarget
		dataType: int64
		formatString: 0
		lineageTag: 9d832446-e801-41bb-b6cf-ea05c70bd9f7
		summarizeBy: sum
		sourceColumn: DailyTarget

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Fact_Target = m
		mode: import
		source = ```
				let
				    // Get date range from Fact_Visit
				    VisitDates = Fact_Visit[DateKey],
				    MinDate = List.Min(VisitDates),
				    MaxDate = List.Max(VisitDates),
				    
				    // Generate date list
				    DateList = List.Dates(MinDate, Duration.Days(MaxDate - MinDate) + 1, #duration(1, 0, 0, 0)),
				    
				    // Get distinct UserIDs
				    UserList = List.Distinct(Dim_User[UserID]),
				    
				    // Entity groups with their targets
				    EntityTargets = Table.FromRecords({
				        [EntityGroup = "Customers", DailyTarget = 10],
				        [EntityGroup = "Consumers", DailyTarget = 5],
				        [EntityGroup = "Influencers", DailyTarget = 10]
				    }),
				    
				    // Create date table
				    DateTable = Table.FromList(DateList, Splitter.SplitByNothing(), {"DateKey"}, null, ExtraValues.Error),
				    DateTableTyped = Table.TransformColumnTypes(DateTable, {{"DateKey", type date}}),
				    
				    // Create user table
				    UserTable = Table.FromList(UserList, Splitter.SplitByNothing(), {"UserID"}, null, ExtraValues.Error),
				    UserTableTyped = Table.TransformColumnTypes(UserTable, {{"UserID", Int64.Type}}),
				    
				    // Cross join all three
				    DateUser = Table.AddColumn(DateTableTyped, "UserData", each UserTableTyped),
				    DateUserExpanded = Table.ExpandTableColumn(DateUser, "UserData", {"UserID"}, {"UserID"}),
				    
				    DateUserEntity = Table.AddColumn(DateUserExpanded, "EntityData", each EntityTargets),
				    Result = Table.ExpandTableColumn(DateUserEntity, "EntityData", {"EntityGroup", "DailyTarget"}, {"EntityGroup", "DailyTarget"}),
				    
				    // Set column types
				    FinalTable = Table.TransformColumnTypes(Result, {
				        {"DateKey", type date},
				        {"UserID", Int64.Type},
				        {"EntityGroup", type text},
				        {"DailyTarget", Int64.Type}
				    })
				in
				    FinalTable
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

