table Fact_Visit
	lineageTag: c56054fa-e8f3-46d0-95fa-016dcd2cc3bf

	measure Total_Retailer_Visits = ```
			
					CALCULATE(
						[Total_Visits],
						'Fact_Visit'[ClientType] = "Retailer"
					)
			```
		formatString: 0
		displayFolder: Visit Counts
		lineageTag: 54fe40e6-9db7-466a-99e5-ab9705614664

		changedProperty = IsHidden

	measure Total_Dealer_Visits = ```
			
					CALCULATE(
						[Total_Visits],
						'Fact_Visit'[ClientType] = "Dealer"
					)
			```
		formatString: 0
		displayFolder: Visit Counts
		lineageTag: a5e4d983-80ab-4b70-b9fb-7f624ba43ae4

		changedProperty = IsHidden

	measure Territory_Captured_Visits = ```
			
			        CALCULATE(
			            COUNTROWS('Fact_Visit'),
			            'Fact_Visit'[HasTerritory] = 1
			        )
			```
		formatString: 0
		displayFolder: GPS & Territory
		lineageTag: 398beba9-89ad-4586-ae55-85f3dfd8e803

		changedProperty = IsHidden

	measure No_Territory_Visits = ```
			
			        CALCULATE(
			            COUNTROWS('Fact_Visit'),
			            'Fact_Visit'[HasTerritory] = 0
			        )
			```
		formatString: 0
		displayFolder: GPS & Territory
		lineageTag: 6f8dc6b2-dce7-4366-b1f2-eb3a53e3a142

		changedProperty = IsHidden

	measure GPS_Capture_Rate = ```
			
			        DIVIDE([Territory_Captured_Visits], [Total_Visits], 0)
			```
		displayFolder: Rates
		lineageTag: 06f8ac33-1b5f-46bf-b782-ee4f31e8c4d5

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GPS_Missing_Rate = ```
			
			        DIVIDE([No_Territory_Visits], [Total_Visits], 0)
			```
		lineageTag: e5c69545-b184-4afd-a921-8342eb54e76b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Zone_Mismatch_Visits
		lineageTag: 3ccd55f5-00a4-452c-9ad2-1dedafee8150

		changedProperty = IsHidden

	measure Total_Visits = COUNTROWS('Fact_Visit')
		formatString: #,##0
		displayFolder: Visit Counts\Base
		lineageTag: 34aafb72-4095-4c1a-bdcc-31f7eb99b15f

		changedProperty = IsHidden

	measure Unique_Clients_Visited = DISTINCTCOUNT('Fact_Visit'[ClientKey])
		formatString: #,##0
		displayFolder: Visit Counts\Base
		lineageTag: 31ee6a27-68ba-41ec-ac33-8867a08436aa

		changedProperty = IsHidden

	measure Active_Employees = DISTINCTCOUNT('Fact_Visit'[EmployeeID])
		formatString: #,##0
		displayFolder: Visit Counts\Base
		lineageTag: 3b1eb32b-316d-4216-952d-9df7f823d42d

		changedProperty = IsHidden

	measure Visits_Per_Employee = ```
			
			        DIVIDE([Total_Visits], [Active_Employees], 0)
			```
		formatString: #,##0.0
		displayFolder: Ratios\Productivity
		lineageTag: 264f432d-eae9-4fbe-881a-0c85dc995b1e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_Per_Client = ```
			
			        DIVIDE([Total_Visits], [Unique_Clients_Visited], 0)
			```
		formatString: #,##0.0
		displayFolder: Ratios\Productivity
		lineageTag: edb0cf22-8b21-4aa2-af54-03fb078e5d8f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Clients_Per_Employee = ```
			
			        DIVIDE([Unique_Clients_Visited], [Active_Employees], 0)
			```
		formatString: #,##0.0
		displayFolder: Ratios\Productivity
		lineageTag: 0de2c990-7e66-4599-a12c-6ac62120c0b7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_With_Photos = ```
			
			        CALCULATE(
			            COUNTROWS('Fact_Visit'),
			            'Fact_Visit'[HasPhoto] = 1
			        )
			```
		formatString: #,##0
		displayFolder: Quality Compliance
		lineageTag: e7589b82-1e9d-42c1-b28e-b9ad29001f0b

		changedProperty = IsHidden

	measure Photo_Compliance_Rate = ```
			
			        DIVIDE([Visits_With_Photos], [Total_Visits], 0)
			```
		formatString: 0.0%
		displayFolder: Quality Compliance\Rates
		lineageTag: 34000498-b990-45b9-ab14-7daa8855b199

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_With_Product_Photos = ```
			
			        CALCULATE(
			            COUNTROWS('Fact_Visit'),
			            'Fact_Visit'[HasProductPhoto] = 1
			        )
			```
		formatString: #,##0
		displayFolder: Quality Compliance
		lineageTag: 6396bece-4da8-439d-9215-30ffa8fb5344

		changedProperty = IsHidden

	measure Product_Photo_Rate = ```
			
			        DIVIDE([Visits_With_Product_Photos], [Total_Visits], 0)
			```
		formatString: 0.0%
		displayFolder: Quality Compliance\Rates
		lineageTag: 0d5dce4a-d3dd-48c6-bfa6-329f082be560

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_With_Feedback = ```
			
			        CALCULATE(
			            COUNTROWS('Fact_Visit'),
			            'Fact_Visit'[HasFeedback] = 1
			        )
			```
		formatString: #,##0
		displayFolder: Quality Compliance
		lineageTag: 1b03d3bd-a171-4b27-8874-52d7b0c0cff5

		changedProperty = IsHidden

	measure Feedback_Rate = ```
			
			        DIVIDE([Visits_With_Feedback], [Total_Visits], 0)
			```
		formatString: 0.0%
		displayFolder: Quality Compliance\Rates
		lineageTag: 1e7d782f-d710-4b94-b7d3-5b8cc454ed66

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visit_Quality_Score = ```
			
			        (
			            [Photo_Compliance_Rate] * 0.4 +
			            [Product_Photo_Rate] * 0.3 +
			            [Feedback_Rate] * 0.3
			        )
			```
		formatString: 0.0%
		displayFolder: Quality Compliance\Score
		lineageTag: cdf6008b-b3cc-41a7-bdfa-1411dfb0d134

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Clients_Visited_Once = ```
			
			        COUNTROWS(
			            FILTER(
			                VALUES('Fact_Visit'[ClientKey]),
			                CALCULATE(COUNTROWS('Fact_Visit')) = 1
			            )
			        )
			```
		formatString: #,##0
		displayFolder: Client Analysis
		lineageTag: 214779a5-b311-4579-aaf1-e8473c7c095e

		changedProperty = IsHidden

	measure Clients_Visited_Multiple = ```
			
			        COUNTROWS(
			            FILTER(
			                VALUES('Fact_Visit'[ClientKey]),
			                CALCULATE(COUNTROWS('Fact_Visit')) > 1
			            )
			        )
			```
		formatString: #,##0
		displayFolder: Client Analysis
		lineageTag: 29103485-6052-4d0d-85ce-702bec344bd2

		changedProperty = IsHidden

	measure Repeat_Visit_Rate = ```
			
			        DIVIDE([Clients_Visited_Multiple], [Unique_Clients_Visited], 0)
			```
		formatString: 0.0%
		displayFolder: Client Analysis\Rates
		lineageTag: 90a3a66c-8a85-47cb-b600-6aef0c143616

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_MTD = ```
			
			        CALCULATE(
			            [Total_Visits],
			            DATESMTD('Dim_Date'[Date])
			        )
			```
		formatString: #,##0
		displayFolder: Time Intelligence\Period to Date
		lineageTag: 50bac071-3622-42a0-aac9-53f59b3180cc

		changedProperty = IsHidden

	measure Visits_QTD = ```
			
			        CALCULATE(
			            [Total_Visits],
			            DATESQTD('Dim_Date'[Date])
			        )
			```
		formatString: #,##0
		displayFolder: Time Intelligence\Period to Date
		lineageTag: 8535cd94-c562-41e5-9311-39b5b1d7c62a

		changedProperty = IsHidden

	measure Visits_YTD = ```
			
			        CALCULATE(
			            [Total_Visits],
			            DATESYTD('Dim_Date'[Date])
			        )
			```
		formatString: #,##0
		displayFolder: Time Intelligence\Period to Date
		lineageTag: 0e81e912-4474-4b27-93a2-7c09d6f4ba0c

		changedProperty = IsHidden

	measure Visits_Previous_Month = ```
			
			        CALCULATE(
			            [Total_Visits],
			            PREVIOUSMONTH('Dim_Date'[Date])
			        )
			```
		formatString: #,##0
		displayFolder: Time Intelligence\Previous Period
		lineageTag: 9c882202-896d-4c78-a93d-a9ccb27aecc5

		changedProperty = IsHidden

	measure Visits_Previous_Quarter = ```
			
			        CALCULATE(
			            [Total_Visits],
			            PREVIOUSQUARTER('Dim_Date'[Date])
			        )
			```
		formatString: #,##0
		displayFolder: Time Intelligence\Previous Period
		lineageTag: f1b149b6-d087-414b-9d8d-dcb5677a907f

		changedProperty = IsHidden

	measure Visits_Previous_Year = ```
			
			        CALCULATE(
			            [Total_Visits],
			            PREVIOUSYEAR('Dim_Date'[Date])
			        )
			```
		formatString: #,##0
		displayFolder: Time Intelligence\Previous Period
		lineageTag: b2879c35-7bf0-4531-9452-1648c0f3c82d

		changedProperty = IsHidden

	measure Visits_MoM_Growth = ```
			
			        DIVIDE(
			            [Total_Visits] - [Visits_Previous_Month],
			            [Visits_Previous_Month],
			            0
			        )
			```
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence\Growth
		lineageTag: 670cb828-a5fb-44f7-aae7-fe07a77be1e7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_YoY_Growth = ```
			
			        DIVIDE(
			            [Total_Visits] - [Visits_Previous_Year],
			            [Visits_Previous_Year],
			            0
			        )
			```
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Time Intelligence\Growth
		lineageTag: d0100c9e-e3c7-4afc-813e-b1c5706a3c15

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_Rolling_7_Days = ```
			
			        CALCULATE(
			            [Total_Visits],
			            DATESINPERIOD('Dim_Date'[Date], MAX('Dim_Date'[Date]), -7, DAY)
			        )
			```
		formatString: #,##0
		displayFolder: Time Intelligence\Rolling
		lineageTag: 6983840a-3280-419a-ac14-e39226e6aaed

		changedProperty = IsHidden

	measure Visits_Rolling_30_Days = ```
			
			        CALCULATE(
			            [Total_Visits],
			            DATESINPERIOD('Dim_Date'[Date], MAX('Dim_Date'[Date]), -30, DAY)
			        )
			```
		formatString: #,##0
		displayFolder: Time Intelligence\Rolling
		lineageTag: c367a91b-f506-458c-93bf-081dea8dc71a

		changedProperty = IsHidden

	measure Unique_Territories =
			CALCULATE(
				DISTINCTCOUNT('Fact_Visit'[territory_id]),
				'Fact_Visit'[HasTerritory] = 1
			)
		formatString: #,##0
		displayFolder: GPS & Territory
		lineageTag: 4566f4a9-877b-46a3-9235-59dec5a91fa7

		changedProperty = IsHidden

	measure Avg_Visits_Per_Day = ```
			
			        DIVIDE(
			            [Total_Visits],
			            DISTINCTCOUNT('Fact_Visit'[DateKey])
			        )
			```
		formatString: #,##0.0
		displayFolder: Ratios\Daily
		lineageTag: 66563689-57d2-40c5-ac30-a7c55ff2a025

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Top_Performer_Visits = ```
			
			        MAXX(
			            VALUES('Fact_Visit'[EmployeeID]),
			            CALCULATE([Total_Visits])
			        )
			```
		formatString: #,##0
		displayFolder: Performance\Benchmarks
		lineageTag: a3669f58-61a5-49ef-9d63-9450f26dea6c

		changedProperty = IsHidden

	measure Bottom_Performer_Visits = ```
			
			        MINX(
			            VALUES('Fact_Visit'[EmployeeID]),
			            CALCULATE([Total_Visits])
			        )
			```
		formatString: #,##0
		displayFolder: Performance\Benchmarks
		lineageTag: 431cb596-4d15-41eb-a9e7-a71d3389072d

		changedProperty = IsHidden

	measure Employees_Above_Target = ```
			
			        VAR TargetVisits = 50
			        RETURN
			        COUNTROWS(
			            FILTER(
			                VALUES('Fact_Visit'[EmployeeID]),
			                CALCULATE([Total_Visits]) >= TargetVisits
			            )
			        )
			```
		formatString: #,##0
		displayFolder: Performance\Targets
		lineageTag: 53b4d37a-fadf-4f2d-8c96-83172b1a6de5

		changedProperty = IsHidden

	measure Employee_Performance_Index =
			
			VAR VisitScore = DIVIDE([Total_Visits], [Top_Performer_Visits], 0) * 40
			VAR QualityScore = [Visit_Quality_Score] * 30
			VAR ClientCoverage = DIVIDE([Unique_Clients_Visited], CALCULATE(DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]), ALL('Dim_Client_Simple')), 0) * 30
			RETURN
			ROUND(VisitScore + QualityScore + ClientCoverage, 1)
		formatString: 0.0
		displayFolder: Analytics
		lineageTag: e1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c6

		changedProperty = IsHidden

	measure Visit_Pareto_Running_Total = ```
			
			VAR CurrentEmployee = MAX('Fact_Visit'[EmployeeID])
			VAR EmployeeVisits = [Total_Visits]
			VAR AllEmployeeVisits = 
			    ADDCOLUMNS(
			        SUMMARIZE(ALL('Fact_Visit'), 'Fact_Visit'[EmployeeID]),
			        "@Visits", CALCULATE([Total_Visits])
			    )
			VAR RankedEmployees = 
			    FILTER(AllEmployeeVisits, [@Visits] >= EmployeeVisits)
			VAR RunningTotal = SUMX(RankedEmployees, [@Visits])
			VAR GrandTotal = CALCULATE([Total_Visits], ALL('Fact_Visit'))
			RETURN
			DIVIDE(RunningTotal, GrandTotal, 0)
			```
		formatString: 0.0%
		displayFolder: Analytics
		lineageTag: f2a3b4c5-e6d7-a8b9-c0d1-e2f3a4b5c6d7

		changedProperty = IsHidden

	measure Visits_Anomaly_Flag =
			VAR AvgVisits = AVERAGEX(ALL('Dim_Date'[Date]), [Total_Visits])
			VAR StdDeviation = STDEVX.P(ALL('Dim_Date'[Date]), [Total_Visits])
			VAR CurrentVisits = [Total_Visits]
			VAR ZScore = DIVIDE(CurrentVisits - AvgVisits, StdDeviation, 0)
			RETURN
			IF(ABS(ZScore) > 2, 1, 0)
		formatString: 0
		displayFolder: Analytics
		lineageTag: a3b4c5d6-e7f8-a9b0-c1d2-e3f4a5b6c7d8

		changedProperty = IsHidden

	measure Visits_Anomaly_Direction =
			VAR AvgVisits = AVERAGEX(ALL('Dim_Date'[Date]), [Total_Visits])
			VAR StdDeviation = STDEVX.P(ALL('Dim_Date'[Date]), [Total_Visits])
			VAR CurrentVisits = [Total_Visits]
			VAR ZScore = DIVIDE(CurrentVisits - AvgVisits, StdDeviation, 0)
			RETURN
			IF(ZScore > 2, "High", IF(ZScore < -2, "Low", "Normal"))
		displayFolder: Analytics\Anomaly Detection
		lineageTag: 575a37eb-189e-4037-8c7e-192f4d7e9d2d

		changedProperty = IsHidden

	measure Days_Since_Last_Visit =
			VAR LastVisitDate = MAX('Fact_Visit'[DateKey])
			VAR Today = TODAY()
			RETURN
			DATEDIFF(LastVisitDate, Today, DAY)
		formatString: 0
		displayFolder: Analytics
		lineageTag: c5d6e7f8-a9b0-c1d2-e3f4-a5b6c7d8e9f0

		changedProperty = IsHidden

	measure Avg_Days_Between_Visits =
			
			VAR VisitDates = SUMMARIZE('Fact_Visit', 'Fact_Visit'[DateKey])
			VAR DateCount = COUNTROWS(VisitDates)
			VAR DateRange = DATEDIFF(MIN('Fact_Visit'[DateKey]), MAX('Fact_Visit'[DateKey]), DAY)
			RETURN
			IF(DateCount > 1, DIVIDE(DateRange, DateCount - 1, 0), BLANK())
		formatString: 0.0
		displayFolder: Analytics\Recency
		lineageTag: d6e7f8a9-b0c1-d2e3-f4a5-b6c7d8e9f0a1

		changedProperty = IsHidden

	measure Employee_Rank_by_Visits =
			
			VAR CurrentVisits = [Total_Visits]
			RETURN
			COUNTROWS(
			    FILTER(
			        SUMMARIZE(ALL('Fact_Visit'), 'Fact_Visit'[EmployeeID], "@V", [Total_Visits]),
			        [@V] > CurrentVisits
			    )
			) + 1
		formatString: 0
		displayFolder: Performance\Rankings
		lineageTag: e7f8a9b0-c1d2-e3f4-a5b6-c7d8e9f0a1b2

		changedProperty = IsHidden

	measure Top_5_Employees_Contribution = ```
			
			VAR Top5 = 
			    TOPN(
			        5,
			        SUMMARIZE(ALL('Fact_Visit'), 'Fact_Visit'[EmployeeID], "@V", [Total_Visits]),
			        [@V], DESC
			    )
			VAR Top5Total = SUMX(Top5, [@V])
			VAR GrandTotal = CALCULATE([Total_Visits], ALL('Fact_Visit'))
			RETURN
			DIVIDE(Top5Total, GrandTotal, 0)
			```
		formatString: 0.0%
		displayFolder: Performance\Rankings
		lineageTag: f8a9b0c1-d2e3-f4a5-b6c7-d8e9f0a1b2c3

		changedProperty = IsHidden

	measure Visit_Streak_Days = ```
			
			VAR MaxDate = MAX('Dim_Date'[Date])
			VAR ConsecutiveDays = 
			    SUMX(
			        GENERATEALL(
			            GENERATESERIES(0, 30, 1),
			            VAR CheckDate = MaxDate - [Value]
			            VAR HasVisit = CALCULATE(COUNTROWS('Fact_Visit'), 'Dim_Date'[Date] = CheckDate) > 0
			            RETURN ROW("@Day", [Value], "@Has", HasVisit)
			        ),
			        IF([@Has] && EARLIER([@Days]) = 0 || ([@Has] && CALCULATE(MAX([@Has]), FILTER(ALL([@Day]), [@Day] < EARLIER([@Day])))) = TRUE(), 1, 0)
			    )
			RETURN ConsecutiveDays
			```
		displayFolder: Analytics\Engagement
		lineageTag: a9b0c1d2-e3f4-a5b6-c7d8-e9f0a1b2c3d4

		changedProperty = IsHidden

	measure Visits_WTD =
			CALCULATE(
			    [Total_Visits],
			    DATESBETWEEN(
			        'Dim_Date'[Date],
			        MAX('Dim_Date'[WeekStartDate]),
			        TODAY()
			    )
			)
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a

		changedProperty = IsHidden

	measure Visits_DateFiltered =
			VAR SelectedFilter = SELECTEDVALUE('DateFilterParam'[FilterOption], "MTD")
			RETURN
			SWITCH(
			    SelectedFilter,
			    "Daily", CALCULATE(
			        [Total_Visits],
			        'Dim_Date'[Date] = TODAY()
			    ),
			    "WTD", [Visits_WTD],
			    "MTD", [Visits_MTD],
			    "YTD", [Visits_YTD],
			    [Visits_MTD]
			)
		formatString: 0
		displayFolder: FRD Dashboard
		lineageTag: 5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b

		changedProperty = IsHidden

	measure Visits_By_Territory =
			VAR HasTerritoryFilter =
				ISFILTERED('Dim_Territory'[territory_id])
					|| ISFILTERED('Dim_Territory'[mainZoneName])
					|| ISFILTERED('Dim_Territory'[mainRegionName])
					|| ISFILTERED('Dim_Territory'[mainTerritoryName])
					|| ISFILTERED('Dim_Territory'[AreaName])
			RETURN
				IF(
					HasTerritoryFilter,
					CALCULATE(
						[Total_Visits],
						TREATAS(VALUES('Dim_Territory'[territory_id]), 'Fact_Visit'[territory_id])
					),
					[Total_Visits]
				)
		formatString: 0
		displayFolder: FRD Dashboard
		lineageTag: 6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c

		changedProperty = IsHidden

	measure Average_Visit_FRD = ```
			
					VAR TotalVisits = COUNTROWS('Fact_Visit')
					VAR UniqueEmployeesWithVisits = DISTINCTCOUNT('Fact_Visit'[EmployeeID])
					RETURN
					IF(
						UniqueEmployeesWithVisits = 0, 
						0, 
						ROUND(DIVIDE(TotalVisits, UniqueEmployeesWithVisits), 0)
					)
			```
		formatString: #,##0
		displayFolder: FRD Dashboard\KPI Tiles
		lineageTag: 2b3c4d5e-6f7a-8901-bcde-f12345678901

		changedProperty = IsHidden

	measure Visits_Current_Month = ```
			
					CALCULATE(
						COUNTROWS('Fact_Visit'),
						DATESMTD('Dim_Date'[Date])
					)
			```
		formatString: #,##0
		displayFolder: FRD Dashboard\MoM Comparison
		lineageTag: 3c4d5e6f-7a8b-9012-cdef-123456789012

		changedProperty = IsHidden

	measure Visits_Previous_Calendar_Month = ```
			
					CALCULATE(
						COUNTROWS('Fact_Visit'),
						DATEADD(DATESMTD('Dim_Date'[Date]), -1, MONTH)
					)
			```
		formatString: #,##0
		displayFolder: FRD Dashboard\MoM Comparison
		lineageTag: 4d5e6f7a-8b9c-0123-def0-234567890123

		changedProperty = IsHidden

	measure MoM_Variance = [Visits_Current_Month] - [Visits_Previous_Calendar_Month]
		formatString: +#,##0;-#,##0;0
		displayFolder: FRD Dashboard\MoM Comparison
		lineageTag: 5e6f7a8b-9c0d-1234-ef01-345678901234

		changedProperty = IsHidden

	measure MoM_Variance_Pct = ```
			
					DIVIDE(
						[MoM_Variance],
						[Visits_Previous_Calendar_Month],
						0
					)
			```
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: FRD Dashboard\MoM Comparison
		lineageTag: 6f7a8b9c-0d1e-2345-f012-456789012345

		changedProperty = IsHidden

	measure Employee_Rank_Asc = ```
			
					VAR CurrentVisits = [Total_Visits]
					VAR AllEmployeeVisits = 
						ADDCOLUMNS(
							SUMMARIZE(
								ALL('Fact_Visit'),
								'Fact_Visit'[EmployeeID]
							),
							"@Visits", [Total_Visits]
						)
					RETURN
					COUNTROWS(
						FILTER(
							AllEmployeeVisits,
							[@Visits] < CurrentVisits
						)
					) + 1
			```
		formatString: 0
		displayFolder: FRD Dashboard\Rankings
		lineageTag: 8b9c0d1e-2f3a-4567-1234-678901234567

		changedProperty = IsHidden

	measure Employee_Rank_Desc = ```
			
					VAR CurrentVisits = [Total_Visits]
					VAR AllEmployeeVisits = 
						ADDCOLUMNS(
							SUMMARIZE(
								ALL('Fact_Visit'),
								'Fact_Visit'[EmployeeID]
							),
							"@Visits", [Total_Visits]
						)
					RETURN
					COUNTROWS(
						FILTER(
							AllEmployeeVisits,
							[@Visits] > CurrentVisits
						)
					) + 1
			```
		formatString: 0
		displayFolder: FRD Dashboard\Rankings
		lineageTag: 9c0d1e2f-3a4b-5678-2345-789012345678

		changedProperty = IsHidden

	measure Is_Top_10 = IF([Employee_Rank_Desc] <= 10, 1, 0)
		formatString: 0
		displayFolder: FRD Dashboard\Rankings
		lineageTag: 0d1e2f3a-4b5c-6789-3456-890123456789

		changedProperty = IsHidden

	measure Is_Bottom_10 = IF([Employee_Rank_Asc] <= 10, 1, 0)
		formatString: 0
		displayFolder: FRD Dashboard\Rankings
		lineageTag: 1e2f3a4b-5c6d-7890-4567-901234567890

		changedProperty = IsHidden

	measure Visits_Clients = ```
			
					CALCULATE(
						COUNTROWS('Fact_Visit'),
						'Fact_Visit'[ClientType] IN {"Dealer", "Retailer"}
					)
			```
		formatString: #,##0
		displayFolder: FRD Dashboard\Entity Filters
		lineageTag: 2f3a4b5c-6d7e-8901-5678-012345678901

		changedProperty = IsHidden

	measure Visits_Influencers = ```
			
					CALCULATE(
						COUNTROWS('Fact_Visit'),
						'Fact_Visit'[ClientType] IN {"Engineer", "Contractor"}
					)
			```
		formatString: #,##0
		displayFolder: FRD Dashboard\Entity Filters
		lineageTag: 3a4b5c6d-7e8f-9012-6789-123456789012

		changedProperty = IsHidden

	measure Visits_Customers = ```
			
					CALCULATE(
						COUNTROWS('Fact_Visit'),
						'Fact_Visit'[ClientType] IN {"Site", "IHB"}
					)
			```
		formatString: #,##0
		displayFolder: FRD Dashboard\Entity Filters
		lineageTag: 4b5c6d7e-8f90-1234-7890-234567890123

		changedProperty = IsHidden

	measure Last_Refresh_DateTime = ```
			
					VAR LastUpdate = MAX('Fact_Visit'[updated_at])
					RETURN
					FORMAT(LastUpdate, "DD-MMM-YYYY HH:MM:SS")
			```
		displayFolder: FRD Dashboard\Metadata
		lineageTag: 5c6d7e8f-9012-3456-8901-345678901234

		changedProperty = IsHidden

	measure Location_Label_Dynamic = ```
				VAR SelectedLevel = SELECTEDVALUE('LocationLevelParam'[LevelOption], "Area")
				VAR TerritoryContext =
					TREATAS(VALUES('Fact_Visit'[territory_id]), 'Dim_Territory'[territory_id])
				RETURN
					CALCULATE(
						SWITCH(
							SelectedLevel,
							"Area", SELECTEDVALUE('Dim_Territory'[AreaName]),
							"Zone", SELECTEDVALUE('Dim_Territory'[mainZoneName]),
							"Territory", SELECTEDVALUE('Dim_Territory'[mainTerritoryName]),
							SELECTEDVALUE('Dim_Territory'[AreaName])
						),
						TerritoryContext
					)
			```
		displayFolder: FRD Dashboard\Location
		lineageTag: 6d7e8f90-1234-5678-9012-456789012345

		changedProperty = IsHidden

	measure Total_Engineer_Visits =
			CALCULATE(
				[Total_Visits],
				'Fact_Visit'[ClientType] = "Engineer"
			)
		formatString: 0
		displayFolder: Visit Counts
		lineageTag: a1b2c3d4-5e6f-7890-abcd-ef0123456789

		changedProperty = IsHidden

	measure Total_Contractor_Visits =
			CALCULATE(
				[Total_Visits],
				'Fact_Visit'[ClientType] = "Contractor"
			)
		formatString: 0
		displayFolder: Visit Counts
		lineageTag: b2c3d4e5-6f7a-8901-bcde-f01234567890

		changedProperty = IsHidden

	measure Total_IHB_Visits =
			CALCULATE(
				[Total_Visits],
				'Fact_Visit'[ClientType] = "IHB"
			)
		formatString: 0
		displayFolder: Visit Counts
		lineageTag: d4e5f6a7-8b9c-0123-def0-123456789012

		changedProperty = IsHidden

	measure Total_Influencers_Visits =
			CALCULATE(
				[Total_Visits],
				'Fact_Visit'[ClientType] IN {"Engineer", "Contractor"}
			)
		formatString: 0
		displayFolder: Visit Counts
		lineageTag: e5f6a7b8-9c0d-1234-ef01-234567890123

		changedProperty = IsHidden

	measure Visited_Dealers =
			CALCULATE(
				DISTINCTCOUNT('Fact_Visit'[ClientKey]),
				'Fact_Visit'[ClientType] = "Dealer"
			)
		formatString: #,##0
		displayFolder: FRD Dashboard\Visited Counts
		lineageTag: frd-visited-dealers-001

		changedProperty = IsHidden

	measure Visited_Retailers =
			CALCULATE(
				DISTINCTCOUNT('Fact_Visit'[ClientKey]),
				'Fact_Visit'[ClientType] = "Retailer"
			)
		formatString: #,##0
		displayFolder: FRD Dashboard\Visited Counts
		lineageTag: frd-visited-retailers-002

		changedProperty = IsHidden

	measure Visited_Sites_IHB =
			CALCULATE(
				DISTINCTCOUNT('Fact_Visit'[ClientKey]),
				'Fact_Visit'[ClientType] IN {"Site", "IHB"}
			)
		formatString: #,##0
		displayFolder: FRD Dashboard\Visited Counts
		lineageTag: frd-visited-sites-ihb-003

		changedProperty = IsHidden

	measure Customer_Target = CALCULATE(SUM(Fact_Target[DailyTarget]), Fact_Target[EntityGroup] = "Customers")
		formatString: #,##0
		displayFolder: FRD Dashboard\Targets
		lineageTag: frd-customer-target-004

		changedProperty = IsHidden

	measure Customer_Total_Visited =
			// Customers = Dealers + Retailers (Channel Partners)
			CALCULATE(
				DISTINCTCOUNT('Fact_Visit'[ClientKey]),
				'Fact_Visit'[ClientType] IN {"Dealer", "Retailer"}
			)
		formatString: 0
		displayFolder: FRD Dashboard\Performance
		lineageTag: frd-customer-total-005

		changedProperty = IsHidden

	measure Customer_Achievement_Pct =
			VAR Target = [Customer_Target]
			VAR Actual = [Customer_Total_Visited]
			RETURN
			IF(Target = 0, BLANK(), DIVIDE(Actual, Target, 0))
		formatString: 0%
		displayFolder: FRD Dashboard\Performance
		lineageTag: frd-customer-ach-006

		changedProperty = IsHidden

	measure Influencer_Target = CALCULATE(SUM(Fact_Target[DailyTarget]), Fact_Target[EntityGroup] = "Influencers")
		formatString: #,##0
		displayFolder: FRD Dashboard\Targets
		lineageTag: frd-influencer-target-007

		changedProperty = IsHidden

	measure Influencer_Total_Visited =
			// Influencers = Engineers + Contractors (Technical Influencers)
			CALCULATE(
				DISTINCTCOUNT('Fact_Visit'[ClientKey]),
				'Fact_Visit'[ClientType] IN {"Engineer", "Contractor"}
			)
		formatString: 0
		displayFolder: FRD Dashboard\Performance
		lineageTag: frd-influencer-total-008

		changedProperty = IsHidden

	measure Influencer_Achievement_Pct =
			VAR Target = [Influencer_Target]
			VAR Actual = [Influencer_Total_Visited]
			RETURN
			IF(Target = 0, BLANK(), DIVIDE(Actual, Target, 0))
		formatString: 0%
		displayFolder: FRD Dashboard\Performance
		lineageTag: frd-influencer-ach-009

		changedProperty = IsHidden

	measure Total_Target = CALCULATE(SUM(Fact_Target[DailyTarget]), Fact_Target[EntityGroup] IN {"Customers", "Influencers"})
		formatString: #,##0
		displayFolder: FRD Dashboard\Targets
		lineageTag: frd-total-target-010

		changedProperty = IsHidden

	measure Total_Achievement_Pct = ```
			DIVIDE(
				[Customer_Total_Visited] + [Influencer_Total_Visited], 
				[Total_Target], 
				0
			)
			```
		formatString: 0%
		displayFolder: FRD Dashboard\Performance
		lineageTag: frd-total-ach-011

		changedProperty = IsHidden

	measure Sites_Visited_Count =
			// Consumers: Sites (Potential Construction Sites)
			CALCULATE(
				DISTINCTCOUNT('Fact_Visit'[ClientKey]),
				'Fact_Visit'[ClientType] = "Site"
			)
		formatString: 0
		displayFolder: FRD Dashboard\Consumer
		lineageTag: frd-sites-visited-012

		changedProperty = IsHidden

	measure IHB_Visited_Count =
			// Consumers: IHB (Individual House Builders)
			CALCULATE(
				DISTINCTCOUNT('Fact_Visit'[ClientKey]),
				'Fact_Visit'[ClientType] = "IHB"
			)
		formatString: 0
		displayFolder: FRD Dashboard\Consumer
		lineageTag: frd-ihb-visited-013

		changedProperty = IsHidden

	measure Visits_By_Zone =
			VAR HasTerritoryFilter =
				ISFILTERED('Dim_Territory'[territory_id])
					|| ISFILTERED('Dim_Territory'[mainZoneName])
					|| ISFILTERED('Dim_Territory'[mainRegionName])
					|| ISFILTERED('Dim_Territory'[mainTerritoryName])
					|| ISFILTERED('Dim_Territory'[AreaName])
			RETURN
				IF(
					HasTerritoryFilter,
					CALCULATE(
						[Total_Visits],
						TREATAS(VALUES('Dim_Territory'[territory_id]), 'Fact_Visit'[territory_id])
					),
					[Total_Visits]
				)
		formatString: #,##0
		displayFolder: Territory Analysis
		lineageTag: territory-visits-zone-001

		changedProperty = IsHidden

	measure Visits_By_Area =
			VAR HasTerritoryFilter =
				ISFILTERED('Dim_Territory'[territory_id])
					|| ISFILTERED('Dim_Territory'[mainZoneName])
					|| ISFILTERED('Dim_Territory'[mainRegionName])
					|| ISFILTERED('Dim_Territory'[mainTerritoryName])
					|| ISFILTERED('Dim_Territory'[AreaName])
			RETURN
				IF(
					HasTerritoryFilter,
					CALCULATE(
						[Total_Visits],
						TREATAS(VALUES('Dim_Territory'[territory_id]), 'Fact_Visit'[territory_id])
					),
					[Total_Visits]
				)
		formatString: #,##0
		displayFolder: Territory Analysis
		lineageTag: territory-visits-area-002

		changedProperty = IsHidden

	measure Territory_Visit_Coverage =
			VAR TotalTerritories =
				CALCULATE(
					DISTINCTCOUNT('Dim_Territory'[territory_id]),
					ALL('Dim_Territory')
				)
			VAR VisitedTerritories =
				CALCULATE(
					DISTINCTCOUNT('Fact_Visit'[territory_id]),
					'Fact_Visit'[HasTerritory] = 1
				)
			RETURN
				DIVIDE(VisitedTerritories, TotalTerritories, 0)
		formatString: 0.0%
		displayFolder: Territory Analysis
		lineageTag: territory-coverage-003

		changedProperty = IsHidden

	measure Zone_Name_Selected = SELECTEDVALUE('Dim_Territory'[mainZoneName], "All Zones")
		displayFolder: Territory Analysis\Labels
		lineageTag: territory-zone-label-004

		changedProperty = IsHidden

	measure Area_Name_Selected = SELECTEDVALUE('Dim_Territory'[AreaName], "All Areas")
		displayFolder: Territory Analysis\Labels
		lineageTag: territory-area-label-005

		changedProperty = IsHidden

	measure Territory_Name_Selected = SELECTEDVALUE('Dim_Territory'[mainTerritoryName], "All Territories")
		displayFolder: Territory Analysis\Labels
		lineageTag: territory-name-label-006

		changedProperty = IsHidden

	measure FRD_Target = DISTINCTCOUNT('Fact_Visit'[ClientKey])
		formatString: #,##0
		displayFolder: FRD Dashboard\Tertiary Sales
		lineageTag: frd-target-count-017

		changedProperty = IsHidden

	measure simple_target = SUM(Fact_Target[DailyTarget])
		formatString: 0
		lineageTag: 649c1c48-53f9-48de-b660-6f00a26e49c0

		changedProperty = IsHidden

	measure sim_ach = DIVIDE([Total_Visits], [simple_target],"N/A")
		lineageTag: 10de036b-8dae-4856-8d05-17381ce8483e

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Site + IHB Visits' =
			
			CALCULATE (
			    [Total_Visits],
			    'Fact_Visit'[ClientType] IN { "Site", "IHB" }
			)
		formatString: 0
		displayFolder: Visit Counts
		lineageTag: ab809b21-5472-4387-b2ce-d385d8db2027

		changedProperty = IsHidden

	measure TT_Dealer_Visits =
			
			IF( SELECTEDVALUE( Dim_EntityGroup[EntityGroup] ) = "Customers", [Total_Dealer_Visits], BLANK() )
		formatString: 0
		lineageTag: a72031f4-f2bb-4934-a452-12995e065622

		changedProperty = IsHidden

	measure TT_Retailer_Visits =
			
			IF( SELECTEDVALUE( Dim_EntityGroup[EntityGroup] ) = "Customers", [Total_Retailer_Visits], BLANK() )
		formatString: 0
		lineageTag: a9331727-fd3c-46d2-a035-6e968831dc47

		changedProperty = IsHidden

	measure TT_IHB_Visits =
			
			IF( SELECTEDVALUE( Dim_EntityGroup[EntityGroup] ) = "Consumers", [Total_IHB_Visits], BLANK() )
		formatString: 0
		lineageTag: d3c138eb-cd26-4637-8e58-da3a0f1e22a6

		changedProperty = IsHidden

	measure 'Unique Employees With Visits' = DISTINCTCOUNT('Fact_Visit'[EmployeeID])
		formatString: 0
		lineageTag: 225a035a-e599-4c04-a7fd-fedf4d9d6a8b

		changedProperty = IsHidden

	measure Visit_to_Client_Ratio =
			// Ratio of visits to unique clients - should be > 1 if repeat visits exist
			VAR _Visits = COUNTROWS('Fact_Visit')
			VAR _Clients = DISTINCTCOUNTNOBLANK('Fact_Visit'[ClientKey])
			RETURN DIVIDE(_Visits, _Clients, BLANK())
		formatString: 0.00
		displayFolder: Ratios\Productivity
		lineageTag: 41ff7a28-79bc-42ed-ac44-9978b0547bba

		changedProperty = IsHidden

	measure _DEBUG_Visit_vs_Client =
			// Debug: Shows visit count vs client count side by side
			VAR _Visits = COUNTROWS('Fact_Visit')
			VAR _Clients = DISTINCTCOUNTNOBLANK('Fact_Visit'[ClientKey])
			RETURN
				"Visits: " & FORMAT(_Visits, "#,##0") &
				" | Clients: " & FORMAT(_Clients, "#,##0") &
				" | Ratio: " & FORMAT(DIVIDE(_Visits, _Clients), "0.00")
		displayFolder: _Debug
		lineageTag: 52aa8b39-8acd-53fe-bd55-aa89c1658ccb

		changedProperty = IsHidden

	column VisitID
		dataType: int64
		formatString: 0
		lineageTag: b0de3cfc-46f7-497b-a6be-4687f8f16deb
		summarizeBy: count
		sourceColumn: VisitID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: dateTime
		formatString: Long Date
		lineageTag: 072c2531-4ca1-482c-9013-186853e98d95
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EmployeeID
		dataType: int64
		formatString: 0
		lineageTag: ebe2fbff-df71-4ba9-8959-aacb4ae544f5
		summarizeBy: none
		sourceColumn: EmployeeID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EmployeeName
		dataType: string
		lineageTag: 02e02cd3-5877-48af-b2af-0a498d169001
		summarizeBy: none
		sourceColumn: EmployeeName

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RoleLevel
		dataType: int64
		formatString: 0
		lineageTag: 1765b72a-1d08-4220-8ce0-7e66db466411
		summarizeBy: sum
		sourceColumn: RoleLevel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientKey
		dataType: string
		lineageTag: 9d18c8ac-c77f-4d24-b6e5-3651527aa443
		summarizeBy: none
		sourceColumn: ClientKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientType
		dataType: string
		lineageTag: 66689d2b-c845-400e-99f1-7debb4cedff7
		summarizeBy: none
		sourceColumn: ClientType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientID
		dataType: int64
		formatString: 0
		lineageTag: 39af79e3-decb-4a38-bafe-b7558e40be08
		summarizeBy: count
		sourceColumn: ClientID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ResponsibleRole
		dataType: string
		lineageTag: 05455d21-d73e-4d31-b6b6-f2c656cc787e
		summarizeBy: none
		sourceColumn: ResponsibleRole

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column visit_type
		dataType: string
		lineageTag: f096ca87-88eb-4825-a3cb-cd483bc02d44
		summarizeBy: none
		sourceColumn: visit_type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column VisitCategoryID
		dataType: int64
		formatString: 0
		lineageTag: 62d47ec7-f58c-4472-a939-bd1e6485b553
		summarizeBy: none
		sourceColumn: VisitCategoryID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column VisitPhaseID
		dataType: int64
		formatString: 0
		lineageTag: 38120914-2534-4578-86bf-f60cc971db1d
		summarizeBy: count
		sourceColumn: VisitPhaseID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column VisitStageID
		dataType: int64
		formatString: 0
		lineageTag: 130690e0-b967-48f9-b8f1-e1e58f4e42cb
		summarizeBy: none
		sourceColumn: VisitStageID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column organization_id
		dataType: int64
		formatString: 0
		lineageTag: 53f429e7-23bb-40cc-a22f-d4c956fc11e1
		summarizeBy: sum
		sourceColumn: organization_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 9bce3478-d606-49c7-81e0-ca1db3d963e9
		summarizeBy: none
		sourceColumn: status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column feedback
		dataType: string
		lineageTag: 73a0cd4c-1110-4464-ab0d-5eb8172167e1
		summarizeBy: none
		sourceColumn: feedback

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column visit_photo
		dataType: string
		lineageTag: 2de23af7-bd54-4d48-bf34-02db028bb43b
		summarizeBy: none
		sourceColumn: visit_photo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_photo
		dataType: string
		lineageTag: 7ae15910-c31e-4ac4-a5cd-8f9e8994638c
		summarizeBy: none
		sourceColumn: product_photo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column delete_status
		dataType: string
		lineageTag: 48a49dcc-c249-42af-afe2-04b667df6df8
		summarizeBy: none
		sourceColumn: delete_status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HasPhoto
		dataType: int64
		formatString: 0
		lineageTag: 8b20320f-e823-4238-a6c3-cb755bb26f76
		summarizeBy: sum
		sourceColumn: HasPhoto

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HasProductPhoto
		dataType: int64
		formatString: 0
		lineageTag: a2943f65-bd16-41e3-accc-5b05923fec37
		summarizeBy: sum
		sourceColumn: HasProductPhoto

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HasFeedback
		dataType: int64
		formatString: 0
		lineageTag: 81462918-5e40-48a7-ab6a-cc7689435f72
		summarizeBy: sum
		sourceColumn: HasFeedback

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HasTerritory
		dataType: int64
		formatString: 0
		lineageTag: ed35709f-beb4-4b9f-ae9a-ae56b6260758
		summarizeBy: sum
		sourceColumn: HasTerritory

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column territory_id
		dataType: int64
		formatString: 0
		lineageTag: 0ec2e29b-23a6-4b38-a6db-7d11bc622979
		summarizeBy: sum
		sourceColumn: territory_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column territory_name
		dataType: string
		lineageTag: 17a78ca3-d95e-4965-a6a1-f74f66154cc2
		summarizeBy: none
		sourceColumn: territory_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column followup_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3817b15f-6bd0-4262-a13a-d89038a51d61
		summarizeBy: none
		sourceColumn: followup_date

		variation Variation
			isDefault
			relationship: d322477c-f6bb-49f4-8ffd-65f4e8870f6e
			defaultHierarchy: LocalDateTable_0c1b9b1e-09f6-47cf-9ce2-dfa4e70f444c.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column origin
		dataType: string
		lineageTag: 5d0ddd02-2778-4dd6-997c-18508974a8d8
		summarizeBy: none
		sourceColumn: origin

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column visit_date_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 338fd740-99fb-4810-8e40-6189d35df066
		summarizeBy: none
		sourceColumn: visit_date_time

		variation Variation
			isDefault
			relationship: 8ef61087-ebdc-47de-ab2c-ccf5b5180fea
			defaultHierarchy: LocalDateTable_38e5fb92-626c-4346-9bcf-ee3e387d6c94.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 56e124ad-339d-4760-8351-6dd54084044c
		summarizeBy: none
		sourceColumn: created_at

		variation Variation
			isDefault
			relationship: fc77fe3f-f42d-4492-b918-46154e773c3b
			defaultHierarchy: LocalDateTable_c06d925f-c97e-4691-8afb-e389824b9822.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 833797d2-9dee-4d6f-9dfc-ff14387a0820
		summarizeBy: none
		sourceColumn: updated_at

		variation Variation
			isDefault
			relationship: e1b97801-32fc-4887-8efd-4248f38f0c89
			defaultHierarchy: LocalDateTable_c0b96bb2-3e42-43ae-bb49-4ba396c907cb.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: c3d4e5f6-7890-abcd-ef12-345678901234
		summarizeBy: sum
		sourceColumn: latitude

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: d4e5f678-90ab-cdef-1234-567890123456
		summarizeBy: sum
		sourceColumn: longitude

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CompanyCode
		dataType: string
		lineageTag: 7e8f9012-3456-7890-abcd-567890123456
		summarizeBy: none
		sourceColumn: CompanyCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Fact_Visit = m
		mode: import
		source = ```
				// ============================================================
				// Fact_Visit - Visit Fact Table
				// Based on actual 'public visits' table schema from Power BI
				// Total Records: 36,041 visits
				// 
				// INFLUENCER SEGREGATION (per PRD.MD):
				// - "Influencer" visits are actually Engineers (managed by BDO)
				// - Contractor visits use contractor_id (managed by CRO)
				// ============================================================
				
				let
				    // Reference the existing 'public visits' table in Power BI
				    // This connects to the semantic model's existing data source
				    Source = #"public visits",
				    
				    // ---- Select Core Columns from actual schema ----
				    SelectedColumns = Table.SelectColumns(Source, {
				        "id", "visit_type", "created_by_id", "create_by_name", "visit_date_time", 
				        "feedback", "visit_photo", "product_photo", "visit_category_id",
				        "visit_phase_id", "visit_stage_id", "status", "followup_date",
				        // Client ID columns (one populated based on visit_type)
				        "potential_site_id", "retailer_id", "dealer_id", 
				        "engineer_id", "contractor_id", "ihb_registration_id", "head_mason_id",
				        "site_manager_id", "organization_id",
				        // Territory info
				        "territory_id", "territory_name", "role_level",
				        // GPS Coordinates
				        "latitude", "longitude",
				        // Metadata
				        "origin", "delete_status", "created_at", "updated_at"
				    }),
				    
				    // ---- Create Unified ClientKey ----
				    // Maps the appropriate ID column based on visit_type
				    // Visit Types: Sites (13,235), Influencer (7,114), Dealer (5,587), 
				    //              Retailer (4,020), IHB (3,807), General Sites (2,278)
				    // 
				    // INFLUENCER SEGREGATION (per PRD):
				    // - Influencer visits with engineer_id → "Engineer" (BDO manages)
				    // - Influencer visits with contractor_id → "Contractor" (CRO manages Partners)
				    WithClientType = Table.AddColumn(SelectedColumns, "ClientType", each 
				        if [visit_type] = "Sites" then "Site"
				        else if [visit_type] = "Retailer" then "Retailer"
				        else if [visit_type] = "Dealer" then "Dealer"
				        else if [visit_type] = "Influencer" then 
				            // INFLUENCER SEGREGATION: Check which ID is populated
				            if [engineer_id] <> null then "Engineer"       // BDO manages Engineers
				            else if [contractor_id] <> null then "Contractor"  // CRO manages Partners/Contractors
				            else "Influencer"  // Fallback for uncategorized Influencers
				        else if [visit_type] = "IHB" then "IHB"
				        else if [visit_type] = "General Sites" then "General"
				        else "Unknown", 
				        type text
				    ),
				    
				    // Use ClientType directly (no need for secondary check)
				    WithContractorCheck = Table.AddColumn(WithClientType, "ClientType_Final", each 
				        [ClientType],
				        type text
				    ),
				    
				    // Extract the appropriate client ID based on visit type
				    WithClientID = Table.AddColumn(WithContractorCheck, "ClientID", each 
				        if [ClientType_Final] = "Site" then [potential_site_id]
				        else if [ClientType_Final] = "Retailer" then [retailer_id]
				        else if [ClientType_Final] = "Dealer" then [dealer_id]
				        else if [ClientType_Final] = "Engineer" then [engineer_id]  // Engineers managed by BDO
				        else if [ClientType_Final] = "Contractor" then [contractor_id]  // Contractors/Partners managed by CRO
				        else if [ClientType_Final] = "IHB" then [ihb_registration_id]
				        else null,
				        Int64.Type
				    ),
				    
				    // Add Responsible Role based on client type (for filtering/RLS)
				    WithResponsibleRole = Table.AddColumn(WithClientID, "ResponsibleRole", each 
				        if [ClientType_Final] = "Site" then "BDO"
				        else if [ClientType_Final] = "Engineer" then "BDO"
				        else if [ClientType_Final] = "Contractor" then "CRO"
				        else if [ClientType_Final] = "Retailer" then "SR"
				        else if [ClientType_Final] = "Dealer" then "CRO"
				        else if [ClientType_Final] = "IHB" then "CRO,BDO"
				        else "All",
				        type text
				    ),
				    
				    // Create composite ClientKey to match Dim_Client
				    WithClientKey = Table.AddColumn(WithResponsibleRole, "ClientKey", each 
				        if [ClientID] <> null then [ClientType_Final] & "-" & Text.From([ClientID])
				        else null,
				        type text
				    ),
				    
				    // Remove the intermediate ClientType column, use ClientType_Final
				    RemovedIntermediate = Table.RemoveColumns(WithClientKey, {"ClientType"}),
				    RenamedClientType = Table.RenameColumns(RemovedIntermediate, {{"ClientType_Final", "ClientType"}}),
				    
				    // ---- Add Quality Metrics ----
				    // Photo Compliance (1 if visit_photo exists, 0 otherwise)
				    WithPhotoFlag = Table.AddColumn(RenamedClientType, "HasPhoto", each 
				        if [visit_photo] <> null and [visit_photo] <> "" then 1 else 0,
				        Int64.Type
				    ),
				    
				    // Product Photo Captured
				    WithProductPhotoFlag = Table.AddColumn(WithPhotoFlag, "HasProductPhoto", each 
				        if [product_photo] <> null and [product_photo] <> "" then 1 else 0,
				        Int64.Type
				    ),
				    
				    // Feedback Provided (1 if feedback exists, 0 otherwise)
				    WithFeedbackFlag = Table.AddColumn(WithProductPhotoFlag, "HasFeedback", each 
				        if [feedback] <> null and [feedback] <> "" then 1 else 0,
				        Int64.Type
				    ),
				    
				    // Territory Captured (1 if territory_id exists, 0 otherwise)
				    WithTerritoryFlag = Table.AddColumn(WithFeedbackFlag, "HasTerritory", each 
				        if [territory_id] <> null then 1 else 0,
				        Int64.Type
				    ),
				    
				    // ---- FR-16-18: Add Company Code (ACL/AIL) ----
				    // Maps organization_id to company codes for filtering
				    WithCompanyCode = Table.AddColumn(WithTerritoryFlag, "CompanyCode", each 
				        if [organization_id] = 1 then "ACL"
				        else if [organization_id] = 2 then "AIL"
				        else "Unknown",
				        type text
				    ),
				    
				    // ---- Extract Date Key for Dim_Date join ----
				    WithDateKey = Table.AddColumn(WithCompanyCode, "DateKey", each 
				        Date.From([visit_date_time]),
				        type date
				    ),
				    
				    // ---- Rename ID column ----
				    RenamedColumns = Table.RenameColumns(WithDateKey, {
				        {"id", "VisitID"},
				        {"created_by_id", "EmployeeID"},
				        {"create_by_name", "EmployeeName"},
				        {"visit_category_id", "VisitCategoryID"},
				        {"visit_phase_id", "VisitPhaseID"},
				        {"visit_stage_id", "VisitStageID"},
				        {"role_level", "RoleLevel"}
				    }),
				    
				    // ---- Remove individual client ID columns (now unified) ----
				    CleanedColumns = Table.RemoveColumns(RenamedColumns, {
				        "potential_site_id", "retailer_id", "dealer_id", 
				        "engineer_id", "contractor_id", "ihb_registration_id", 
				        "head_mason_id", "site_manager_id"
				    }),
				    
				    // ---- Filter out deleted records ----
				    ActiveRecords = Table.SelectRows(CleanedColumns, each [delete_status] = "NO"),
				    
				    // ---- Reorder Columns ----
				    ReorderedColumns = Table.ReorderColumns(ActiveRecords, {
				        "VisitID", "DateKey", "EmployeeID", "EmployeeName", "RoleLevel",
				        "ClientKey", "ClientType", "ClientID", "ResponsibleRole", "visit_type", 
				        "VisitCategoryID", "VisitPhaseID", "VisitStageID", "organization_id", "CompanyCode", "status",
				        "feedback", "visit_photo", "product_photo",
				        "HasPhoto", "HasProductPhoto", "HasFeedback", "HasTerritory",
				        "territory_id", "territory_name", "latitude", "longitude", "followup_date",
				        "origin", "visit_date_time", "created_at", "updated_at"
				    }),
				    
				    // ---- Set Data Types ----
				    TypedTable = Table.TransformColumnTypes(ReorderedColumns, {
				        {"VisitID", Int64.Type},
				        {"DateKey", type date},
				        {"EmployeeID", Int64.Type},
				        {"EmployeeName", type text},
				        {"RoleLevel", Int64.Type},
				        {"ClientKey", type text},
				        {"ClientType", type text},
				        {"ClientID", Int64.Type},
				        {"ResponsibleRole", type text},
				        {"visit_type", type text},
				        {"VisitCategoryID", Int64.Type},
				        {"VisitPhaseID", Int64.Type},
				        {"VisitStageID", Int64.Type},
				        {"organization_id", Int64.Type},
				        {"CompanyCode", type text},
				        {"status", type text},
				        {"feedback", type text},
				        {"visit_photo", type text},
				        {"product_photo", type text},
				        {"HasPhoto", Int64.Type},
				        {"HasProductPhoto", Int64.Type},
				        {"HasFeedback", Int64.Type},
				        {"HasTerritory", Int64.Type},
				        {"territory_id", Int64.Type},
				        {"territory_name", type text},
				        {"latitude", type number},
				        {"longitude", type number},
				        {"followup_date", type datetime},
				        {"origin", type text},
				        {"visit_date_time", type datetime},
				        {"created_at", type datetime},
				        {"updated_at", type datetime}
				    })
				in
				    TypedTable
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

