table Fact_Order
	lineageTag: 2fa8efb5-1fd1-4ed4-a564-8e1e3c2f06c7

	measure Total_Orders = DISTINCTCOUNT('Fact_Order'[OrderID])
		formatString: #,##0
		displayFolder: Orders\Base
		lineageTag: 5a5ed38d-4f5a-44a7-9c7a-8a7a7a3d6b35

		changedProperty = IsHidden

	measure Total_Order_Amount = SUM('Fact_Order'[TotalAmount])
		formatString: #,##0.00
		displayFolder: Orders\Base
		lineageTag: 15df1a60-6a52-4d5b-8ca1-5a3b1a4e1e3a

		changedProperty = IsHidden

	measure Total_Order_Quantity = SUM('Fact_Order'[TotalQuantity])
		formatString: #,##0.00
		displayFolder: Orders\Base
		lineageTag: 8a2d1c7a-8a3a-4da2-9aa1-1f0b3f66c81a

		changedProperty = IsHidden

	measure Total_Order_Quantity_MT = SUM('Fact_Order'[qty_in_mt])
		formatString: #,##0.00
		displayFolder: Orders\Base
		lineageTag: 3f6a2d61-6b0e-4c2d-9d68-2b27e1f8a4c2

		changedProperty = IsHidden

	measure Average_Order_Value = DIVIDE([Total_Order_Amount], [Total_Orders], 0)
		formatString: #,##0.00
		displayFolder: Orders\Rates
		lineageTag: b7d8d0a5-f5e0-4c9a-9b5a-40f38a1f8f35

		changedProperty = IsHidden

	measure Average_Items_Per_Order = DIVIDE(SUM('Fact_Order'[OrderItemCount]), [Total_Orders], 0)
		formatString: #,##0.00
		displayFolder: Orders\Rates
		lineageTag: 2b5c19f0-49df-4b63-9f5c-9f2c7b5d87b1

		changedProperty = IsHidden

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: 1d9902a5-2b63-4c0a-9f38-1c27998a69b0
		summarizeBy: count
		sourceColumn: OrderID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: dateTime
		formatString: Long Date
		lineageTag: d2b0cc2d-6f49-41fb-9c52-9dcebb26cb7a
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column UserID
		dataType: int64
		formatString: 0
		lineageTag: 5b72c6ac-8a90-4c59-87b5-6c7b9c0e2de7
		summarizeBy: none
		sourceColumn: UserID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientKey
		dataType: string
		lineageTag: 7659b460-94ee-4a0f-bb3a-3e8d2f4e9db5
		summarizeBy: none
		sourceColumn: ClientKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientType
		dataType: string
		lineageTag: f0a0d6f6-20a4-49e3-a1c2-7d4f48a91b3e
		summarizeBy: none
		sourceColumn: ClientType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientID
		dataType: int64
		formatString: 0
		lineageTag: a8f4b0c2-3b01-4e1a-8c3f-3d8f6a0f0b8f
		summarizeBy: count
		sourceColumn: ClientID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderStatus
		dataType: string
		lineageTag: 248f4c2b-f2d0-45f4-9a3a-8ad11e9f0c92
		summarizeBy: none
		sourceColumn: OrderStatus

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DeliveryMethod
		dataType: string
		lineageTag: 6b0f196d-ffb3-4d38-ae3a-99cf2c3de4c7
		summarizeBy: none
		sourceColumn: DeliveryMethod

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrganizationID
		dataType: int64
		formatString: 0
		lineageTag: 5b19b0e6-47c5-42de-a9f2-bc8f9af3bb55
		summarizeBy: count
		sourceColumn: OrganizationID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CompanyCode
		dataType: string
		lineageTag: 90fb5c13-3ff6-4f98-87aa-345cd15e0b07
		summarizeBy: none
		sourceColumn: CompanyCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TotalAmount
		dataType: double
		lineageTag: 7fd2e0f6-3a55-4c0d-b9e8-7a11f8f5db64
		summarizeBy: sum
		sourceColumn: TotalAmount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalQuantity
		dataType: double
		lineageTag: b86f4c63-1c64-4f97-8d0b-1d0e9e2c7d9c
		summarizeBy: sum
		sourceColumn: TotalQuantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column qty_in_mt
		dataType: double
		lineageTag: 5c7e7c60-5e3c-4c77-8d16-2a7e7ac2d4b0
		summarizeBy: sum
		sourceColumn: qty_in_mt

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderItemCount
		dataType: int64
		formatString: 0
		lineageTag: 0c9f2a30-0788-4b8a-a4b5-9a6e3cc6be9c
		summarizeBy: sum
		sourceColumn: OrderItemCount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DistinctSKUCount
		dataType: int64
		formatString: 0
		lineageTag: 5ed9c34c-7c43-4e7d-bf19-d3e9d7f92c7a
		summarizeBy: sum
		sourceColumn: DistinctSKUCount

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 98b8f0e3-4d1e-4b69-8d23-4a45b7f7a3a2
		summarizeBy: none
		sourceColumn: created_at

		variation Variation
			isDefault
			relationship: b04ed4a0-e160-4623-b2d0-b5e4194475fa
			defaultHierarchy: LocalDateTable_245b3042-013f-4f31-8a34-c992d61a1092.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 7cb4bb7f-cb5a-4c11-9f1d-9bd32ce7c6aa
		summarizeBy: none
		sourceColumn: updated_at

		variation Variation
			isDefault
			relationship: 505135e6-79bd-491d-8c61-9d9a9050f824
			defaultHierarchy: LocalDateTable_71e7d8b1-5b94-483a-99f6-c8e4c3712267.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Fact_Order = m
		mode: import
		source = ```
				// ============================================================
				// Fact_Order - Order Fact Table (Order Header Grain)
				//
				// New rule:
				// - public order_items is the source of truth for order line details
				// - header attributes are sourced from public orders (fallback: public user_orders)
				// ============================================================
				
				let
				    OrdersRaw = try #"public orders" otherwise #"public user_orders",
				    ItemsRaw = #"public order_items",
				
				    OrdersCols = Table.ColumnNames(OrdersRaw),
				
				    // Safe conversion helpers
				    AsInt64 = (v as any) as nullable number => try Int64.From(v) otherwise null,
				    AsDateTime = (v as any) as nullable datetime => try DateTime.From(v) otherwise null,
				    AsNumber = (v as any) as nullable number =>
				        let
				            n = try Number.From(v) otherwise null,
				            s = if n <> null then null else try Text.From(v) otherwise null,
				            cleaned = if s = null then null else Text.Select(s, {"0".."9", ".", "-"}),
				            t = if n <> null then n else try Number.FromText(cleaned) otherwise null
				        in
				            t,
				
				    // -------------------------
				    // ORDERS (header)
				    // -------------------------
				    OrdersSelected = Table.SelectColumns(
				        OrdersRaw,
				        {
				            "id", "order_id", "corteza_record_ref", "user_order_history_id",
				            "created_at", "updated_at",
				            "dn_number",
				            "delete_status",
				            "delivery_method",
				            "order_status",
				            "order_category",
				            "order_type",
				            "stage",
				            "organization_id", "organizations_id",
				            "bazaar_id", "dealer_id", "site_id", "retailer_id",
				            "project_conversion_id",
				            "created_by", "created_by_id", "updated_by", "updated_by_id", "user_id", "users_id",
				            "total_amount", "total_quantity"
				        },
				        MissingField.UseNull
				    ),
				
				    OrdersFiltered = if List.Contains(OrdersCols, "delete_status")
				        then
				            Table.SelectRows(
				                OrdersSelected,
				                each
				                    let
				                        ds = if [delete_status] = null then "NO" else try Text.Upper(Text.From([delete_status])) otherwise "NO"
				                    in
				                        ds = "NO" or ds = "N" or ds = "0" or ds = "FALSE"
				            )
				        else OrdersSelected,
				
				    WithOrderID = Table.AddColumn(
				        OrdersFiltered,
				        "OrderID",
				        each
				            let
				                id = AsInt64(Record.FieldOrDefault(_, "id", null)),
				                oid = AsInt64(Record.FieldOrDefault(_, "order_id", null)),
				                uoh = AsInt64(Record.FieldOrDefault(_, "user_order_history_id", null)),
				                cr = AsInt64(Record.FieldOrDefault(_, "corteza_record_ref", null))
				            in
				                if id <> null then id else if oid <> null then oid else if uoh <> null then uoh else cr,
				        Int64.Type
				    ),
				
				    OrdersNonNull = Table.SelectRows(WithOrderID, each [OrderID] <> null),
				
				    WithOrderDateTime = Table.AddColumn(
				        OrdersNonNull,
				        "OrderDateTime",
				        each
				            let
				                d1 = AsDateTime([created_at]),
				                d2 = AsDateTime([updated_at])
				            in
				                if d1 <> null then d1 else d2,
				        type datetime
				    ),
				
				    WithDateKey = Table.AddColumn(
				        WithOrderDateTime,
				        "DateKey",
				        each try Date.From([OrderDateTime]) otherwise null,
				        type date
				    ),
				
				    WithUserID = Table.AddColumn(
				        WithDateKey,
				        "UserID",
				        each
				            let
				                u1 = AsInt64(Record.FieldOrDefault(_, "created_by", null)),
				                u1b = AsInt64(Record.FieldOrDefault(_, "created_by_id", null)),
				                u2 = AsInt64(Record.FieldOrDefault(_, "updated_by", null)),
				                u2b = AsInt64(Record.FieldOrDefault(_, "updated_by_id", null)),
				                u3 = AsInt64(Record.FieldOrDefault(_, "user_id", null)),
				                u4 = AsInt64(Record.FieldOrDefault(_, "users_id", null))
				            in
				                if u1 <> null then u1
				                else if u1b <> null then u1b
				                else if u3 <> null then u3
				                else if u2 <> null then u2
				                else if u2b <> null then u2b
				                else u4,
				        Int64.Type
				    ),
				
				    WithClientType = Table.AddColumn(
				        WithUserID,
				        "ClientType",
				        each
				            let
				                oc = if [order_category] <> null then Text.Upper(Text.From([order_category])) else null,
				                hasSite = [site_id] <> null,
				                hasRetailer = [retailer_id] <> null,
				                hasDealer = [dealer_id] <> null,
				                hasBazaar = [bazaar_id] <> null
				            in
				                if oc <> null and Text.Contains(oc, "SITE") and hasSite then "Site"
				                else if oc = "RETAILER" and hasRetailer then "Retailer"
				                else if oc = "DEALER" and hasDealer then "Dealer"
				                else if oc = "BAZAAR" and hasBazaar then "Bazaar"
				                else if hasSite then "Site"
				                else if hasRetailer then "Retailer"
				                else if hasDealer then "Dealer"
				                else if hasBazaar then "Bazaar"
				                else null,
				        type text
				    ),
				
				    WithClientID = Table.AddColumn(
				        WithClientType,
				        "ClientID",
				        each
				            let
				                oc = if [order_category] <> null then Text.Upper(Text.From([order_category])) else null,
				                hasSite = [site_id] <> null,
				                hasRetailer = [retailer_id] <> null,
				                hasDealer = [dealer_id] <> null,
				                hasBazaar = [bazaar_id] <> null
				            in
				                if oc <> null and Text.Contains(oc, "SITE") and hasSite then AsInt64([site_id])
				                else if oc = "RETAILER" and hasRetailer then AsInt64([retailer_id])
				                else if oc = "DEALER" and hasDealer then AsInt64([dealer_id])
				                else if oc = "BAZAAR" and hasBazaar then AsInt64([bazaar_id])
				                else if hasSite then AsInt64([site_id])
				                else if hasRetailer then AsInt64([retailer_id])
				                else if hasDealer then AsInt64([dealer_id])
				                else if hasBazaar then AsInt64([bazaar_id])
				                else null,
				        Int64.Type
				    ),
				
				    WithClientKey = Table.AddColumn(
				        WithClientID,
				        "ClientKey",
				        each if [ClientType] <> null and [ClientID] <> null then [ClientType] & "-" & Text.From([ClientID]) else null,
				        type text
				    ),
				
				    WithOrganizationID = Table.AddColumn(
				        WithClientKey,
				        "OrganizationID",
				        each
				            let
				                o1 = AsInt64([organization_id]),
				                o2 = AsInt64([organizations_id])
				            in
				                if o1 <> null then o1 else o2,
				        Int64.Type
				    ),
				
				    WithCompanyCode = Table.AddColumn(
				        WithOrganizationID,
				        "CompanyCode",
				        each
				            let
				                org = [OrganizationID],
				                dn = if [dn_number] <> null then try Text.Upper(Text.From([dn_number])) otherwise null else null
				            in
				                if org = 1 then "ACL"
				                else if org = 2 then "AIL"
				                else if dn <> null and Text.Contains(dn, "-AIL") then "AIL"
				                else if dn <> null and Text.Contains(dn, "-ACL") then "ACL"
				                else "Unknown",
				        type text
				    ),
				
				    WithOrderStatus = Table.AddColumn(
				        WithCompanyCode,
				        "OrderStatus",
				        each if [order_status] <> null then Text.From([order_status]) else null,
				        type text
				    ),
				
				    WithDeliveryMethod = Table.AddColumn(
				        WithOrderStatus,
				        "DeliveryMethod",
				        each if [delivery_method] <> null then Text.From([delivery_method]) else null,
				        type text
				    ),
				
				    // -------------------------
				    // ORDER ITEMS (aggregate to header)
				    // -------------------------
				    ItemsSelected = Table.SelectColumns(
				        ItemsRaw,
				        {
				            "id",
				            "user_order_history_id",
				            "corteza_record_ref",
				            "qty",
				            "unit_type",
				            "balance",
				            "unit_price",
				            "sku",
				            "sku_name",
				            "sku_info_id"
				        },
				        MissingField.UseNull
				    ),
				
				    WithItemQuantity = Table.AddColumn(
				        ItemsSelected,
				        "ItemQuantity",
				        each AsNumber([qty]),
				        type number
				    ),
				
				    WithItemUnit = Table.AddColumn(
				        WithItemQuantity,
				        "ItemUnit",
				        each if [unit_type] <> null then try Text.Lower(Text.From([unit_type])) otherwise null else null,
				        type text
				    ),
				
				    WithItemQtyInMT = Table.AddColumn(
				        WithItemUnit,
				        "ItemQtyInMT",
				        each
				            let
				                u = [ItemUnit],
				                isBag = if u = null then false else Text.Contains(u, "bag"),
				                q = [ItemQuantity]
				            in
				                if q = null then null else if isBag then q / 20 else q,
				        type number
				    ),
				
				    WithItemAmount = Table.AddColumn(
				        WithItemQtyInMT,
				        "ItemAmount",
				        each
				            let
				                b = AsNumber([balance]),
				                up = AsNumber([unit_price]),
				                q = [ItemQuantity]
				            in
				                if b <> null then b else if up <> null and q <> null then up * q else null,
				        type number
				    ),
				
				    WithOrderJoinKey = Table.AddColumn(
				        WithItemAmount,
				        "OrderJoinKey",
				        each
				            let
				                a = AsInt64([user_order_history_id]),
				                b = AsInt64([corteza_record_ref])
				            in
				                if a <> null then a else b,
				        Int64.Type
				    ),
				
				    WithSKUKey = Table.AddColumn(
				        WithOrderJoinKey,
				        "SKUKey",
				        each
				            let
				                s1 = AsInt64([sku_info_id]),
				                s2 = AsInt64([sku]),
				                s3 = if [sku_name] <> null then try Text.From([sku_name]) otherwise null else null
				            in
				                if s1 <> null then Text.From(s1) else if s2 <> null then Text.From(s2) else s3,
				        type text
				    ),
				
				    ItemsForAgg = Table.SelectRows(WithSKUKey, each [OrderJoinKey] <> null),
				
				    LineAgg = Table.Group(
				        ItemsForAgg,
				        {"OrderJoinKey"},
				        {
				            {"OrderItemCount", each Table.RowCount(_), Int64.Type},
				            {"OrderQuantity_Items", each List.Sum(List.RemoveNulls([ItemQuantity])), type number},
				            {"OrderAmount_Items", each List.Sum(List.RemoveNulls([ItemAmount])), type number},
				            {"DistinctSKUCount", each List.NonNullCount(List.Distinct(List.RemoveNulls([SKUKey]))), Int64.Type},
				            {"qty_in_mt_items", each List.Sum(List.RemoveNulls([ItemQtyInMT])), type number}
				        }
				    ),
				
				    // -------------------------
				    // MERGE LINE AGG INTO ORDERS
				    // -------------------------
				    OrdersSorted = Table.Sort(WithDeliveryMethod, {{"OrderDateTime", Order.Descending}}),
				    OrdersDeduped = Table.Distinct(OrdersSorted, {"OrderID"}),
				
				    Merged = Table.NestedJoin(OrdersDeduped, {"OrderID"}, LineAgg, {"OrderJoinKey"}, "ItemsAgg", JoinKind.LeftOuter),
				    Expanded = Table.ExpandTableColumn(Merged, "ItemsAgg", {"OrderItemCount", "OrderQuantity_Items", "OrderAmount_Items", "DistinctSKUCount", "qty_in_mt_items"}, {"OrderItemCount", "OrderQuantity_Items", "OrderAmount_Items", "DistinctSKUCount", "qty_in_mt_items"}),
				
				    WithTotalAmount = Table.AddColumn(
				        Expanded,
				        "TotalAmount",
				        each
				            let
				                a = AsNumber([total_amount]),
				                ai = AsNumber([OrderAmount_Items])
				            in
				                if ai <> null then ai else if a <> null then a else 0,
				        type number
				    ),
				
				    WithTotalQuantity = Table.AddColumn(
				        WithTotalAmount,
				        "TotalQuantity",
				        each
				            let
				                q = AsNumber([total_quantity]),
				                qi = AsNumber([OrderQuantity_Items])
				            in
				                if qi <> null then qi else if q <> null then q else 0,
				        type number
				    ),
				
				    WithQtyInMT = Table.AddColumn(
				        WithTotalQuantity,
				        "qty_in_mt",
				        each
				            let
				                qim = AsNumber([qty_in_mt_items]),
				                tq = AsNumber([TotalQuantity])
				            in
				                if qim <> null then qim else tq,
				        type number
				    ),
				
				    // Ensure counts are 0 instead of null for orders without items
				    CountsFilled = Table.TransformColumns(
				        WithQtyInMT,
				        {
				            {"OrderItemCount", each if _ = null then 0 else _, Int64.Type},
				            {"DistinctSKUCount", each if _ = null then 0 else _, Int64.Type}
				        }
				    ),
				
				    FinalSelected = Table.SelectColumns(
				        CountsFilled,
				        {
				            "OrderID", "DateKey", "UserID", "ClientKey", "ClientType", "ClientID",
				            "OrderStatus", "DeliveryMethod", "OrganizationID", "CompanyCode",
				            "TotalAmount", "TotalQuantity", "qty_in_mt", "OrderItemCount", "DistinctSKUCount",
				            "created_at", "updated_at"
				        },
				        MissingField.UseNull
				    ),
				
				    TypedTable = Table.TransformColumnTypes(
				        FinalSelected,
				        {
				            {"OrderID", Int64.Type},
				            {"DateKey", type date},
				            {"UserID", Int64.Type},
				            {"ClientKey", type text},
				            {"ClientType", type text},
				            {"ClientID", Int64.Type},
				            {"OrderStatus", type text},
				            {"DeliveryMethod", type text},
				            {"OrganizationID", Int64.Type},
				            {"CompanyCode", type text},
				            {"TotalAmount", type number},
				            {"TotalQuantity", type number},
				            {"qty_in_mt", type number},
				            {"OrderItemCount", Int64.Type},
				            {"DistinctSKUCount", Int64.Type},
				            {"created_at", type datetime},
				            {"updated_at", type datetime}
				        }
				    )
				in
				    TypedTable
				```

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

