/// FACT TABLES
/// 
table Fact_Visit
	lineageTag: c56054fa-e8f3-46d0-95fa-016dcd2cc3bf

	measure Total_Retailer_Visits = ```
			
					CALCULATE(
						[Total_Visits],
						'Fact_Visit'[ClientType] = "Retailer"
					)
			```
		formatString: 0
		displayFolder: Visit Counts
		lineageTag: 54fe40e6-9db7-466a-99e5-ab9705614664

	measure Total_Dealer_Visits = ```
			
					CALCULATE(
						[Total_Visits],
						'Fact_Visit'[ClientType] = "Dealer"
					)
			```
		formatString: 0
		displayFolder: Visit Counts
		lineageTag: a5e4d983-80ab-4b70-b9fb-7f624ba43ae4

	measure Territory_Captured_Visits = ```
			
			        CALCULATE(
			            COUNTROWS('Fact_Visit'),
			            'Fact_Visit'[HasTerritory] = 1
			        )
			```
		formatString: 0
		displayFolder: GPS & Territory
		lineageTag: 398beba9-89ad-4586-ae55-85f3dfd8e803

	measure No_Territory_Visits = ```
			
			        CALCULATE(
			            COUNTROWS('Fact_Visit'),
			            'Fact_Visit'[HasTerritory] = 0
			        )
			```
		formatString: 0
		displayFolder: GPS & Territory
		lineageTag: 6f8dc6b2-dce7-4366-b1f2-eb3a53e3a142

	measure GPS_Capture_Rate = ```
			
			        DIVIDE([Territory_Captured_Visits], [Total_Visits], 0)
			```
		displayFolder: Rates
		lineageTag: 06f8ac33-1b5f-46bf-b782-ee4f31e8c4d5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure GPS_Missing_Rate = ```
			
			        DIVIDE([No_Territory_Visits], [Total_Visits], 0)
			```
		lineageTag: e5c69545-b184-4afd-a921-8342eb54e76b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Zone_Mismatch_Visits
		lineageTag: 3ccd55f5-00a4-452c-9ad2-1dedafee8150

	measure Total_Visits = COUNTROWS('Fact_Visit')
		formatString: 0
		lineageTag: 34aafb72-4095-4c1a-bdcc-31f7eb99b15f

	measure Unique_Clients_Visited = DISTINCTCOUNT('Fact_Visit'[ClientKey])
		formatString: 0
		lineageTag: 31ee6a27-68ba-41ec-ac33-8867a08436aa

	measure Active_Employees = DISTINCTCOUNT('Fact_Visit'[EmployeeID])
		formatString: 0
		lineageTag: 3b1eb32b-316d-4216-952d-9df7f823d42d

	measure Visits_Per_Employee = ```
			
			        DIVIDE([Total_Visits], [Active_Employees], 0)
			```
		lineageTag: 264f432d-eae9-4fbe-881a-0c85dc995b1e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_Per_Client = ```
			
			        DIVIDE([Total_Visits], [Unique_Clients_Visited], 0)
			```
		lineageTag: edb0cf22-8b21-4aa2-af54-03fb078e5d8f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Clients_Per_Employee = ```
			
			        DIVIDE([Unique_Clients_Visited], [Active_Employees], 0)
			```
		lineageTag: 0de2c990-7e66-4599-a12c-6ac62120c0b7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_With_Photos = ```
			
			        CALCULATE(
			            COUNTROWS('Fact_Visit'),
			            'Fact_Visit'[HasPhoto] = 1
			        )
			```
		formatString: 0
		lineageTag: e7589b82-1e9d-42c1-b28e-b9ad29001f0b

	measure Photo_Compliance_Rate = ```
			
			        DIVIDE([Visits_With_Photos], [Total_Visits], 0)
			```
		lineageTag: 34000498-b990-45b9-ab14-7daa8855b199

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_With_Product_Photos = ```
			
			        CALCULATE(
			            COUNTROWS('Fact_Visit'),
			            'Fact_Visit'[HasProductPhoto] = 1
			        )
			```
		formatString: 0
		lineageTag: 6396bece-4da8-439d-9215-30ffa8fb5344

	measure Product_Photo_Rate = ```
			
			        DIVIDE([Visits_With_Product_Photos], [Total_Visits], 0)
			```
		lineageTag: 0d5dce4a-d3dd-48c6-bfa6-329f082be560

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_With_Feedback = ```
			
			        CALCULATE(
			            COUNTROWS('Fact_Visit'),
			            'Fact_Visit'[HasFeedback] = 1
			        )
			```
		formatString: 0
		lineageTag: 1b03d3bd-a171-4b27-8874-52d7b0c0cff5

	measure Feedback_Rate = ```
			
			        DIVIDE([Visits_With_Feedback], [Total_Visits], 0)
			```
		lineageTag: 1e7d782f-d710-4b94-b7d3-5b8cc454ed66

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visit_Quality_Score = ```
			
			        (
			            [Photo_Compliance_Rate] * 0.4 +
			            [Product_Photo_Rate] * 0.3 +
			            [Feedback_Rate] * 0.3
			        )
			```
		lineageTag: cdf6008b-b3cc-41a7-bdfa-1411dfb0d134

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Clients_Visited_Once = ```
			
			        COUNTROWS(
			            FILTER(
			                VALUES('Fact_Visit'[ClientKey]),
			                CALCULATE(COUNTROWS('Fact_Visit')) = 1
			            )
			        )
			```
		formatString: 0
		lineageTag: 214779a5-b311-4579-aaf1-e8473c7c095e

	measure Clients_Visited_Multiple = ```
			
			        COUNTROWS(
			            FILTER(
			                VALUES('Fact_Visit'[ClientKey]),
			                CALCULATE(COUNTROWS('Fact_Visit')) > 1
			            )
			        )
			```
		formatString: 0
		lineageTag: 29103485-6052-4d0d-85ce-702bec344bd2

	measure Repeat_Visit_Rate = ```
			
			        DIVIDE([Clients_Visited_Multiple], [Unique_Clients_Visited], 0)
			```
		lineageTag: 90a3a66c-8a85-47cb-b600-6aef0c143616

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_MTD = ```
			
			        CALCULATE(
			            [Total_Visits],
			            DATESMTD('Dim_Date'[Date])
			        )
			```
		formatString: 0
		lineageTag: 50bac071-3622-42a0-aac9-53f59b3180cc

	measure Visits_QTD = ```
			
			        CALCULATE(
			            [Total_Visits],
			            DATESQTD('Dim_Date'[Date])
			        )
			```
		formatString: 0
		lineageTag: 8535cd94-c562-41e5-9311-39b5b1d7c62a

	measure Visits_YTD = ```
			
			        CALCULATE(
			            [Total_Visits],
			            DATESYTD('Dim_Date'[Date])
			        )
			```
		formatString: 0
		lineageTag: 0e81e912-4474-4b27-93a2-7c09d6f4ba0c

	/// Week-To-Date Visits - FR-7-10 Date Filter
	/// Uses WeekStartDate from Dim_Date (Saturday start per Bangladesh fiscal calendar)
	measure Visits_WTD = ```
			CALCULATE(
			    [Total_Visits],
			    DATESBETWEEN(
			        'Dim_Date'[Date],
			        MAX('Dim_Date'[WeekStartDate]),
			        TODAY()
			    )
			)
			```
		formatString: 0
		displayFolder: Time Intelligence
		lineageTag: 4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a

	/// Dynamic Date Filter Measure - responds to DateFilterParam selection
	/// FR-7-10: Radio buttons for Daily, WTD, MTD, YTD
	measure Visits_DateFiltered = ```
			VAR SelectedFilter = SELECTEDVALUE('DateFilterParam'[FilterOption], "MTD")
			RETURN
			SWITCH(
			    SelectedFilter,
			    "Daily", CALCULATE(
			        [Total_Visits],
			        'Dim_Date'[Date] = TODAY()
			    ),
			    "WTD", [Visits_WTD],
			    "MTD", [Visits_MTD],
			    "YTD", [Visits_YTD],
			    [Visits_MTD]
			)
			```
		formatString: 0
		displayFolder: FRD Dashboard
		lineageTag: 5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b

	/// Territory Filtering via Dim_User bridge
	/// Phase 5.5: Uses TREATAS for virtual relationship to Dim_Territory
	/// This avoids adding redundant direct relationship from Fact_Visit to Dim_Territory
	measure Visits_By_Territory = ```
			CALCULATE(
			    [Total_Visits],
			    TREATAS(
			        VALUES('Dim_Territory'[ZoneName]),
			        'Dim_User'[ZoneName]
			    )
			)
			```
		formatString: 0
		displayFolder: FRD Dashboard
		lineageTag: 6f7a8b9c-0d1e-2f3a-4b5c-6d7e8f9a0b1c

	measure Visits_Previous_Month = ```
			
			        CALCULATE(
			            [Total_Visits],
			            PREVIOUSMONTH('Dim_Date'[Date])
			        )
			```
		formatString: 0
		lineageTag: 9c882202-896d-4c78-a93d-a9ccb27aecc5

	measure Visits_Previous_Quarter = ```
			
			        CALCULATE(
			            [Total_Visits],
			            PREVIOUSQUARTER('Dim_Date'[Date])
			        )
			```
		formatString: 0
		lineageTag: f1b149b6-d087-414b-9d8d-dcb5677a907f

	measure Visits_Previous_Year = ```
			
			        CALCULATE(
			            [Total_Visits],
			            PREVIOUSYEAR('Dim_Date'[Date])
			        )
			```
		formatString: 0
		lineageTag: b2879c35-7bf0-4531-9452-1648c0f3c82d

	measure Visits_MoM_Growth = ```
			
			        DIVIDE(
			            [Total_Visits] - [Visits_Previous_Month],
			            [Visits_Previous_Month],
			            0
			        )
			```
		lineageTag: 670cb828-a5fb-44f7-aae7-fe07a77be1e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_YoY_Growth = ```
			
			        DIVIDE(
			            [Total_Visits] - [Visits_Previous_Year],
			            [Visits_Previous_Year],
			            0
			        )
			```
		lineageTag: d0100c9e-e3c7-4afc-813e-b1c5706a3c15

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Visits_Rolling_7_Days = ```
			
			        CALCULATE(
			            [Total_Visits],
			            DATESINPERIOD('Dim_Date'[Date], MAX('Dim_Date'[Date]), -7, DAY)
			        )
			```
		formatString: 0
		lineageTag: 6983840a-3280-419a-ac14-e39226e6aaed

	measure Visits_Rolling_30_Days = ```
			
			        CALCULATE(
			            [Total_Visits],
			            DATESINPERIOD('Dim_Date'[Date], MAX('Dim_Date'[Date]), -30, DAY)
			        )
			```
		formatString: 0
		lineageTag: c367a91b-f506-458c-93bf-081dea8dc71a

	measure Unique_Territories = DISTINCTCOUNT('Fact_Visit'[territory_id])
		formatString: 0
		lineageTag: 4566f4a9-877b-46a3-9235-59dec5a91fa7

	measure Avg_Visits_Per_Day = ```
			
			        DIVIDE(
			            [Total_Visits],
			            DISTINCTCOUNT('Fact_Visit'[DateKey])
			        )
			```
		lineageTag: 66563689-57d2-40c5-ac30-a7c55ff2a025

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Top_Performer_Visits = ```
			
			        MAXX(
			            VALUES('Fact_Visit'[EmployeeID]),
			            CALCULATE([Total_Visits])
			        )
			```
		formatString: 0
		lineageTag: a3669f58-61a5-49ef-9d63-9450f26dea6c

	measure Bottom_Performer_Visits = ```
			
			        MINX(
			            VALUES('Fact_Visit'[EmployeeID]),
			            CALCULATE([Total_Visits])
			        )
			```
		formatString: 0
		lineageTag: 431cb596-4d15-41eb-a9e7-a71d3389072d

	measure Employees_Above_Target = ```
			
			        VAR TargetVisits = 50
			        RETURN
			        COUNTROWS(
			            FILTER(
			                VALUES('Fact_Visit'[EmployeeID]),
			                CALCULATE([Total_Visits]) >= TargetVisits
			            )
			        )
			```
		formatString: 0
		lineageTag: 53b4d37a-fadf-4f2d-8c96-83172b1a6de5

	measure Employee_Performance_Index =
			
			VAR VisitScore = DIVIDE([Total_Visits], [Top_Performer_Visits], 0) * 40
			VAR QualityScore = [Visit_Quality_Score] * 30
			VAR ClientCoverage = DIVIDE([Unique_Clients_Visited], CALCULATE(DISTINCTCOUNT('Dim_Client_Simple'[ClientKey]), ALL('Dim_Client_Simple')), 0) * 30
			RETURN
			ROUND(VisitScore + QualityScore + ClientCoverage, 1)
		formatString: 0.0
		displayFolder: Analytics
		lineageTag: e1a2b3c4-d5e6-f7a8-b9c0-d1e2f3a4b5c6

	measure Visit_Pareto_Running_Total = ```
			
			VAR CurrentEmployee = MAX('Fact_Visit'[EmployeeID])
			VAR EmployeeVisits = [Total_Visits]
			VAR AllEmployeeVisits = 
			    ADDCOLUMNS(
			        SUMMARIZE(ALL('Fact_Visit'), 'Fact_Visit'[EmployeeID]),
			        "@Visits", CALCULATE([Total_Visits])
			    )
			VAR RankedEmployees = 
			    FILTER(AllEmployeeVisits, [@Visits] >= EmployeeVisits)
			VAR RunningTotal = SUMX(RankedEmployees, [@Visits])
			VAR GrandTotal = CALCULATE([Total_Visits], ALL('Fact_Visit'))
			RETURN
			DIVIDE(RunningTotal, GrandTotal, 0)
			```
		formatString: 0.0%
		displayFolder: Analytics
		lineageTag: f2a3b4c5-e6d7-a8b9-c0d1-e2f3a4b5c6d7

	measure Visits_Anomaly_Flag =
			VAR AvgVisits = AVERAGEX(ALL('Dim_Date'[Date]), [Total_Visits])
			VAR StdDeviation = STDEVX.P(ALL('Dim_Date'[Date]), [Total_Visits])
			VAR CurrentVisits = [Total_Visits]
			VAR ZScore = DIVIDE(CurrentVisits - AvgVisits, StdDeviation, 0)
			RETURN
			IF(ABS(ZScore) > 2, 1, 0)
		formatString: 0
		displayFolder: Analytics
		lineageTag: a3b4c5d6-e7f8-a9b0-c1d2-e3f4a5b6c7d8

	measure Visits_Anomaly_Direction =
			VAR AvgVisits = AVERAGEX(ALL('Dim_Date'[Date]), [Total_Visits])
			VAR StdDeviation = STDEVX.P(ALL('Dim_Date'[Date]), [Total_Visits])
			VAR CurrentVisits = [Total_Visits]
			VAR ZScore = DIVIDE(CurrentVisits - AvgVisits, StdDeviation, 0)
			RETURN
			IF(ZScore > 2, "High", IF(ZScore < -2, "Low", "Normal"))
		lineageTag: 575a37eb-189e-4037-8c7e-192f4d7e9d2d

	measure Days_Since_Last_Visit =
			VAR LastVisitDate = MAX('Fact_Visit'[DateKey])
			VAR Today = TODAY()
			RETURN
			DATEDIFF(LastVisitDate, Today, DAY)
		formatString: 0
		displayFolder: Analytics
		lineageTag: c5d6e7f8-a9b0-c1d2-e3f4-a5b6c7d8e9f0

	measure Avg_Days_Between_Visits =
			
			VAR VisitDates = SUMMARIZE('Fact_Visit', 'Fact_Visit'[DateKey])
			VAR DateCount = COUNTROWS(VisitDates)
			VAR DateRange = DATEDIFF(MIN('Fact_Visit'[DateKey]), MAX('Fact_Visit'[DateKey]), DAY)
			RETURN
			IF(DateCount > 1, DIVIDE(DateRange, DateCount - 1, 0), BLANK())
		formatString: 0.0
		lineageTag: d6e7f8a9-b0c1-d2e3-f4a5-b6c7d8e9f0a1

	measure Employee_Rank_by_Visits =
			
			VAR CurrentVisits = [Total_Visits]
			RETURN
			COUNTROWS(
			    FILTER(
			        SUMMARIZE(ALL('Fact_Visit'), 'Fact_Visit'[EmployeeID], "@V", [Total_Visits]),
			        [@V] > CurrentVisits
			    )
			) + 1
		formatString: 0
		lineageTag: e7f8a9b0-c1d2-e3f4-a5b6-c7d8e9f0a1b2

	measure Top_5_Employees_Contribution = ```
			
			VAR Top5 = 
			    TOPN(
			        5,
			        SUMMARIZE(ALL('Fact_Visit'), 'Fact_Visit'[EmployeeID], "@V", [Total_Visits]),
			        [@V], DESC
			    )
			VAR Top5Total = SUMX(Top5, [@V])
			VAR GrandTotal = CALCULATE([Total_Visits], ALL('Fact_Visit'))
			RETURN
			DIVIDE(Top5Total, GrandTotal, 0)
			```
		formatString: 0.0%
		lineageTag: f8a9b0c1-d2e3-f4a5-b6c7-d8e9f0a1b2c3

	measure Visit_Streak_Days = ```
			
			VAR MaxDate = MAX('Dim_Date'[Date])
			VAR ConsecutiveDays = 
			    SUMX(
			        GENERATEALL(
			            GENERATESERIES(0, 30, 1),
			            VAR CheckDate = MaxDate - [Value]
			            VAR HasVisit = CALCULATE(COUNTROWS('Fact_Visit'), 'Dim_Date'[Date] = CheckDate) > 0
			            RETURN ROW("@Day", [Value], "@Has", HasVisit)
			        ),
			        IF([@Has] && EARLIER([@Day]) = 0 || ([@Has] && CALCULATE(MAX([@Has]), FILTER(ALL([@Day]), [@Day] < EARLIER([@Day])))) = TRUE(), 1, 0)
			    )
			RETURN ConsecutiveDays
			```
		formatString: 0
		lineageTag: a9b0c1d2-e3f4-a5b6-c7d8-e9f0a1b2c3d4

	/// FR-24: Total Visit - KPI Tile with comma formatting
	measure Total_Visit_FRD = COUNTROWS('Fact_Visit')
		formatString: #,##0
		displayFolder: FRD Dashboard\KPI Tiles
		lineageTag: 1a2b3c4d-5e6f-7890-abcd-ef1234567890

	/// FR-27-28: Average Visit per Employee
	measure Average_Visit_FRD = ```
			
					VAR TotalVisits = COUNTROWS('Fact_Visit')
					VAR UniqueEmployeesWithVisits = DISTINCTCOUNT('Fact_Visit'[EmployeeID])
					RETURN
					IF(
						UniqueEmployeesWithVisits = 0, 
						0, 
						ROUND(DIVIDE(TotalVisits, UniqueEmployeesWithVisits), 0)
					)
			```
		formatString: #,##0
		displayFolder: FRD Dashboard\KPI Tiles
		lineageTag: 2b3c4d5e-6f7a-8901-bcde-f12345678901

	/// FR-38-44: Current Month Visits for MoM Comparison
	measure Visits_Current_Month = ```
			
					CALCULATE(
						COUNTROWS('Fact_Visit'),
						DATESMTD('Dim_Date'[Date])
					)
			```
		formatString: #,##0
		displayFolder: FRD Dashboard\MoM Comparison
		lineageTag: 3c4d5e6f-7a8b-9012-cdef-123456789012

	/// FR-41: Previous Calendar Month Visits
	measure Visits_Previous_Calendar_Month = ```
			
					CALCULATE(
						COUNTROWS('Fact_Visit'),
						DATEADD(DATESMTD('Dim_Date'[Date]), -1, MONTH)
					)
			```
		formatString: #,##0
		displayFolder: FRD Dashboard\MoM Comparison
		lineageTag: 4d5e6f7a-8b9c-0123-def0-234567890123

	/// FR-42: MoM Variance (absolute difference)
	measure MoM_Variance = [Visits_Current_Month] - [Visits_Previous_Calendar_Month]
		formatString: +#,##0;-#,##0;0
		displayFolder: FRD Dashboard\MoM Comparison
		lineageTag: 5e6f7a8b-9c0d-1234-ef01-345678901234

	/// FR-43: MoM Variance Percentage
	measure MoM_Variance_Pct = ```
			
					DIVIDE(
						[MoM_Variance],
						[Visits_Previous_Calendar_Month],
						0
					)
			```
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: FRD Dashboard\MoM Comparison
		lineageTag: 6f7a8b9c-0d1e-2345-f012-456789012345

	/// FR-50-52: Employee Visit Count for ranking
	measure Employee_Visit_Count = COUNTROWS('Fact_Visit')
		formatString: #,##0
		displayFolder: FRD Dashboard\Rankings
		lineageTag: 7a8b9c0d-1e2f-3456-0123-567890123456

	/// FR-53-56: Employee Rank (ascending) - For Bottom Performers
	measure Employee_Rank_Asc = ```
			
					VAR CurrentVisits = [Employee_Visit_Count]
					VAR AllEmployeeVisits = 
						ADDCOLUMNS(
							SUMMARIZE(
								ALL('Fact_Visit'),
								'Fact_Visit'[EmployeeID]
							),
							"@Visits", [Employee_Visit_Count]
						)
					RETURN
					COUNTROWS(
						FILTER(
							AllEmployeeVisits,
							[@Visits] < CurrentVisits
						)
					) + 1
			```
		formatString: 0
		displayFolder: FRD Dashboard\Rankings
		lineageTag: 8b9c0d1e-2f3a-4567-1234-678901234567

	/// FR-57-60: Employee Rank (descending) - For Top Performers
	measure Employee_Rank_Desc = ```
			
					VAR CurrentVisits = [Employee_Visit_Count]
					VAR AllEmployeeVisits = 
						ADDCOLUMNS(
							SUMMARIZE(
								ALL('Fact_Visit'),
								'Fact_Visit'[EmployeeID]
							),
							"@Visits", [Employee_Visit_Count]
						)
					RETURN
					COUNTROWS(
						FILTER(
							AllEmployeeVisits,
							[@Visits] > CurrentVisits
						)
					) + 1
			```
		formatString: 0
		displayFolder: FRD Dashboard\Rankings
		lineageTag: 9c0d1e2f-3a4b-5678-2345-789012345678

	/// FR-61: Is Top 10 Performer Flag
	measure Is_Top_10 = IF([Employee_Rank_Desc] <= 10, 1, 0)
		formatString: 0
		displayFolder: FRD Dashboard\Rankings
		lineageTag: 0d1e2f3a-4b5c-6789-3456-890123456789

	/// FR-62: Is Bottom 10 Performer Flag
	measure Is_Bottom_10 = IF([Employee_Rank_Asc] <= 10, 1, 0)
		formatString: 0
		displayFolder: FRD Dashboard\Rankings
		lineageTag: 1e2f3a4b-5c6d-7890-4567-901234567890

	/// FR-22-23: Clients Dashboard Filter (Dealer + Retailer)
	measure Visits_Clients = ```
			
					CALCULATE(
						COUNTROWS('Fact_Visit'),
						'Fact_Visit'[ClientType] IN {"Dealer", "Retailer"}
					)
			```
		formatString: #,##0
		displayFolder: FRD Dashboard\Entity Filters
		lineageTag: 2f3a4b5c-6d7e-8901-5678-012345678901

	/// FR-66-68: Influencers Dashboard Filter (Engineer + Contractor)
	measure Visits_Influencers = ```
			
					CALCULATE(
						COUNTROWS('Fact_Visit'),
						'Fact_Visit'[ClientType] IN {"Engineer", "Contractor"}
					)
			```
		formatString: #,##0
		displayFolder: FRD Dashboard\Entity Filters
		lineageTag: 3a4b5c6d-7e8f-9012-6789-123456789012

	/// FR-69-74: Customers Dashboard Filter (Site + IHB)
	measure Visits_Customers = ```
			
					CALCULATE(
						COUNTROWS('Fact_Visit'),
						'Fact_Visit'[ClientType] IN {"Site", "IHB"}
					)
			```
		formatString: #,##0
		displayFolder: FRD Dashboard\Entity Filters
		lineageTag: 4b5c6d7e-8f90-1234-7890-234567890123

	/// FR-6: Last Data Refresh Timestamp
	measure Last_Refresh_DateTime = ```
			
					VAR LastUpdate = MAX('Fact_Visit'[updated_at])
					RETURN
					FORMAT(LastUpdate, "DD-MMM-YYYY HH:MM:SS")
			```
		displayFolder: FRD Dashboard\Metadata
		lineageTag: 5c6d7e8f-9012-3456-8901-345678901234

	/// FR-11-15: Dynamic Location Label - responds to LocationLevelParam selection
	measure Location_Label_Dynamic = ```
			
					VAR SelectedLevel = SELECTEDVALUE('LocationLevelParam'[LevelOption], "Area")
					RETURN
					SWITCH(
						SelectedLevel,
						"Area", SELECTEDVALUE('Dim_Territory'[AreaName]),
						"Zone", SELECTEDVALUE('Dim_Territory'[ZoneName]),
						"Territory", SELECTEDVALUE('Dim_Territory'[RegionName]),
						SELECTEDVALUE('Dim_Territory'[AreaName])
					)
			```
		displayFolder: FRD Dashboard\Location
		lineageTag: 6d7e8f90-1234-5678-9012-456789012345

	/// CLIENT TYPE VISIT MEASURES
	/// Total Engineer Visits
	measure Total_Engineer_Visits = ```
			CALCULATE(
				[Total_Visits],
				'Fact_Visit'[ClientType] = "Engineer"
			)
			```
		formatString: 0
		displayFolder: Visit Counts
		lineageTag: a1b2c3d4-5e6f-7890-abcd-ef0123456789

	/// Total Contractor Visits
	measure Total_Contractor_Visits = ```
			CALCULATE(
				[Total_Visits],
				'Fact_Visit'[ClientType] = "Contractor"
			)
			```
		formatString: 0
		displayFolder: Visit Counts
		lineageTag: b2c3d4e5-6f7a-8901-bcde-f01234567890

	/// Total Site Visits (in Fact_Visit)
	measure Total_Site_Visits = ```
			CALCULATE(
				[Total_Visits],
				'Fact_Visit'[ClientType] = "Site"
			)
			```
		formatString: 0
		displayFolder: Visit Counts
		lineageTag: c3d4e5f6-7a8b-9012-cdef-012345678901

	/// Total IHB Visits
	measure Total_IHB_Visits = ```
			CALCULATE(
				[Total_Visits],
				'Fact_Visit'[ClientType] = "IHB"
			)
			```
		formatString: 0
		displayFolder: Visit Counts
		lineageTag: d4e5f6a7-8b9c-0123-def0-123456789012

	/// Total Influencers Visits (Engineer + Contractor)
	measure Total_Influencers_Visits = ```
			CALCULATE(
				[Total_Visits],
				'Fact_Visit'[ClientType] IN {"Engineer", "Contractor"}
			)
			```
		formatString: 0
		displayFolder: Visit Counts
		lineageTag: e5f6a7b8-9c0d-1234-ef01-234567890123

	/// MOM COMPARISON - Alternative Names (for report compatibility)
	/// Current Month Visits (alternative name for report compatibility)
	measure CurrentMonth_Visits = [Visits_Current_Month]
		formatString: #,##0
		displayFolder: FRD Dashboard\MoM Comparison
		lineageTag: f6a7b8c9-0d1e-2345-f012-345678901234

	/// Previous Month Visits (alternative name for report compatibility)
	measure PreviousMonth_Visits = [Visits_Previous_Calendar_Month]
		formatString: #,##0
		displayFolder: FRD Dashboard\MoM Comparison
		lineageTag: a7b8c9d0-1e2f-3456-0123-456789012345

	column VisitID
		dataType: int64
		formatString: 0
		lineageTag: b0de3cfc-46f7-497b-a6be-4687f8f16deb
		summarizeBy: count
		sourceColumn: VisitID

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: dateTime
		formatString: Long Date
		lineageTag: 072c2531-4ca1-482c-9013-186853e98d95
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EmployeeID
		dataType: int64
		formatString: 0
		lineageTag: ebe2fbff-df71-4ba9-8959-aacb4ae544f5
		summarizeBy: none
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column EmployeeName
		dataType: string
		lineageTag: 02e02cd3-5877-48af-b2af-0a498d169001
		summarizeBy: none
		sourceColumn: EmployeeName

		annotation SummarizationSetBy = Automatic

	column RoleLevel
		dataType: int64
		formatString: 0
		lineageTag: 1765b72a-1d08-4220-8ce0-7e66db466411
		summarizeBy: none
		sourceColumn: RoleLevel

		annotation SummarizationSetBy = Automatic

	column ClientKey
		dataType: string
		lineageTag: 9d18c8ac-c77f-4d24-b6e5-3651527aa443
		summarizeBy: none
		sourceColumn: ClientKey

		annotation SummarizationSetBy = Automatic

	column ClientType
		dataType: string
		lineageTag: 66689d2b-c845-400e-99f1-7debb4cedff7
		summarizeBy: none
		sourceColumn: ClientType

		annotation SummarizationSetBy = Automatic

	column ClientID
		dataType: int64
		formatString: 0
		lineageTag: 39af79e3-decb-4a38-bafe-b7558e40be08
		summarizeBy: count
		sourceColumn: ClientID

		annotation SummarizationSetBy = Automatic

	column ResponsibleRole
		dataType: string
		lineageTag: 05455d21-d73e-4d31-b6b6-f2c656cc787e
		summarizeBy: none
		sourceColumn: ResponsibleRole

		annotation SummarizationSetBy = Automatic

	column visit_type
		dataType: string
		lineageTag: f096ca87-88eb-4825-a3cb-cd483bc02d44
		summarizeBy: none
		sourceColumn: visit_type

		annotation SummarizationSetBy = Automatic

	column VisitCategoryID
		dataType: int64
		formatString: 0
		lineageTag: 62d47ec7-f58c-4472-a939-bd1e6485b553
		summarizeBy: none
		sourceColumn: VisitCategoryID

		annotation SummarizationSetBy = Automatic

	column VisitPhaseID
		dataType: int64
		formatString: 0
		lineageTag: 38120914-2534-4578-86bf-f60cc971db1d
		summarizeBy: none
		sourceColumn: VisitPhaseID

		annotation SummarizationSetBy = Automatic

	column VisitStageID
		dataType: int64
		formatString: 0
		lineageTag: 130690e0-b967-48f9-b8f1-e1e58f4e42cb
		summarizeBy: count
		sourceColumn: VisitStageID

		annotation SummarizationSetBy = Automatic

	column organization_id
		dataType: int64
		formatString: 0
		lineageTag: 53f429e7-23bb-40cc-a22f-d4c956fc11e1
		summarizeBy: none
		sourceColumn: organization_id

		annotation SummarizationSetBy = Automatic

	/// FR-16-18: Company Code for ACL/AIL filter
	column CompanyCode
		dataType: string
		lineageTag: 7e8f9012-3456-7890-abcd-567890123456
		summarizeBy: none
		sourceColumn: CompanyCode

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 9bce3478-d606-49c7-81e0-ca1db3d963e9
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column feedback
		dataType: string
		lineageTag: 73a0cd4c-1110-4464-ab0d-5eb8172167e1
		summarizeBy: none
		sourceColumn: feedback

		annotation SummarizationSetBy = Automatic

	column visit_photo
		dataType: string
		lineageTag: 2de23af7-bd54-4d48-bf34-02db028bb43b
		summarizeBy: none
		sourceColumn: visit_photo

		annotation SummarizationSetBy = Automatic

	column product_photo
		dataType: string
		lineageTag: 7ae15910-c31e-4ac4-a5cd-8f9e8994638c
		summarizeBy: none
		sourceColumn: product_photo

		annotation SummarizationSetBy = Automatic

	column delete_status
		dataType: string
		lineageTag: 48a49dcc-c249-42af-afe2-04b667df6df8
		summarizeBy: none
		sourceColumn: delete_status

		annotation SummarizationSetBy = Automatic

	column HasPhoto
		dataType: int64
		formatString: 0
		lineageTag: 8b20320f-e823-4238-a6c3-cb755bb26f76
		summarizeBy: sum
		sourceColumn: HasPhoto

		annotation SummarizationSetBy = Automatic

	column HasProductPhoto
		dataType: int64
		formatString: 0
		lineageTag: a2943f65-bd16-41e3-accc-5b05923fec37
		summarizeBy: sum
		sourceColumn: HasProductPhoto

		annotation SummarizationSetBy = Automatic

	column HasFeedback
		dataType: int64
		formatString: 0
		lineageTag: 81462918-5e40-48a7-ab6a-cc7689435f72
		summarizeBy: sum
		sourceColumn: HasFeedback

		annotation SummarizationSetBy = Automatic

	column HasTerritory
		dataType: int64
		formatString: 0
		lineageTag: ed35709f-beb4-4b9f-ae9a-ae56b6260758
		summarizeBy: sum
		sourceColumn: HasTerritory

		annotation SummarizationSetBy = Automatic

	column territory_id
		dataType: int64
		formatString: 0
		lineageTag: 0ec2e29b-23a6-4b38-a6db-7d11bc622979
		summarizeBy: none
		sourceColumn: territory_id

		annotation SummarizationSetBy = Automatic

	column territory_name
		dataType: string
		lineageTag: 17a78ca3-d95e-4965-a6a1-f74f66154cc2
		summarizeBy: none
		sourceColumn: territory_name

		annotation SummarizationSetBy = Automatic

	column followup_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 3817b15f-6bd0-4262-a13a-d89038a51d61
		summarizeBy: none
		sourceColumn: followup_date

		variation Variation
			isDefault
			relationship: 962be8ce-82e9-48c1-98c7-0feb32f403e5
			defaultHierarchy: LocalDateTable_b78652d6-96b5-4ce0-b950-81d1fcd8e989.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column origin
		dataType: string
		lineageTag: 5d0ddd02-2778-4dd6-997c-18508974a8d8
		summarizeBy: none
		sourceColumn: origin

		annotation SummarizationSetBy = Automatic

	column visit_date_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 338fd740-99fb-4810-8e40-6189d35df066
		summarizeBy: none
		sourceColumn: visit_date_time

		variation Variation
			isDefault
			relationship: 78d7e16f-3448-48a9-8ea1-824a10536011
			defaultHierarchy: LocalDateTable_4ccd853a-ffaa-4612-9342-019595dc6792.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 56e124ad-339d-4760-8351-6dd54084044c
		summarizeBy: none
		sourceColumn: created_at

		variation Variation
			isDefault
			relationship: 1987ce8d-274c-4244-acb1-fe2b4f761ec6
			defaultHierarchy: LocalDateTable_80dc7739-add9-4cfa-bfd4-0f267802e538.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 833797d2-9dee-4d6f-9dfc-ff14387a0820
		summarizeBy: none
		sourceColumn: updated_at

		variation Variation
			isDefault
			relationship: 7d5ccdec-0a55-48d8-8dfb-4451b0266308
			defaultHierarchy: LocalDateTable_f8d9e743-e68c-4f07-9f25-9ac4ce880065.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: c3d4e5f6-7890-abcd-ef12-345678901234
		summarizeBy: none
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: d4e5f678-90ab-cdef-1234-567890123456
		summarizeBy: none
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Visit = m
		mode: import
		source = ```
				// ============================================================
				// Fact_Visit - Visit Fact Table
				// Based on actual 'public visits' table schema from Power BI
				// Total Records: 36,041 visits
				// 
				// INFLUENCER SEGREGATION (per PRD.MD):
				// - "Influencer" visits are actually Engineers (managed by BDO)
				// - Contractor visits use contractor_id (managed by CRO)
				// ============================================================
				
				let
				    // Reference the existing 'public visits' table in Power BI
				    // This connects to the semantic model's existing data source
				    Source = #"public visits",
				    
				    // ---- Select Core Columns from actual schema ----
				    SelectedColumns = Table.SelectColumns(Source, {
				        "id", "visit_type", "created_by_id", "create_by_name", "visit_date_time", 
				        "feedback", "visit_photo", "product_photo", "visit_category_id",
				        "visit_phase_id", "visit_stage_id", "status", "followup_date",
				        // Client ID columns (one populated based on visit_type)
				        "potential_site_id", "retailer_id", "dealer_id", 
				        "engineer_id", "contractor_id", "ihb_registration_id", "head_mason_id",
				        "site_manager_id", "organization_id",
				        // Territory info
				        "territory_id", "territory_name", "role_level",
				        // GPS Coordinates
				        "latitude", "longitude",
				        // Metadata
				        "origin", "delete_status", "created_at", "updated_at"
				    }),
				    
				    // ---- Create Unified ClientKey ----
				    // Maps the appropriate ID column based on visit_type
				    // Visit Types: Sites (13,235), Influencer (7,114), Dealer (5,587), 
				    //              Retailer (4,020), IHB (3,807), General Sites (2,278)
				    // 
				    // INFLUENCER SEGREGATION (per PRD):
				    // - Influencer visits with engineer_id → "Engineer" (BDO manages)
				    // - Influencer visits with contractor_id → "Contractor" (CRO manages Partners)
				    WithClientType = Table.AddColumn(SelectedColumns, "ClientType", each 
				        if [visit_type] = "Sites" then "Site"
				        else if [visit_type] = "Retailer" then "Retailer"
				        else if [visit_type] = "Dealer" then "Dealer"
				        else if [visit_type] = "Influencer" then 
				            // INFLUENCER SEGREGATION: Check which ID is populated
				            if [engineer_id] <> null then "Engineer"       // BDO manages Engineers
				            else if [contractor_id] <> null then "Contractor"  // CRO manages Partners/Contractors
				            else "Influencer"  // Fallback for uncategorized Influencers
				        else if [visit_type] = "IHB" then "IHB"
				        else if [visit_type] = "General Sites" then "General"
				        else "Unknown", 
				        type text
				    ),
				    
				    // Use ClientType directly (no need for secondary check)
				    WithContractorCheck = Table.AddColumn(WithClientType, "ClientType_Final", each 
				        [ClientType],
				        type text
				    ),
				    
				    // Extract the appropriate client ID based on visit type
				    WithClientID = Table.AddColumn(WithContractorCheck, "ClientID", each 
				        if [ClientType_Final] = "Site" then [potential_site_id]
				        else if [ClientType_Final] = "Retailer" then [retailer_id]
				        else if [ClientType_Final] = "Dealer" then [dealer_id]
				        else if [ClientType_Final] = "Engineer" then [engineer_id]  // Engineers managed by BDO
				        else if [ClientType_Final] = "Contractor" then [contractor_id]  // Contractors/Partners managed by CRO
				        else if [ClientType_Final] = "IHB" then [ihb_registration_id]
				        else null,
				        Int64.Type
				    ),
				    
				    // Add Responsible Role based on client type (for filtering/RLS)
				    WithResponsibleRole = Table.AddColumn(WithClientID, "ResponsibleRole", each 
				        if [ClientType_Final] = "Site" then "BDO"
				        else if [ClientType_Final] = "Engineer" then "BDO"
				        else if [ClientType_Final] = "Contractor" then "CRO"
				        else if [ClientType_Final] = "Retailer" then "SR"
				        else if [ClientType_Final] = "Dealer" then "CRO"
				        else if [ClientType_Final] = "IHB" then "CRO,BDO"
				        else "All",
				        type text
				    ),
				    
				    // Create composite ClientKey to match Dim_Client
				    WithClientKey = Table.AddColumn(WithResponsibleRole, "ClientKey", each 
				        if [ClientID] <> null then [ClientType_Final] & "-" & Text.From([ClientID])
				        else null,
				        type text
				    ),
				    
				    // Remove the intermediate ClientType column, use ClientType_Final
				    RemovedIntermediate = Table.RemoveColumns(WithClientKey, {"ClientType"}),
				    RenamedClientType = Table.RenameColumns(RemovedIntermediate, {{"ClientType_Final", "ClientType"}}),
				    
				    // ---- Add Quality Metrics ----
				    // Photo Compliance (1 if visit_photo exists, 0 otherwise)
				    WithPhotoFlag = Table.AddColumn(RenamedClientType, "HasPhoto", each 
				        if [visit_photo] <> null and [visit_photo] <> "" then 1 else 0,
				        Int64.Type
				    ),
				    
				    // Product Photo Captured
				    WithProductPhotoFlag = Table.AddColumn(WithPhotoFlag, "HasProductPhoto", each 
				        if [product_photo] <> null and [product_photo] <> "" then 1 else 0,
				        Int64.Type
				    ),
				    
				    // Feedback Provided (1 if feedback exists, 0 otherwise)
				    WithFeedbackFlag = Table.AddColumn(WithProductPhotoFlag, "HasFeedback", each 
				        if [feedback] <> null and [feedback] <> "" then 1 else 0,
				        Int64.Type
				    ),
				    
				    // Territory Captured (1 if territory_id exists, 0 otherwise)
				    WithTerritoryFlag = Table.AddColumn(WithFeedbackFlag, "HasTerritory", each 
				        if [territory_id] <> null then 1 else 0,
				        Int64.Type
				    ),
				    
				    // ---- FR-16-18: Add Company Code (ACL/AIL) ----
				    // Maps organization_id to company codes for filtering
				    WithCompanyCode = Table.AddColumn(WithTerritoryFlag, "CompanyCode", each 
				        if [organization_id] = 1 then "ACL"
				        else if [organization_id] = 2 then "AIL"
				        else "Unknown",
				        type text
				    ),
				    
				    // ---- Extract Date Key for Dim_Date join ----
				    WithDateKey = Table.AddColumn(WithCompanyCode, "DateKey", each 
				        Date.From([visit_date_time]),
				        type date
				    ),
				    
				    // ---- Rename ID column ----
				    RenamedColumns = Table.RenameColumns(WithDateKey, {
				        {"id", "VisitID"},
				        {"created_by_id", "EmployeeID"},
				        {"create_by_name", "EmployeeName"},
				        {"visit_category_id", "VisitCategoryID"},
				        {"visit_phase_id", "VisitPhaseID"},
				        {"visit_stage_id", "VisitStageID"},
				        {"role_level", "RoleLevel"}
				    }),
				    
				    // ---- Remove individual client ID columns (now unified) ----
				    CleanedColumns = Table.RemoveColumns(RenamedColumns, {
				        "potential_site_id", "retailer_id", "dealer_id", 
				        "engineer_id", "contractor_id", "ihb_registration_id", 
				        "head_mason_id", "site_manager_id"
				    }),
				    
				    // ---- Filter out deleted records ----
				    ActiveRecords = Table.SelectRows(CleanedColumns, each [delete_status] = "NO"),
				    
				    // ---- Reorder Columns ----
				    ReorderedColumns = Table.ReorderColumns(ActiveRecords, {
				        "VisitID", "DateKey", "EmployeeID", "EmployeeName", "RoleLevel",
				        "ClientKey", "ClientType", "ClientID", "ResponsibleRole", "visit_type", 
				        "VisitCategoryID", "VisitPhaseID", "VisitStageID", "organization_id", "CompanyCode", "status",
				        "feedback", "visit_photo", "product_photo",
				        "HasPhoto", "HasProductPhoto", "HasFeedback", "HasTerritory",
				        "territory_id", "territory_name", "latitude", "longitude", "followup_date",
				        "origin", "visit_date_time", "created_at", "updated_at"
				    }),
				    
				    // ---- Set Data Types ----
				    TypedTable = Table.TransformColumnTypes(ReorderedColumns, {
				        {"VisitID", Int64.Type},
				        {"DateKey", type date},
				        {"EmployeeID", Int64.Type},
				        {"EmployeeName", type text},
				        {"RoleLevel", Int64.Type},
				        {"ClientKey", type text},
				        {"ClientType", type text},
				        {"ClientID", Int64.Type},
				        {"ResponsibleRole", type text},
				        {"visit_type", type text},
				        {"VisitCategoryID", Int64.Type},
				        {"VisitPhaseID", Int64.Type},
				        {"VisitStageID", Int64.Type},
				        {"organization_id", Int64.Type},
				        {"CompanyCode", type text},
				        {"status", type text},
				        {"feedback", type text},
				        {"visit_photo", type text},
				        {"product_photo", type text},
				        {"HasPhoto", Int64.Type},
				        {"HasProductPhoto", Int64.Type},
				        {"HasFeedback", Int64.Type},
				        {"HasTerritory", Int64.Type},
				        {"territory_id", Int64.Type},
				        {"territory_name", type text},
				        {"latitude", type number},
				        {"longitude", type number},
				        {"followup_date", type datetime},
				        {"origin", type text},
				        {"visit_date_time", type datetime},
				        {"created_at", type datetime},
				        {"updated_at", type datetime}
				    })
				in
				    TypedTable
				```

	annotation PBI_ResultType = Table

