table Fact_Target
	lineageTag: 7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d

	partition Fact_Target = calculated
		mode: import
		source = ```
			VAR MinDate = MIN(Fact_Visit[DateKey])
			VAR MaxDate = MAX(Fact_Visit[DateKey])
			VAR DateRange = FILTER(
			    ALL(Dim_Date[DateKey]),
			    Dim_Date[DateKey] >= MinDate && Dim_Date[DateKey] <= MaxDate
			)
			VAR Users = DISTINCT(Dim_User[UserID])
			VAR EntityGroups = DATATABLE(
			    "EntityGroup", STRING,
			    {
			        {"Customers"},
			        {"Consumers"},
			        {"Influencers"}
			    }
			)
			VAR BaseTable = CROSSJOIN(DateRange, Users, EntityGroups)
			RETURN
			ADDCOLUMNS(
			    BaseTable,
			    "DailyTarget", 
			    SWITCH(
			        [EntityGroup],
			        "Customers", 10,
			        "Influencers", 10,
			        "Consumers", 5,
			        10
			    )
			)
			```

	column DateKey
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column UserID
		dataType: int64
		formatString: 0
		lineageTag: 9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f
		summarizeBy: none
		sourceColumn: UserID

		annotation SummarizationSetBy = Automatic

	column EntityGroup
		dataType: string
		lineageTag: 0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a
		summarizeBy: none
		sourceColumn: EntityGroup

		annotation SummarizationSetBy = Automatic

	column DailyTarget
		dataType: int64
		formatString: 0
		lineageTag: 1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b
		summarizeBy: sum
		sourceColumn: DailyTarget

		annotation SummarizationSetBy = Automatic

	measure Target_Sum = SUM(Fact_Target[DailyTarget])
		formatString: #,##0
		displayFolder: FRD Dashboard\Targets
		lineageTag: 2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c

	annotation PBI_ResultType = Table

