/// LocationLevelParam - Disconnected Parameter Table for Location Level Selection
/// This table is intentionally NOT connected to any other table (no relationships)
/// Used for FR-11-15: Location filter with dynamic level (Area, Zone, Territory)
/// Reference: FRD_IMPLEMENTATION_GUIDE.md - Phase 5.5 Relationship Schema Verification

table LocationLevelParam
	lineageTag: 1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d

	column LevelOption
		dataType: string
		lineageTag: 2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e
		summarizeBy: none
		sourceColumn: LevelOption

		annotation SummarizationSetBy = Automatic

	column LevelOrder
		dataType: int64
		lineageTag: 3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f
		formatString: 0
		summarizeBy: none
		sourceColumn: LevelOrder

		annotation SummarizationSetBy = Automatic

	partition LocationLevelParam = m
		mode: import
		source =
			let
			    Source = #table(
			        {"LevelOption", "LevelOrder"},
			        {
			            {"Area", 1},
			            {"Zone", 2},
			            {"Territory", 3}
			        }
			    ),
			    TypedTable = Table.TransformColumnTypes(Source, {
			        {"LevelOption", type text},
			        {"LevelOrder", Int64.Type}
			    })
			in
			    TypedTable

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation IsDisconnectedParameterTable = true

