table 'public visits'
	isHidden
	lineageTag: 808a39a5-1c4b-496a-bdaf-ce0a0d22e91b

	column id
		dataType: int64
		isHidden
		isKey
		formatString: 0
		lineageTag: ae3292fe-1128-45b9-90eb-52baec404035
		summarizeBy: sum
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column bd_incharge_feedback
		dataType: string
		isHidden
		lineageTag: 1177af13-f7df-4cf6-ab24-eebda373999a
		summarizeBy: none
		sourceColumn: bd_incharge_feedback

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column conversion_no
		dataType: string
		isHidden
		lineageTag: 35080cb1-d23b-4a71-bc52-5ddfe0eca68f
		summarizeBy: none
		sourceColumn: conversion_no

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column create_by_name
		dataType: string
		isHidden
		lineageTag: 985e8724-7ca5-45ff-bdc9-5700c708a330
		summarizeBy: none
		sourceColumn: create_by_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 8730f20d-ce1c-413a-838f-af3ae49bb529
		summarizeBy: none
		sourceColumn: created_at

		variation Variation
			isDefault
			relationship: 38080b16-ee5a-4037-9ce0-971ed2c89027
			defaultHierarchy: LocalDateTable_4ff2a9dd-527f-4851-bfbd-491ba008777f.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column delete_status
		dataType: string
		isHidden
		lineageTag: 951e7b84-55ac-4768-9070-fd9f99b827fa
		summarizeBy: none
		sourceColumn: delete_status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column entity_id
		dataType: string
		isHidden
		lineageTag: fd3e3832-757a-4403-b883-e25f5474da52
		summarizeBy: none
		sourceColumn: entity_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column entity_name
		dataType: string
		isHidden
		lineageTag: 46bcf593-b91d-4994-85e3-27bbe504f200
		summarizeBy: none
		sourceColumn: entity_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column entity_record_id
		dataType: string
		isHidden
		lineageTag: ef7e6450-5669-495b-8448-5c0524faf571
		summarizeBy: none
		sourceColumn: entity_record_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column feedback
		dataType: string
		isHidden
		lineageTag: 359fe502-e3ff-4fda-9949-6e68b12683c8
		summarizeBy: none
		sourceColumn: feedback

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column followup_date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 40c7f077-2592-497c-9d82-24e1de88fa79
		summarizeBy: none
		sourceColumn: followup_date

		variation Variation
			isDefault
			relationship: 1733bb7c-a3e5-4170-a4db-f059a1a635df
			defaultHierarchy: LocalDateTable_756f7cc1-2c39-41b9-b721-a18bd72aee92.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column influencer_type
		dataType: string
		isHidden
		lineageTag: b2be7ac6-c809-419d-ba24-240da8cff0a0
		summarizeBy: none
		sourceColumn: influencer_type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column origin
		dataType: string
		isHidden
		lineageTag: 93970418-8640-407b-87b0-2f3bad5c39db
		summarizeBy: none
		sourceColumn: origin

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_photo
		dataType: string
		isHidden
		lineageTag: af11d46c-e25f-4703-9263-97959040606a
		summarizeBy: none
		sourceColumn: product_photo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column recordid
		dataType: string
		isHidden
		lineageTag: 39b1495d-f0ff-42fa-8da8-b7b21092112e
		summarizeBy: none
		sourceColumn: recordid

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column role_level
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3a85c1b0-92f6-4b3a-a6bd-38f24d6716e9
		summarizeBy: sum
		sourceColumn: role_level

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		isHidden
		lineageTag: cf73620f-f3d7-49e2-983b-cbd9e60ad5ad
		summarizeBy: none
		sourceColumn: status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column territory_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e3c7ee06-ebfd-4c42-9f04-21c54a1771d7
		summarizeBy: sum
		sourceColumn: territory_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column territory_name
		dataType: string
		isHidden
		lineageTag: e9ff30bb-0d79-4700-985a-a8a07777980c
		summarizeBy: none
		sourceColumn: territory_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: d7ec9313-3952-4225-9e1a-24ff66a25774
		summarizeBy: none
		sourceColumn: updated_at

		variation Variation
			isDefault
			relationship: cf484771-194a-442a-870f-2246465be0dc
			defaultHierarchy: LocalDateTable_edeabc03-7638-4fd9-a371-a86e8dd65833.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column visit_date_time
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 56de6b0a-c8c8-4d48-bd6d-fbae53c78dda
		summarizeBy: none
		sourceColumn: visit_date_time

		variation Variation
			isDefault
			relationship: 22636ac3-c3ba-4fce-b585-ba1d6d8ac352
			defaultHierarchy: LocalDateTable_74bb562f-c78c-469c-87e2-319f69c775a2.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column visit_photo
		dataType: string
		isHidden
		lineageTag: e5ca4050-4283-4601-990f-683b4ad4268e
		summarizeBy: none
		sourceColumn: visit_photo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column visit_type
		dataType: string
		isHidden
		lineageTag: 9975ef84-c603-4a4c-b7e5-7748705f92c2
		summarizeBy: none
		sourceColumn: visit_type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column contractor_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b9427af9-1953-4c2d-b658-08e25f9ef64a
		summarizeBy: sum
		sourceColumn: contractor_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column created_by_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 95e3628e-dc64-4b3c-af29-9070c4d8cf68
		summarizeBy: sum
		sourceColumn: created_by_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dealer_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 10dbd97e-e412-4675-bff2-5bb561b1fa82
		summarizeBy: sum
		sourceColumn: dealer_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column engineer_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 17058432-2464-420b-9517-2df2b8a48a22
		summarizeBy: sum
		sourceColumn: engineer_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column head_mason_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 10083d54-f5aa-4719-a857-4b7e9f014c83
		summarizeBy: sum
		sourceColumn: head_mason_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ihb_registration_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0a8b6254-2287-4943-9a9e-15125ab86693
		summarizeBy: sum
		sourceColumn: ihb_registration_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column organization_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 65e0251a-8ee1-4df8-98fc-5c663f9fd2a5
		summarizeBy: sum
		sourceColumn: organization_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column potential_site_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7b7a94b2-d93b-46e1-8263-12c4da2a07e5
		summarizeBy: sum
		sourceColumn: potential_site_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column project_conversion_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f53b9c3b-7dd9-4a68-83c3-fac33b949860
		summarizeBy: sum
		sourceColumn: project_conversion_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column retailer_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 62300029-6233-4299-aa48-2252cfacb7a0
		summarizeBy: sum
		sourceColumn: retailer_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column site_manager_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8354cda0-26e5-45fc-a27d-1ea8fc99c96f
		summarizeBy: sum
		sourceColumn: site_manager_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column updated_by_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5721a6ee-489a-4f16-a845-ddde0ed11a3a
		summarizeBy: sum
		sourceColumn: updated_by_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column visit_category_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 97a61557-cac1-48d1-b40c-32b2ca2e70dc
		summarizeBy: sum
		sourceColumn: visit_category_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column visit_phase_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f469d84c-cf40-4bb2-a291-a2aae12d0d4d
		summarizeBy: sum
		sourceColumn: visit_phase_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column visit_stage_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 70e50944-f70c-48ac-ab19-03d3c1c1aebb
		summarizeBy: sum
		sourceColumn: visit_stage_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		isHidden
		lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890
		summarizeBy: none
		sourceColumn: latitude

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		isHidden
		lineageTag: b2c3d4e5-f678-90ab-cdef-123456789012
		summarizeBy: none
		sourceColumn: longitude

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'public visits' = m
		mode: import
		source =
				let
				  Source = PostgreSQL.Database("172.17.19.21", "bmdsalesdb"),
				  #"Navigation 1" = Source{[Schema = "public", Item = "visits"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"latitude", type number}, {"longitude", type number}}, "bn-BD")
				in
				  #"Changed column type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

