table Target
	excludeFromModelRefresh
	lineageTag: 20d0afb4-8cc4-4c6c-9db6-ecc9c9cb7ce3

	measure Cumulative_Target =
			
			VAR WorkingDays =
			    CALCULATE (
			        COUNTROWS ( Dim_Date ),
			        Dim_Date[IsWeekend] = 0
			    )
			VAR DailyTargetAllEmployees =
			    SUM ( Target[DailyTarget] )
			RETURN
			WorkingDays * DailyTargetAllEmployees
		formatString: 0
		lineageTag: 025ec16e-19e7-4260-bd8a-67161944e45b

	measure Total_Target =
			
			VAR WorkingDays =
			    CALCULATE (
			        COUNTROWS ( Dim_Date ),
			        Dim_Date[IsWeekend] = 0
			    )
			RETURN
			WorkingDays *
			SUMX (
			    VALUES ( Target[EntityGroup] ),
			    CALCULATE ( MAX ( Target[DailyTarget] ) )
			)
		formatString: 0
		lineageTag: c18f40ae-0ba3-436c-95da-1d1f69e8d4e4

	column EntityGroup
		dataType: string
		lineageTag: 8478ea63-9bb3-44ac-a072-13e328be82bf
		summarizeBy: none
		sourceColumn: EntityGroup

		annotation SummarizationSetBy = Automatic

	column UserID
		dataType: int64
		formatString: 0
		lineageTag: ab572660-e696-4b82-a635-9992222e7ac8
		summarizeBy: none
		sourceColumn: UserID

		annotation SummarizationSetBy = Automatic

	column RoleID
		dataType: int64
		formatString: 0
		lineageTag: 8753c34f-5348-4e47-9fb5-7937b2039747
		summarizeBy: count
		sourceColumn: RoleID

		annotation SummarizationSetBy = Automatic

	column RoleName
		dataType: string
		lineageTag: 4457398f-ef32-4260-bd60-5893bb2358a0
		summarizeBy: none
		sourceColumn: RoleName

		annotation SummarizationSetBy = Automatic

	column OrganizationID
		dataType: string
		lineageTag: a55101dd-e668-4d03-aa55-e56218a18103
		summarizeBy: none
		sourceColumn: OrganizationID

		annotation SummarizationSetBy = Automatic

	column Organization
		dataType: string
		lineageTag: 4875e7c5-7577-4df5-aeea-39274108b438
		summarizeBy: none
		sourceColumn: Organization

		annotation SummarizationSetBy = Automatic

	column DailyTarget
		dataType: int64
		formatString: 0
		lineageTag: 509695f1-4a40-433b-8426-081e067f1293
		summarizeBy: sum
		sourceColumn: DailyTarget

		annotation SummarizationSetBy = Automatic

	column 'Volume Target'
		dataType: int64
		formatString: 0
		lineageTag: 2af3b795-f55d-4ec1-8fb3-a5fa6a54b402
		summarizeBy: sum
		sourceColumn: Volume Target

		annotation SummarizationSetBy = Automatic

	partition Target = m
		mode: import
		source =
				let
				  Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/1FvRIxyWdfCVuGGF6JJxoFJiZko5RcjeDKMxFlNEjomY/edit?gid=0#gid=0"),
				  #"Navigation 1" = Source{[name = "Target", ItemKind = "Table"]}[Data],
				  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"EntityGroup", type text}, {"UserID", Int64.Type}, {"RoleID", Int64.Type}, {"DailyTarget", Int64.Type}, {"Volume Target", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

