// ============================================
// GPS & TERRITORY MEASURES - Cross-Role Visit Reporting
// ============================================
// Execute via: POST https://api.powerbi.com/v1.0/myorg/datasets/{datasetId}/executeQueries
// 
// NOTE: Based on actual Fact_Visit schema, only territory_id capture is available.
// Columns like is_zone_mismatch, is_out_of_territory, distance_deviation_km
// do NOT exist in the source data.
// ============================================

// ============================================
// SECTION 1: GPS/TERRITORY CAPTURE MEASURES
// ============================================
DEFINE
    MEASURE 'Fact_Visit'[Total_Visits] = COUNTROWS('Fact_Visit')
    
    MEASURE 'Fact_Visit'[Territory_Captured_Visits] = 
        CALCULATE(
            COUNTROWS('Fact_Visit'),
            NOT(ISBLANK('Fact_Visit'[territory_id]))
        )
    
    MEASURE 'Fact_Visit'[No_Territory_Visits] = 
        CALCULATE(
            COUNTROWS('Fact_Visit'),
            ISBLANK('Fact_Visit'[territory_id])
        )
    
    MEASURE 'Fact_Visit'[GPS_Capture_Rate] = 
        DIVIDE([Territory_Captured_Visits], [Total_Visits], 0)
    
    MEASURE 'Fact_Visit'[GPS_Missing_Rate] = 
        DIVIDE([No_Territory_Visits], [Total_Visits], 0)

EVALUATE
    SUMMARIZECOLUMNS(
        "Total_Visits", [Total_Visits],
        "Territory_Captured_Visits", [Territory_Captured_Visits],
        "No_Territory_Visits", [No_Territory_Visits],
        "GPS_Capture_Rate", [GPS_Capture_Rate],
        "GPS_Missing_Rate", [GPS_Missing_Rate]
    )

// ============================================
// SECTION 2: TERRITORY CAPTURE BY CLIENT TYPE
// ============================================
DEFINE
    MEASURE 'Fact_Visit'[Total_Visits] = COUNTROWS('Fact_Visit')
    
    MEASURE 'Fact_Visit'[Territory_Captured_Visits] = 
        CALCULATE(
            COUNTROWS('Fact_Visit'),
            NOT(ISBLANK('Fact_Visit'[territory_id]))
        )
    
    MEASURE 'Fact_Visit'[GPS_Capture_Rate] = 
        DIVIDE([Territory_Captured_Visits], [Total_Visits], 0)

EVALUATE
    SUMMARIZECOLUMNS(
        'Dim_Client_Simple'[client_type],
        "Total_Visits", [Total_Visits],
        "Territory_Captured", [Territory_Captured_Visits],
        "GPS_Capture_Rate", [GPS_Capture_Rate]
    )

// ============================================
// SECTION 3: TERRITORY CAPTURE BY EMPLOYEE
// ============================================
DEFINE
    MEASURE 'Fact_Visit'[Total_Visits] = COUNTROWS('Fact_Visit')
    
    MEASURE 'Fact_Visit'[Territory_Captured_Visits] = 
        CALCULATE(
            COUNTROWS('Fact_Visit'),
            NOT(ISBLANK('Fact_Visit'[territory_id]))
        )
    
    MEASURE 'Fact_Visit'[GPS_Capture_Rate] = 
        DIVIDE([Territory_Captured_Visits], [Total_Visits], 0)
    
    MEASURE 'Fact_Visit'[Active_Employees] = DISTINCTCOUNT('Fact_Visit'[EmployeeID])
    
    MEASURE 'Fact_Visit'[Employees_With_100_GPS_Capture] = 
        COUNTROWS(
            FILTER(
                VALUES('Fact_Visit'[EmployeeID]),
                CALCULATE([GPS_Capture_Rate]) = 1
            )
        )
    
    MEASURE 'Fact_Visit'[Employees_Below_80_GPS_Capture] = 
        COUNTROWS(
            FILTER(
                VALUES('Fact_Visit'[EmployeeID]),
                CALCULATE([GPS_Capture_Rate]) < 0.8
            )
        )
    
    MEASURE 'Fact_Visit'[High_GPS_Capture_Employee_Rate] = 
        DIVIDE([Employees_With_100_GPS_Capture], [Active_Employees], 0)

EVALUATE
    SUMMARIZECOLUMNS(
        "Active_Employees", [Active_Employees],
        "Employees_With_100_GPS_Capture", [Employees_With_100_GPS_Capture],
        "Employees_Below_80_GPS_Capture", [Employees_Below_80_GPS_Capture],
        "High_GPS_Capture_Employee_Rate", [High_GPS_Capture_Employee_Rate]
    )

// ============================================
// SECTION 4: TERRITORY CAPTURE BY ROLE LEVEL
// ============================================
DEFINE
    MEASURE 'Fact_Visit'[Total_Visits] = COUNTROWS('Fact_Visit')
    
    MEASURE 'Fact_Visit'[Territory_Captured_Visits] = 
        CALCULATE(
            COUNTROWS('Fact_Visit'),
            NOT(ISBLANK('Fact_Visit'[territory_id]))
        )
    
    MEASURE 'Fact_Visit'[GPS_Capture_Rate] = 
        DIVIDE([Territory_Captured_Visits], [Total_Visits], 0)
    
    MEASURE 'Fact_Visit'[Active_Employees] = DISTINCTCOUNT('Fact_Visit'[EmployeeID])

EVALUATE
    SUMMARIZECOLUMNS(
        'Fact_Visit'[RoleLevel],
        "Total_Visits", [Total_Visits],
        "Territory_Captured", [Territory_Captured_Visits],
        "GPS_Capture_Rate", [GPS_Capture_Rate],
        "Active_Employees", [Active_Employees]
    )

// ============================================
// SECTION 5: TERRITORY CAPTURE BY RESPONSIBLE ROLE
// ============================================
DEFINE
    MEASURE 'Fact_Visit'[Total_Visits] = COUNTROWS('Fact_Visit')
    
    MEASURE 'Fact_Visit'[Territory_Captured_Visits] = 
        CALCULATE(
            COUNTROWS('Fact_Visit'),
            NOT(ISBLANK('Fact_Visit'[territory_id]))
        )
    
    MEASURE 'Fact_Visit'[GPS_Capture_Rate] = 
        DIVIDE([Territory_Captured_Visits], [Total_Visits], 0)
    
    MEASURE 'Fact_Visit'[Unique_Clients_Visited] = DISTINCTCOUNT('Fact_Visit'[ClientKey])

EVALUATE
    SUMMARIZECOLUMNS(
        'Fact_Visit'[ResponsibleRole],
        "Total_Visits", [Total_Visits],
        "Territory_Captured", [Territory_Captured_Visits],
        "GPS_Capture_Rate", [GPS_Capture_Rate],
        "Unique_Clients", [Unique_Clients_Visited]
    )

// ============================================
// SECTION 6: TERRITORY CAPTURE TIME TRENDS
// ============================================
DEFINE
    MEASURE 'Fact_Visit'[Total_Visits] = COUNTROWS('Fact_Visit')
    
    MEASURE 'Fact_Visit'[Territory_Captured_Visits] = 
        CALCULATE(
            COUNTROWS('Fact_Visit'),
            NOT(ISBLANK('Fact_Visit'[territory_id]))
        )
    
    MEASURE 'Fact_Visit'[GPS_Capture_Rate] = 
        DIVIDE([Territory_Captured_Visits], [Total_Visits], 0)
    
    MEASURE 'Fact_Visit'[GPS_Capture_Rate_Previous_Month] = 
        CALCULATE(
            [GPS_Capture_Rate],
            PREVIOUSMONTH('Dim_Date'[Date])
        )
    
    MEASURE 'Fact_Visit'[GPS_Capture_Rate_Change] = 
        [GPS_Capture_Rate] - [GPS_Capture_Rate_Previous_Month]
    
    MEASURE 'Fact_Visit'[Territory_Captured_MTD] = 
        CALCULATE(
            [Territory_Captured_Visits],
            DATESMTD('Dim_Date'[Date])
        )
    
    MEASURE 'Fact_Visit'[Territory_Captured_YTD] = 
        CALCULATE(
            [Territory_Captured_Visits],
            DATESYTD('Dim_Date'[Date])
        )

EVALUATE
    SUMMARIZECOLUMNS(
        "GPS_Capture_Rate", [GPS_Capture_Rate],
        "GPS_Capture_Rate_Previous_Month", [GPS_Capture_Rate_Previous_Month],
        "GPS_Capture_Rate_Change", [GPS_Capture_Rate_Change],
        "Territory_Captured_MTD", [Territory_Captured_MTD],
        "Territory_Captured_YTD", [Territory_Captured_YTD]
    )

// ============================================
// SECTION 7: DISTINCT TERRITORIES VISITED
// ============================================
DEFINE
    MEASURE 'Fact_Visit'[Total_Visits] = COUNTROWS('Fact_Visit')
    
    MEASURE 'Fact_Visit'[Unique_Territories] = DISTINCTCOUNT('Fact_Visit'[territory_id])
    
    MEASURE 'Fact_Visit'[Active_Employees] = DISTINCTCOUNT('Fact_Visit'[EmployeeID])
    
    MEASURE 'Fact_Visit'[Territories_Per_Employee] = 
        DIVIDE([Unique_Territories], [Active_Employees], 0)
    
    MEASURE 'Fact_Visit'[Visits_Per_Territory] = 
        DIVIDE([Total_Visits], [Unique_Territories], 0)

EVALUATE
    SUMMARIZECOLUMNS(
        "Total_Visits", [Total_Visits],
        "Unique_Territories", [Unique_Territories],
        "Active_Employees", [Active_Employees],
        "Territories_Per_Employee", [Territories_Per_Employee],
        "Visits_Per_Territory", [Visits_Per_Territory]
    )

// ============================================
// SECTION 8: TERRITORY DISTRIBUTION BY CLIENT TYPE
// ============================================
DEFINE
    MEASURE 'Fact_Visit'[Total_Visits] = COUNTROWS('Fact_Visit')
    
    MEASURE 'Fact_Visit'[Unique_Territories] = DISTINCTCOUNT('Fact_Visit'[territory_id])
    
    MEASURE 'Fact_Visit'[Unique_Clients_Visited] = DISTINCTCOUNT('Fact_Visit'[ClientKey])
    
    MEASURE 'Fact_Visit'[Clients_Per_Territory] = 
        DIVIDE([Unique_Clients_Visited], [Unique_Territories], 0)

EVALUATE
    SUMMARIZECOLUMNS(
        'Dim_Client_Simple'[client_type],
        "Total_Visits", [Total_Visits],
        "Unique_Territories", [Unique_Territories],
        "Unique_Clients", [Unique_Clients_Visited],
        "Clients_Per_Territory", [Clients_Per_Territory]
    )
